'use client';

import { useMemo, useState } from 'react';
import { calculateQuoteCabinetPreview } from '@/lib/cabinet-overrides';
import type { BackMode, ModuleKey, PriceBookItem } from '@/lib/engineering';
import { formatMinor } from '@/lib/calculation';
import { INTL_LOCALES, type Locale } from '@/lib/i18n';
import { getCabinetMessages } from '@/lib/i18n-cabinet';
import type { SpecialHardwareRole } from '@/lib/special-hardware-presets';
import { deleteCabinet, duplicateCabinet, saveCabinet } from './actions';

type CabinetRow={id:string;module_key:string;name:string;width_mm:number|string;height_mm:number|string;depth_mm:number|string;quantity:number|string;construction_json:Record<string,unknown>;material_refs_json:Record<string,unknown>;hardware_refs_json:Record<string,unknown>;computed_cost_json:Record<string,unknown>};
type Props={projectId:string;currency:string;cabinets:CabinetRow[];priceBook:PriceBookItem[];targetMarginBps:number;overheadBps:number;taxBps:number;locale:Locale};
const byCategory=(items:PriceBookItem[],category:string)=>items.filter((item)=>item.category===category);
function asBackMode(value:unknown):BackMode{return value==='none'||value==='overlay'||value==='groove'?value:'groove';}
function asSpecialRole(value:unknown):SpecialHardwareRole|''{return value==='cargo'||value==='lift'||value==='corner'?value:'';}
function safeBigInt(value:unknown){try{return BigInt(typeof value==='string'||typeof value==='number'?value:0);}catch{return 0n;}}
function rowQuantity(value:unknown){const quantity=Number(value);return Number.isFinite(quantity)?Math.max(1,Math.min(999,Math.round(quantity))):1;}
function defaultShelfCount(moduleKey:ModuleKey){if(moduleKey==='b-door')return 1;if(moduleKey==='w-door'||moduleKey==='open')return 2;if(moduleKey==='t-door')return 4;if(moduleKey==='t-oven')return 2;if(moduleKey==='t-fridge')return 1;return 0;}
function hasFront(moduleKey:ModuleKey){return ['b-door','b-drawer','w-door','t-door','t-oven','t-fridge','dishwasher'].includes(moduleKey);}
function hasCarcass(moduleKey:ModuleKey){return moduleKey!=='dishwasher';}
function isHinged(moduleKey:ModuleKey){return ['b-door','w-door','t-door','t-oven'].includes(moduleKey);}
function usesStretchers(moduleKey:ModuleKey){return ['b-door','b-drawer','b-oven'].includes(moduleKey);}
function hardwareRole(item:PriceBookItem){const value=item.parameters_json?.hardwareRole;return typeof value==='string'?value:'';}

const partNames:Record<Locale,Record<string,string>>={
  ru:{'dishwasher-front':'Фасад ПММ',side:'Боковина',bottom:'Дно',stretcher:'Царга верхняя',top:'Верх',shelf:'Полка','door-front':'Фасад двери','drawer-front':'Фасад ящика','oven-front-top':'Фасад над духовкой','oven-front-bottom':'Фасад под духовкой','fridge-front':'Фасад холодильника',back:'Задняя стенка'},
  en:{'dishwasher-front':'Dishwasher front',side:'Side',bottom:'Bottom',stretcher:'Top stretcher',top:'Top',shelf:'Shelf / divider','door-front':'Door front','drawer-front':'Drawer front','oven-front-top':'Front above oven','oven-front-bottom':'Front below oven','fridge-front':'Fridge front',back:'Back panel'},
  cs:{'dishwasher-front':'Čelo myčky',side:'Bočnice',bottom:'Dno',stretcher:'Horní lub',top:'Horní díl',shelf:'Police / příčka','door-front':'Čelo dvířek','drawer-front':'Čelo zásuvky','oven-front-top':'Čelo nad troubou','oven-front-bottom':'Čelo pod troubou','fridge-front':'Čelo lednice',back:'Zadní stěna'},
  de:{'dishwasher-front':'Geschirrspülerfront',side:'Seite',bottom:'Boden',stretcher:'Obere Zarge',top:'Oberboden',shelf:'Boden / Trennwand','door-front':'Türfront','drawer-front':'Schubladenfront','oven-front-top':'Front über Backofen','oven-front-bottom':'Front unter Backofen','fridge-front':'Kühlschrankfront',back:'Rückwand'},
  pl:{'dishwasher-front':'Front zmywarki',side:'Bok',bottom:'Dno',stretcher:'Górna listwa',top:'Góra',shelf:'Półka / przegroda','door-front':'Front drzwi','drawer-front':'Front szuflady','oven-front-top':'Front nad piekarnikiem','oven-front-bottom':'Front pod piekarnikiem','fridge-front':'Front lodówki',back:'Plecy'},
};
const operationNames:Record<Locale,Record<string,string>>={
  ru:{cutting:'Распил','edge-banding':'Кромление','carcass-drilling':'Присадка корпуса','hinge-cup':'Чашка петли','drawer-drilling':'Присадка ящиков','back-groove':'Паз задней стенки'},
  en:{cutting:'Cutting','edge-banding':'Edge banding','carcass-drilling':'Carcass drilling','hinge-cup':'Hinge cup','drawer-drilling':'Drawer drilling','back-groove':'Back groove'},
  cs:{cutting:'Řezání','edge-banding':'Olepování hran','carcass-drilling':'Vrtání korpusu','hinge-cup':'Miska závěsu','drawer-drilling':'Vrtání zásuvek','back-groove':'Drážka zad'},
  de:{cutting:'Zuschnitt','edge-banding':'Kantenanleimen','carcass-drilling':'Korpusbohrung','hinge-cup':'Topfbohrung','drawer-drilling':'Schubladenbohrung','back-groove':'Rückwandnut'},
  pl:{cutting:'Cięcie','edge-banding':'Oklejanie','carcass-drilling':'Nawiercanie korpusu','hinge-cup':'Otwór pod zawias','drawer-drilling':'Nawiercanie szuflad','back-groove':'Rowek pod plecy'},
};
const hardwareNames:Record<Locale,Record<string,string>>={ru:{hinge:'Петли','drawer-system':'Комплекты ящиков','special-hardware':'Специальный механизм'},en:{hinge:'Hinges','drawer-system':'Drawer sets','special-hardware':'Special mechanism'},cs:{hinge:'Závěsy','drawer-system':'Sady zásuvek','special-hardware':'Speciální mechanismus'},de:{hinge:'Scharniere','drawer-system':'Schubladensätze','special-hardware':'Spezialmechanismus'},pl:{hinge:'Zawiasy','drawer-system':'Komplety szuflad','special-hardware':'Mechanizm specjalny'}};
const specialHardwareLabels:Record<Locale,Record<SpecialHardwareRole,string>>={
  ru:{cargo:'Карго / бутылочница',lift:'Lift-Up / Aventos',corner:'LeMans / Magic Corner'},
  en:{cargo:'Cargo / bottle pull-out',lift:'Lift-Up / Aventos',corner:'LeMans / Magic Corner'},
  cs:{cargo:'Cargo / výsuv',lift:'Lift-Up / Aventos',corner:'LeMans / Magic Corner'},
  de:{cargo:'Cargo / Flaschenauszug',lift:'Lift-Up / Aventos',corner:'LeMans / Magic Corner'},
  pl:{cargo:'Cargo / wysuw',lift:'Lift-Up / Aventos',corner:'LeMans / Magic Corner'},
};

export default function CabinetEditorClient({projectId,currency,cabinets,priceBook,targetMarginBps,overheadBps,taxBps,locale}:Props){
  const m=getCabinetMessages(locale); const intl=INTL_LOCALES[locale]; const money=(value:bigint)=>formatMinor(value,currency,intl);
  const first=cabinets[0]; const firstConstruction=first?.construction_json??{}; const firstMaterials=first?.material_refs_json??{}; const firstHardware=first?.hardware_refs_json??{}; const firstLegacyHardware=String(firstHardware.hardwareItemId??''); const initialKey=((first?.module_key as ModuleKey)??'b-drawer');
  const [cabinetId,setCabinetId]=useState(first?.id??''); const [moduleKey,setModuleKey]=useState<ModuleKey>(initialKey); const [name,setName]=useState(first?.name??m.defaultName); const [quantity,setQuantity]=useState(rowQuantity(first?.quantity)); const [width,setWidth]=useState(Number(first?.width_mm??800)); const [height,setHeight]=useState(Number(first?.height_mm??720)); const [depth,setDepth]=useState(Number(first?.depth_mm??560)); const [thickness,setThickness]=useState(Number(firstConstruction.thicknessMm??18)); const [gap,setGap]=useState(Number(firstConstruction.gapMm??2)); const [drawers,setDrawers]=useState(Number(firstConstruction.drawers??2)); const [doors,setDoors]=useState(Number(firstConstruction.doors??(initialKey==='t-fridge'||initialKey==='t-oven'?2:1))); const [shelfCount,setShelfCount]=useState(Number(firstConstruction.shelfCount??defaultShelfCount(initialKey))); const [stretcherDepth,setStretcherDepth]=useState(Number(firstConstruction.stretcherDepthMm??100)); const [shelfSetback,setShelfSetback]=useState(Number(firstConstruction.shelfSetbackMm??20)); const [applianceOpeningHeight,setApplianceOpeningHeight]=useState(Number(firstConstruction.applianceOpeningHeightMm??600)); const [backMode,setBackMode]=useState<BackMode>(asBackMode(firstConstruction.backMode)); const [backThickness,setBackThickness]=useState(Number(firstConstruction.backThicknessMm??4)); const [backInset,setBackInset]=useState(Number(firstConstruction.backInsetMm??10)); const [backGrooveDepth,setBackGrooveDepth]=useState(Number(firstConstruction.backGrooveDepthMm??8)); const [frontEdgeIncluded,setFrontEdgeIncluded]=useState(firstConstruction.frontEdgeIncluded!==false); const [labourHours,setLabourHours]=useState(Number(firstConstruction.labourHours??0)); const [boardItemId,setBoardItemId]=useState(String(firstMaterials.boardItemId??'')); const [frontItemId,setFrontItemId]=useState(String(firstMaterials.frontItemId??'')); const [backItemId,setBackItemId]=useState(String(firstMaterials.backItemId??'')); const [edgeItemId,setEdgeItemId]=useState(String(firstMaterials.edgeItemId??'')); const [hingeItemId,setHingeItemId]=useState(String(firstHardware.hingeItemId??(isHinged(initialKey)?firstLegacyHardware:''))); const [drawerItemId,setDrawerItemId]=useState(String(firstHardware.drawerItemId??(initialKey==='b-drawer'?firstLegacyHardware:''))); const [labourItemId,setLabourItemId]=useState(String(firstMaterials.labourItemId??'')); const [specialHardwareRole,setSpecialHardwareRole]=useState<SpecialHardwareRole|''>(asSpecialRole(firstConstruction.specialHardwareRole)); const [specialHardwareQty,setSpecialHardwareQty]=useState(Number(firstConstruction.specialHardwareQty??1)); const [specialHardwareItemId,setSpecialHardwareItemId]=useState(String(firstHardware.specialHardwareItemId??''));

  const preview=useMemo(()=>calculateQuoteCabinetPreview({moduleKey,widthMm:width,heightMm:height,depthMm:depth,thicknessMm:thickness,gapMm:gap,drawers,doors,shelfCount,stretcherDepthMm:stretcherDepth,shelfSetbackMm:shelfSetback,applianceOpeningHeightMm:applianceOpeningHeight,backMode:moduleKey==='dishwasher'?'none':backMode,backThicknessMm:backThickness,backInsetMm:backInset,backGrooveDepthMm:backGrooveDepth,frontEdgeIncluded,boardItemId,frontItemId,backItemId,edgeItemId,hingeItemId,drawerItemId,labourItemId,labourHours,specialHardwareRole:specialHardwareRole||undefined,specialHardwareQty,specialHardwareItemId:specialHardwareItemId||undefined},priceBook,{targetMarginBps,overheadBps,taxBps}),[moduleKey,width,height,depth,thickness,gap,drawers,doors,shelfCount,stretcherDepth,shelfSetback,applianceOpeningHeight,backMode,backThickness,backInset,backGrooveDepth,frontEdgeIncluded,boardItemId,frontItemId,backItemId,edgeItemId,hingeItemId,drawerItemId,labourItemId,labourHours,specialHardwareRole,specialHardwareQty,specialHardwareItemId,priceBook,targetMarginBps,overheadBps,taxBps]);
  const normalizedQuantity=rowQuantity(quantity); const savedProject=useMemo(()=>cabinets.reduce((totals,row)=>{const rowQty=BigInt(rowQuantity(row.quantity));return{trueCost:totals.trueCost+safeBigInt(row.computed_cost_json?.trueCostMinor)*rowQty,netSales:totals.netSales+safeBigInt(row.computed_cost_json?.netSalesMinor)*rowQty};},{trueCost:0n,netSales:0n}),[cabinets]);

  function loadCabinet(row:CabinetRow){const construction=row.construction_json??{};const materials=row.material_refs_json??{};const hardware=row.hardware_refs_json??{};const legacyHardware=String(hardware.hardwareItemId??'');const key=(row.module_key as ModuleKey)||'generic';setCabinetId(row.id);setModuleKey(key);setName(row.name);setQuantity(rowQuantity(row.quantity));setWidth(Number(row.width_mm));setHeight(Number(row.height_mm));setDepth(Number(row.depth_mm));setThickness(Number(construction.thicknessMm??18));setGap(Number(construction.gapMm??2));setDrawers(Number(construction.drawers??2));setDoors(Number(construction.doors??(key==='t-fridge'||key==='t-oven'?2:1)));setShelfCount(Number(construction.shelfCount??defaultShelfCount(key)));setStretcherDepth(Number(construction.stretcherDepthMm??100));setShelfSetback(Number(construction.shelfSetbackMm??20));setApplianceOpeningHeight(Number(construction.applianceOpeningHeightMm??600));setBackMode(asBackMode(construction.backMode));setBackThickness(Number(construction.backThicknessMm??4));setBackInset(Number(construction.backInsetMm??10));setBackGrooveDepth(Number(construction.backGrooveDepthMm??8));setFrontEdgeIncluded(construction.frontEdgeIncluded!==false);setLabourHours(Number(construction.labourHours??0));setBoardItemId(String(materials.boardItemId??''));setFrontItemId(String(materials.frontItemId??''));setBackItemId(String(materials.backItemId??''));setEdgeItemId(String(materials.edgeItemId??''));setHingeItemId(String(hardware.hingeItemId??(isHinged(key)?legacyHardware:'')));setDrawerItemId(String(hardware.drawerItemId??(key==='b-drawer'?legacyHardware:'')));setLabourItemId(String(materials.labourItemId??''));setSpecialHardwareRole(asSpecialRole(construction.specialHardwareRole));setSpecialHardwareQty(Number(construction.specialHardwareQty??1));setSpecialHardwareItemId(String(hardware.specialHardwareItemId??''));}
  function newCabinet(){setCabinetId('');setModuleKey('b-drawer');setName(m.defaultName);setQuantity(1);setWidth(800);setHeight(720);setDepth(560);setThickness(18);setGap(2);setDrawers(2);setDoors(1);setShelfCount(0);setStretcherDepth(100);setShelfSetback(20);setApplianceOpeningHeight(600);setBackMode('groove');setBackThickness(4);setBackInset(10);setBackGrooveDepth(8);setFrontEdgeIncluded(true);setLabourHours(0);setBoardItemId('');setFrontItemId('');setBackItemId('');setEdgeItemId('');setHingeItemId('');setDrawerItemId('');setLabourItemId('');setSpecialHardwareRole('');setSpecialHardwareQty(1);setSpecialHardwareItemId('');}
  const boards=byCategory(priceBook,'board');const fronts=byCategory(priceBook,'front');const edges=byCategory(priceBook,'edge');const hardware=byCategory(priceBook,'hardware');const labour=byCategory(priceBook,'labour');const specialHardwareItems=specialHardwareRole?hardware.filter((item)=>hardwareRole(item)===specialHardwareRole):[];const showCarcass=hasCarcass(moduleKey);const showFront=hasFront(moduleKey);const showDoors=['b-door','w-door','t-door','t-fridge'].includes(moduleKey);const showShelves=showCarcass&&!['b-drawer','b-oven'].includes(moduleKey);const showBack=showCarcass;const showStandardHinge=isHinged(moduleKey)&&specialHardwareRole!=='cargo'&&specialHardwareRole!=='lift';

  return <div className="contentGrid">
    <section className="panel treePanel"><div className="panelHeader"><span>{m.modules}</span><button className="iconButton" type="button" onClick={newCabinet}>+</button></div>{cabinets.map((row)=><button key={row.id} type="button" onClick={()=>loadCabinet(row)} className={`cabinetRow ${row.id===cabinetId?'selected':''}`}><span>{row.module_key}</span><div><strong>{row.name}{rowQuantity(row.quantity)>1?` × ${rowQuantity(row.quantity)}`:''}</strong><small>{Number(row.width_mm)} × {Number(row.height_mm)} × {Number(row.depth_mm)} {m.mm}</small></div></button>)}{!cabinets.length?<div className="miniEmpty">{m.addFirst}</div>:null}<div className="engineNote"><strong>{m.savedProject}</strong><span>{m.cost}: {money(savedProject.trueCost)}</span><span>{m.price}: {money(savedProject.netSales)}</span></div></section>

    <form action={saveCabinet} className="panel editorPanel"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="cabinetId" value={cabinetId}/>{moduleKey==='dishwasher'?<input type="hidden" name="backMode" value="none"/>:null}
      <div className="panelHeader"><div><span className="eyebrow">{cabinetId?m.editing:m.newModule} · MQ 0.2 · SPECIAL HARDWARE</span><h2>{name}</h2></div><div className="topActions">{cabinetId?<><button className="secondary" type="submit" formAction={duplicateCabinet}>{m.duplicate}</button><button className="secondary" type="submit" formAction={deleteCabinet} onClick={(event)=>{if(!window.confirm(m.confirmRemove))event.preventDefault();}}>{m.remove}</button></>:null}<button className="primary" type="submit">{m.save}</button></div></div>
      <div className="formSection"><h3>{m.typeAndSize}</h3><div className="fieldGrid"><label>{m.type}<select name="moduleKey" value={moduleKey} onChange={(event)=>setModuleKey(event.target.value as ModuleKey)}>{Object.entries(m.modulesMap).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>{m.name}<input name="name" value={name} onChange={(event)=>setName(event.target.value)}/></label><label>{m.quantity}<input name="quantity" type="number" min="1" max="999" step="1" value={quantity} onChange={(event)=>setQuantity(Number(event.target.value))}/></label><label>{m.carcassThickness}<input name="thicknessMm" type="number" min="1" step="0.1" value={thickness} onChange={(event)=>setThickness(Number(event.target.value))}/></label><label>{m.width}<input name="widthMm" type="number" min="1" value={width} onChange={(event)=>setWidth(Number(event.target.value))}/></label><label>{m.height}<input name="heightMm" type="number" min="1" value={height} onChange={(event)=>setHeight(Number(event.target.value))}/></label><label>{m.depth}<input name="depthMm" type="number" min="1" value={depth} onChange={(event)=>setDepth(Number(event.target.value))}/></label></div></div>
      <div className="formSection"><h3>{m.construction}</h3><div className="fieldGrid"><label>{m.frontGap}<input name="gapMm" type="number" min="0" step="0.5" value={gap} onChange={(event)=>setGap(Number(event.target.value))}/></label>{moduleKey==='b-drawer'?<label>{m.drawers}<input name="drawers" type="number" min="1" max="8" value={drawers} onChange={(event)=>setDrawers(Number(event.target.value))}/></label>:null}{showDoors?<label>{moduleKey==='t-fridge'?m.frontsHeight:m.doors}<input name="doors" type="number" min="1" max="4" value={doors} onChange={(event)=>setDoors(Number(event.target.value))}/></label>:null}{showShelves?<label>{m.shelves}<input name="shelfCount" type="number" min="0" max="12" value={shelfCount} onChange={(event)=>setShelfCount(Number(event.target.value))}/></label>:null}{usesStretchers(moduleKey)?<label>{m.stretcherDepth}<input name="stretcherDepthMm" type="number" min="20" value={stretcherDepth} onChange={(event)=>setStretcherDepth(Number(event.target.value))}/></label>:null}{showShelves&&shelfCount>0?<label>{m.shelfSetback}<input name="shelfSetbackMm" type="number" min="0" value={shelfSetback} onChange={(event)=>setShelfSetback(Number(event.target.value))}/></label>:null}{moduleKey==='t-oven'?<label>{m.ovenOpening}<input name="applianceOpeningHeightMm" type="number" min="400" max={Math.max(400,height-200)} value={applianceOpeningHeight} onChange={(event)=>setApplianceOpeningHeight(Number(event.target.value))}/></label>:null}{showFront?<label>{m.frontEdge}<select name="frontEdgeMode" value={frontEdgeIncluded?'included':'same-edge'} onChange={(event)=>setFrontEdgeIncluded(event.target.value==='included')}><option value="included">{m.edgeIncluded}</option><option value="same-edge">{m.sameEdge}</option></select></label>:<input type="hidden" name="frontEdgeMode" value="included"/>}<label>{m.labourHours}<input name="labourHours" type="number" step="0.1" min="0" value={labourHours} onChange={(event)=>setLabourHours(Number(event.target.value))}/></label></div></div>
      {showBack?<div className="formSection"><h3>{m.back}</h3><div className="fieldGrid"><label>{m.mounting}<select name="backMode" value={backMode} onChange={(event)=>setBackMode(event.target.value as BackMode)}><option value="groove">{m.groove}</option><option value="overlay">{m.overlay}</option><option value="none">{m.noBack}</option></select></label>{backMode!=='none'?<label>{m.thickness}<input name="backThicknessMm" type="number" min="1" step="0.1" value={backThickness} onChange={(event)=>setBackThickness(Number(event.target.value))}/></label>:null}{backMode==='groove'?<label>{m.grooveInset}<input name="backInsetMm" type="number" min="0" step="0.5" value={backInset} onChange={(event)=>setBackInset(Number(event.target.value))}/></label>:null}{backMode==='groove'?<label>{m.grooveDepth}<input name="backGrooveDepthMm" type="number" min="0" step="0.5" value={backGrooveDepth} onChange={(event)=>setBackGrooveDepth(Number(event.target.value))}/></label>:null}</div></div>:null}
      <div className="formSection"><h3>{m.materialsHardware}</h3><div className="fieldGrid two">{showCarcass?<PriceSelect name="boardItemId" label={m.board} value={boardItemId} setValue={setBoardItemId} items={boards} empty={m.notSelected}/>:null}{showFront?<PriceSelect name="frontItemId" label={m.front} value={frontItemId} setValue={setFrontItemId} items={fronts} empty={m.notSelected}/>:null}{showBack&&backMode!=='none'?<PriceSelect name="backItemId" label={m.backMaterial} value={backItemId} setValue={setBackItemId} items={boards} empty={m.notSelected}/>:null}<PriceSelect name="edgeItemId" label={m.edge} value={edgeItemId} setValue={setEdgeItemId} items={edges} empty={m.notSelected}/>{showStandardHinge?<PriceSelect name="hingeItemId" label={m.hinge} value={hingeItemId} setValue={setHingeItemId} items={hardware} empty={m.notSelected}/>:null}{moduleKey==='b-drawer'?<PriceSelect name="drawerItemId" label={m.drawerSet} value={drawerItemId} setValue={setDrawerItemId} items={hardware} empty={m.notSelected}/>:null}{specialHardwareRole?<PriceSelect name="specialHardwareItemId" label={specialHardwareLabels[locale][specialHardwareRole]} value={specialHardwareItemId} setValue={setSpecialHardwareItemId} items={specialHardwareItems} empty={m.notSelected}/>:null}<PriceSelect name="labourItemId" label={m.labourRate} value={labourItemId} setValue={setLabourItemId} items={labour} empty={m.notSelected}/></div></div>
      <div className="formSection"><h3>{m.parts}</h3><div className="tableWrap"><table><thead><tr><th>{m.part}</th><th>{m.material}</th><th>{m.qty}</th><th>{m.size}</th><th>{m.edgeColumn}</th></tr></thead><tbody>{preview.parts.map((part)=><tr key={part.key}><td><strong>{partNames[locale][part.key]??part.label}</strong></td><td>{m.roles[part.materialRole]??part.materialRole}</td><td>{part.quantity}</td><td>{part.lengthMm.toFixed(1)} × {part.widthMm.toFixed(1)} × {part.thicknessMm.toFixed(1)}</td><td>{part.edgeLengthMm>0?`${(part.edgeLengthMm/1000).toFixed(2)} ${m.meterPerPiece}`:'—'}</td></tr>)}</tbody></table></div></div>
      <div className="engineNote"><strong>Makster Engineering Core · MQ 0.2</strong><span>{preview.usage.partCount} {m.detailsPerUnit} · {m.carcass.toLowerCase()} {preview.usage.boardM2.toFixed(3)} m² · {m.front.toLowerCase()} {preview.usage.frontM2.toFixed(3)} m² · {m.backMaterial.toLowerCase()} {preview.usage.backM2.toFixed(3)} m² · {m.edge.toLowerCase()} {preview.usage.edgeM.toFixed(2)} m.</span>{normalizedQuantity>1?<span>{normalizedQuantity} {m.identicalModules}. {m.autoMultiply}</span>:null}</div>
    </form>

    <aside className="panel costPanel"><div className="panelHeader"><span>{m.unitCost}</span><span className="liveDot">LIVE</span></div><div className="costRows"><div><span>{m.carcass}</span><strong>{money(preview.detailCosts.carcass)}</strong></div><div><span>{m.backMaterial}</span><strong>{money(preview.detailCosts.back)}</strong></div><div><span>{m.fronts}</span><strong>{money(preview.detailCosts.fronts)}</strong></div><div><span>{m.edge}</span><strong>{money(preview.detailCosts.edges)}</strong></div><div><span>{m.hardware}</span><strong>{money(preview.detailCosts.hardware)}</strong></div><div><span>{m.operations}</span><strong>{money(preview.detailCosts.operations)}</strong></div><div><span>{m.labour}</span><strong>{money(preview.detailCosts.labour)}</strong></div><div className="soft"><span>{m.overhead}</span><strong>{money(preview.pricing.overheadMinor)}</strong></div></div><div className="trueCost"><span>{m.unitCost}</span><strong>{money(preview.pricing.trueCostMinor)}</strong></div><div className="priceHero"><span>{m.recommended}</span><strong>{money(preview.pricing.netSalesMinor)}</strong><small>{m.margin} {(preview.pricing.marginBps/100).toFixed(2)}%</small></div>
      {normalizedQuantity>1?<div className="engineNote"><strong>{m.total} × {normalizedQuantity}</strong><span>{m.cost}: {money(preview.pricing.trueCostMinor*BigInt(normalizedQuantity))}</span><span>{m.price}: {money(preview.pricing.netSalesMinor*BigInt(normalizedQuantity))}</span></div>:null}
      <div className="costRows"><div className="soft"><span>{m.operations}</span><strong>{preview.operations.length}</strong></div>{preview.operations.map((operation)=><div key={operation.key}><span>{operationNames[locale][operation.key]??operation.label}<br/><small>{operation.quantity.toFixed(operation.unit==='m'?2:0)} {operation.unit==='m'?'m':m.pcs}</small></span><strong>{money(operation.costMinor)}</strong></div>)}</div>
      {preview.hardware.length?<div className="costRows"><div className="soft"><span>{m.hardware}</span><strong>{preview.usage.hardwareQty} {m.pcs}</strong></div>{preview.hardware.map((line)=><div key={line.key}><span>{hardwareNames[locale][line.key]??line.label}<br/><small>{line.itemName??m.missingPrice} · {line.quantity}</small></span><strong>{money(line.costMinor)}</strong></div>)}</div>:null}
      {preview.warnings.length?<div className="warningList"><strong>{m.needsFill}</strong>{locale==='ru'?preview.warnings.map((warning,index)=><span key={index}>• {warning}</span>):<span>• {preview.warnings.length} {m.needsFill.toLowerCase()}</span>}</div>:<div className="notice success"><strong>{m.complete}</strong></div>}
      <div className="warningList"><strong>{m.assumptions}</strong>{locale==='ru'?preview.notes.map((note,index)=><span key={index}>• {note}</span>):<span>• Makster Pro keeps exact CNC, appliance-clearance and sheet-optimization engineering outside Quote.</span>}</div>
    </aside>
  </div>;
}

function PriceSelect({name,label,value,setValue,items,empty}:{name:string;label:string;value:string;setValue:(value:string)=>void;items:PriceBookItem[];empty:string}){return <label>{label}<select name={name} value={value} onChange={(event)=>setValue(event.target.value)}><option value="">{empty}</option>{items.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>;}
