import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AppShell } from '@/components/app-shell';
import { addPresetToProject } from '@/app/library/actions';
import type { PriceBookItem } from '@/lib/engineering';
import { getInterfaceLocale } from '@/lib/interface-locale';
import type { Locale } from '@/lib/i18n';
import { getProjectMessages } from '@/lib/i18n-project';
import { requireWorkspace } from '@/lib/workspace';
import CabinetEditor from './cabinet-editor';
import { ModuleOrderPanel } from './module-order-panel';
import { ProjectCommercial } from './project-commercial';

export const dynamic='force-dynamic';
type Props={params:Promise<{id:string}>;searchParams:Promise<{error?:string;saved?:string;duplicated?:string}>};
type PageText={back:string;library:string;priceBook:string;livePreview:string;duplicate:string;commercialSaved:string;manualAdded:string;manualRemoved:string;moduleAdded:string;moduleAddedHelp:string;moduleDuplicated:string;moduleDeleted:string;moduleMoved:string;priceBookEmpty:string;addRealPrices:string;noCurrencyPrices:string;currencyGuard:string;addCurrencyPrices:string;quickAdd:string;quickAddHelp:string;allPresets:string;errors:Record<string,string>;genericError:string;presets:Record<string,string>};
const texts:Record<Locale,PageText>={
  ru:{back:'← Проекты',library:'Библиотека модулей',priceBook:'Прайс-лист',livePreview:'Живой просмотр',duplicate:'Создана независимая копия проекта. Выпущенные предложения исходного проекта не копировались.',commercialSaved:'Итог проекта и параметры предложения сохранены.',manualAdded:'Нестандартная позиция добавлена в себестоимость проекта.',manualRemoved:'Нестандартная позиция удалена из рабочего расчёта.',moduleAdded:'Модуль добавлен из библиотеки.',moduleAddedHelp:'Выберите реальные материалы, фасад, кромку и фурнитуру и сохраните расчёт.',moduleDuplicated:'Модуль продублирован.',moduleDeleted:'Модуль удалён из рабочего проекта. Выпущенные предложения не изменены.',moduleMoved:'Порядок модулей обновлён.',priceBookEmpty:'Прайс-лист пуст.',addRealPrices:'Добавьте реальные цены',noCurrencyPrices:'Нет цен в',currencyGuard:'Этот проект не будет использовать позиции из другой валюты.',addCurrencyPrices:'Добавьте Price Book для',quickAdd:'Быстро добавить модуль',quickAddHelp:'Основные элементы кухни, включая глухой угол, можно добавить прямо из проекта.',allPresets:'Все пресеты →',errors:{'publish-client':'Перед выпуском предложения выберите и сохраните клиента.','publish-empty':'Нельзя выпустить пустое предложение. Добавьте хотя бы один модуль.','publish-incomplete':'Есть модули с неполным расчётом. Заполните материалы, фурнитуру и операции.','publish-extras':'Одна из выбранных услуг или отделочных позиций недоступна в Price Book для валюты проекта.','publish-margin-guard':'Profit Guardrail не разрешил выпуск: фактическая маржа ниже минимальной.','pricing-options':'Проверьте значения маржи и коммерческой корректировки.','extras-unit':'Выбранная услуга не соответствует категории, единице или валюте проекта.','pricebook-currency':'Для проекта выбрана позиция Price Book в другой валюте.'},genericError:'Не удалось выполнить действие',presets:{'base-door-600':'Низ 600 · дверь','base-drawer-600-3':'Низ 600 · 3 ящика','wall-door-600':'Верх 600','sink-600':'Мойка 600','base-oven-600':'Духовка 600','dishwasher-600':'ПММ 600','corner-base-blind-900':'Угол 900 · глухой','tall-oven-600':'Пенал духовки','tall-fridge-600':'Пенал холодильника'}},
  en:{back:'← Projects',library:'Module Library',priceBook:'Price Book',livePreview:'Live preview',duplicate:'An independent project copy was created. Published quotes from the source project were not copied.',commercialSaved:'Project totals and quote parameters saved.',manualAdded:'Custom cost item added to project cost.',manualRemoved:'Custom cost item removed from the working calculation.',moduleAdded:'Module added from the library.',moduleAddedHelp:'Choose real materials, front, edge band and hardware, then save the calculation.',moduleDuplicated:'Module duplicated.',moduleDeleted:'Module removed from the working project. Published quotes are unchanged.',moduleMoved:'Module order updated.',priceBookEmpty:'Price Book is empty.',addRealPrices:'Add real prices',noCurrencyPrices:'No prices in',currencyGuard:'This project will not use Price Book items from another currency.',addCurrencyPrices:'Add Price Book prices for',quickAdd:'Quick add module',quickAddHelp:'Core kitchen modules, including a blind corner, can be added directly from the project.',allPresets:'All presets →',errors:{'publish-client':'Select and save a customer before publishing.','publish-empty':'An empty quote cannot be published. Add at least one module.','publish-incomplete':'Some modules have incomplete costing. Fill materials, hardware and operations.','publish-extras':'A selected service or finishing item is unavailable in the Price Book for this project currency.','publish-margin-guard':'Profit Guardrail blocked publishing: actual margin is below the minimum.','pricing-options':'Check margin and commercial adjustment values.','extras-unit':'The selected service does not match the required category, unit or project currency.','pricebook-currency':'A Price Book item in another currency was selected for this project.'},genericError:'Could not complete the action',presets:{'base-door-600':'Base 600 · door','base-drawer-600-3':'Base 600 · 3 drawers','wall-door-600':'Wall 600','sink-600':'Sink 600','base-oven-600':'Oven 600','dishwasher-600':'Dishwasher 600','corner-base-blind-900':'Blind corner 900','tall-oven-600':'Tall oven','tall-fridge-600':'Tall fridge'}},
  cs:{back:'← Projekty',library:'Knihovna modulů',priceBook:'Ceník',livePreview:'Živý náhled',duplicate:'Byla vytvořena nezávislá kopie projektu. Vydané nabídky zdrojového projektu se nekopírovaly.',commercialSaved:'Souhrn projektu a parametry nabídky byly uloženy.',manualAdded:'Nestandardní položka byla přidána do nákladů projektu.',manualRemoved:'Nestandardní položka byla odebrána z pracovní kalkulace.',moduleAdded:'Modul byl přidán z knihovny.',moduleAddedHelp:'Vyberte skutečné materiály, čelo, hranu a kování a kalkulaci uložte.',moduleDuplicated:'Modul byl zkopírován.',moduleDeleted:'Modul byl odstraněn z pracovního projektu. Vydané nabídky se nezměnily.',moduleMoved:'Pořadí modulů bylo aktualizováno.',priceBookEmpty:'Ceník je prázdný.',addRealPrices:'Přidat skutečné ceny',noCurrencyPrices:'Nejsou ceny v',currencyGuard:'Projekt nebude používat položky ceníku v jiné měně.',addCurrencyPrices:'Přidat ceny ceníku pro',quickAdd:'Rychle přidat modul',quickAddHelp:'Základní kuchyňské moduly včetně slepého rohu lze přidat přímo z projektu.',allPresets:'Všechny presety →',errors:{'publish-client':'Před vydáním vyberte a uložte klienta.','publish-empty':'Prázdnou nabídku nelze vydat. Přidejte alespoň jeden modul.','publish-incomplete':'Některé moduly mají neúplnou kalkulaci. Doplňte materiály, kování a operace.','publish-extras':'Vybraná služba nebo dokončovací položka není v ceníku dostupná pro měnu projektu.','publish-margin-guard':'Profit Guardrail zablokoval vydání: skutečná marže je pod minimem.','pricing-options':'Zkontrolujte marže a obchodní úpravu.','extras-unit':'Vybraná služba neodpovídá kategorii, jednotce nebo měně projektu.','pricebook-currency':'Pro projekt byla vybrána položka ceníku v jiné měně.'},genericError:'Akci se nepodařilo dokončit',presets:{'base-door-600':'Spodní 600 · dvířka','base-drawer-600-3':'Spodní 600 · 3 zásuvky','wall-door-600':'Horní 600','sink-600':'Dřez 600','base-oven-600':'Trouba 600','dishwasher-600':'Myčka 600','corner-base-blind-900':'Slepý roh 900','tall-oven-600':'Vysoká trouba','tall-fridge-600':'Vysoká lednice'}},
  de:{back:'← Projekte',library:'Modulbibliothek',priceBook:'Preisliste',livePreview:'Live-Vorschau',duplicate:'Eine unabhängige Projektkopie wurde erstellt. Veröffentlichte Angebote des Quellprojekts wurden nicht kopiert.',commercialSaved:'Projektsumme und Angebotsparameter gespeichert.',manualAdded:'Sonderposition zu den Projektkosten hinzugefügt.',manualRemoved:'Sonderposition aus der Arbeitskalkulation entfernt.',moduleAdded:'Modul aus der Bibliothek hinzugefügt.',moduleAddedHelp:'Reale Materialien, Front, Kante und Beschläge wählen und die Kalkulation speichern.',moduleDuplicated:'Modul dupliziert.',moduleDeleted:'Modul aus dem Arbeitsprojekt entfernt. Veröffentlichte Angebote bleiben unverändert.',moduleMoved:'Modulreihenfolge aktualisiert.',priceBookEmpty:'Die Preisliste ist leer.',addRealPrices:'Reale Preise hinzufügen',noCurrencyPrices:'Keine Preise in',currencyGuard:'Dieses Projekt verwendet keine Preislistenpositionen in einer anderen Währung.',addCurrencyPrices:'Preise hinzufügen für',quickAdd:'Modul schnell hinzufügen',quickAddHelp:'Wichtige Küchenmodule einschließlich blindem Eckmodul können direkt im Projekt hinzugefügt werden.',allPresets:'Alle Presets →',errors:{'publish-client':'Vor Veröffentlichung Kunden auswählen und speichern.','publish-empty':'Ein leeres Angebot kann nicht veröffentlicht werden. Mindestens ein Modul hinzufügen.','publish-incomplete':'Einige Module sind unvollständig kalkuliert. Materialien, Beschläge und Operationen ergänzen.','publish-extras':'Eine gewählte Leistung oder Ausbauposition ist für die Projektwährung nicht in der Preisliste verfügbar.','publish-margin-guard':'Profit Guardrail blockiert: tatsächliche Marge unter Mindestwert.','pricing-options':'Marge und kommerzielle Anpassung prüfen.','extras-unit':'Die gewählte Leistung passt nicht zu Kategorie, Einheit oder Projektwährung.','pricebook-currency':'Für das Projekt wurde eine Preislistenposition in einer anderen Währung gewählt.'},genericError:'Aktion konnte nicht ausgeführt werden',presets:{'base-door-600':'Unterschrank 600 · Tür','base-drawer-600-3':'Unterschrank 600 · 3 Schubladen','wall-door-600':'Oberschrank 600','sink-600':'Spüle 600','base-oven-600':'Backofen 600','dishwasher-600':'Geschirrspüler 600','corner-base-blind-900':'Blind-Ecke 900','tall-oven-600':'Hochschrank Backofen','tall-fridge-600':'Hochschrank Kühlschrank'}},
  pl:{back:'← Projekty',library:'Biblioteka modułów',priceBook:'Cennik',livePreview:'Podgląd na żywo',duplicate:'Utworzono niezależną kopię projektu. Opublikowane oferty projektu źródłowego nie zostały skopiowane.',commercialSaved:'Podsumowanie projektu i parametry oferty zapisane.',manualAdded:'Niestandardową pozycję dodano do kosztu projektu.',manualRemoved:'Niestandardową pozycję usunięto z roboczej kalkulacji.',moduleAdded:'Moduł dodano z biblioteki.',moduleAddedHelp:'Wybierz rzeczywiste materiały, front, obrzeże i okucia, a następnie zapisz kalkulację.',moduleDuplicated:'Moduł zduplikowano.',moduleDeleted:'Moduł usunięto z roboczego projektu. Opublikowane oferty pozostają bez zmian.',moduleMoved:'Kolejność modułów zaktualizowana.',priceBookEmpty:'Cennik jest pusty.',addRealPrices:'Dodaj rzeczywiste ceny',noCurrencyPrices:'Brak cen w',currencyGuard:'Projekt nie będzie korzystać z pozycji cennika w innej walucie.',addCurrencyPrices:'Dodaj ceny cennika dla',quickAdd:'Szybko dodaj moduł',quickAddHelp:'Podstawowe moduły kuchenne, w tym ślepy narożnik, można dodać bezpośrednio z projektu.',allPresets:'Wszystkie presety →',errors:{'publish-client':'Przed publikacją wybierz i zapisz klienta.','publish-empty':'Nie można opublikować pustej oferty. Dodaj co najmniej jeden moduł.','publish-incomplete':'Niektóre moduły mają niepełną kalkulację. Uzupełnij materiały, okucia i operacje.','publish-extras':'Wybrana usługa lub pozycja wykończenia jest niedostępna w cenniku dla waluty projektu.','publish-margin-guard':'Profit Guardrail zablokował publikację: rzeczywista marża jest poniżej minimum.','pricing-options':'Sprawdź marże i korektę handlową.','extras-unit':'Wybrana usługa nie pasuje do kategorii, jednostki lub waluty projektu.','pricebook-currency':'Wybrano pozycję cennika w innej walucie niż projekt.'},genericError:'Nie udało się wykonać operacji',presets:{'base-door-600':'Dolna 600 · drzwi','base-drawer-600-3':'Dolna 600 · 3 szuflady','wall-door-600':'Górna 600','sink-600':'Zlew 600','base-oven-600':'Piekarnik 600','dishwasher-600':'Zmywarka 600','corner-base-blind-900':'Ślepy narożnik 900','tall-oven-600':'Słupek piekarnik','tall-fridge-600':'Słupek lodówka'}}
};
const presetKeys=['base-door-600','base-drawer-600-3','wall-door-600','sink-600','base-oven-600','dishwasher-600','corner-base-blind-900','tall-oven-600','tall-fridge-600'];
function safeBps(value:unknown,fallback:number,max=9_500){const parsed=Number(value);if(!Number.isFinite(parsed))return fallback;return Math.max(0,Math.min(max,Math.round(parsed)));}

export default async function ProjectPage({params,searchParams}:Props){
  const {id}=await params; const query=await searchParams; const {supabase,organization,role}=await requireWorkspace(); const locale=await getInterfaceLocale(); const t=texts[locale]; const commercialText=getProjectMessages(locale);
  const [projectResult,cabinetsResult,priceResult,subscriptionResult,clientsResult,quotesResult]=await Promise.all([
    supabase.from('projects').select('id, name, project_type, status, currency, client_id, settings, current_revision_id').eq('id',id).eq('organization_id',organization.id).maybeSingle(),
    supabase.from('quote_cabinets').select('id, module_key, name, width_mm, height_mm, depth_mm, quantity, construction_json, material_refs_json, hardware_refs_json, computed_cost_json').eq('project_id',id).eq('organization_id',organization.id).order('sort_order').order('created_at'),
    supabase.from('quote_price_book_items').select('id, category, name, unit, currency, purchase_price_minor, parameters_json').eq('organization_id',organization.id).eq('active',true).order('name'),
    supabase.from('quote_subscriptions').select('plan').eq('organization_id',organization.id).maybeSingle(),
    supabase.from('clients').select('id, display_name, email, phone').eq('organization_id',organization.id).is('archived_at',null).order('display_name'),
    supabase.from('client_commercial_quotes').select('id, quote_version, issued_at, valid_until, total_amount_minor, client_name').eq('project_id',id).eq('organization_id',organization.id).order('quote_version',{ascending:false}),
  ]);
  const project=projectResult.data; const cabinets=cabinetsResult.data; const priceBook=priceResult.data; const subscription=subscriptionResult.data;
  if(projectResult.error||!project)notFound(); if(cabinetsResult.error)throw new Error(`Failed to load modules: ${cabinetsResult.error.message}`); if(priceResult.error)throw new Error(`Failed to load Price Book: ${priceResult.error.message}`); if(clientsResult.error)throw new Error(`Failed to load customers: ${clientsResult.error.message}`); if(quotesResult.error)throw new Error(`Failed to load quote history: ${quotesResult.error.message}`);
  const projectPriceBook=(priceBook??[]).filter((item)=>item.currency===project.currency); const quoteHistory=quotesResult.data??[]; let statusEvents:{quote_id:string;status:string;created_at:string;note:string|null}[]=[];
  if(quoteHistory.length){const {data,error}=await supabase.from('client_quote_status_events').select('quote_id, status, created_at, note').eq('organization_id',organization.id).in('quote_id',quoteHistory.map((quote)=>quote.id)).order('created_at',{ascending:false});if(error)throw new Error(`Failed to load quote statuses: ${error.message}`);statusEvents=data??[];}
  const quoteSettings=(organization.settings?.quote??{}) as Record<string,unknown>; const targetMarginBps=safeBps(quoteSettings.targetMarginBps,3500); const minimumMarginBps=Math.min(targetMarginBps,safeBps(quoteSettings.minimumMarginBps,1500)); const overheadBps=safeBps(quoteSettings.overheadBps,0); const taxBps=safeBps((project.settings as Record<string,unknown>|null)?.taxBps,0,100_000);
  return <AppShell organizationName={organization.name} role={role} plan={(subscription?.plan??'free').toUpperCase()}>
    <header className="topbar"><div><span className="eyebrow">{project.project_type.toUpperCase()} · {project.status.toUpperCase()}</span><h1>{project.name}</h1></div><div className="topActions"><Link href="/projects" className="textLink">{t.back}</Link><Link href={`/library?project=${project.id}`} className="secondary linkButton">{t.library}</Link><Link href="/price-book" className="secondary linkButton">{t.priceBook}</Link><Link href={`/projects/${project.id}/quote`} className="secondary linkButton" target="_blank">{t.livePreview}</Link></div></header>
    {query.duplicated?<div className="pageContent compact"><div className="notice success">{t.duplicate}</div></div>:null}
    {query.error?<div className="pageContent compact"><div className="notice error">{t.errors[query.error]??`${t.genericError} (${query.error})`}</div></div>:null}
    {query.saved==='commercial'?<div className="pageContent compact"><div className="notice success">{t.commercialSaved}</div></div>:null}
    {query.saved==='manual-cost-added'?<div className="pageContent compact"><div className="notice success">{t.manualAdded}</div></div>:null}
    {query.saved==='manual-cost-removed'?<div className="pageContent compact"><div className="notice success">{t.manualRemoved}</div></div>:null}
    {query.saved==='module-added'?<div className="pageContent compact"><div className="notice success"><strong>{t.moduleAdded}</strong> {t.moduleAddedHelp}</div></div>:null}
    {query.saved==='module-duplicated'?<div className="pageContent compact"><div className="notice success">{t.moduleDuplicated}</div></div>:null}
    {query.saved==='module-deleted'?<div className="pageContent compact"><div className="notice success">{t.moduleDeleted}</div></div>:null}
    {query.saved==='module-moved'?<div className="pageContent compact"><div className="notice success">{t.moduleMoved}</div></div>:null}
    {!priceBook?.length?<div className="pageContent compact"><div className="notice warning">{t.priceBookEmpty} <Link href="/price-book">{t.addRealPrices}</Link>.</div></div>:null}
    {priceBook?.length&&!projectPriceBook.length?<div className="pageContent compact"><div className="notice warning"><strong>{t.noCurrencyPrices} {project.currency}.</strong> {t.currencyGuard} <Link href="/price-book">{t.addCurrencyPrices} {project.currency}</Link>.</div></div>:null}
    <section className="pageContent compact"><div className="panel"><div className="panelHeader"><div><span className="eyebrow">QUICK ADD · MQ 0.1.15</span><h2>{t.quickAdd}</h2><p className="muted">{t.quickAddHelp}</p></div><Link href={`/library?project=${project.id}`} className="textLink">{t.allPresets}</Link></div><div className="formActions padded" style={{flexWrap:'wrap'}}>{presetKeys.map((key)=><form action={addPresetToProject} key={key}><input type="hidden" name="projectId" value={project.id}/><input type="hidden" name="presetKey" value={key}/><input type="hidden" name="quantity" value="1"/><button className="secondary" type="submit">+ {t.presets[key]}</button></form>)}</div></div></section>
    <ProjectCommercial projectId={project.id} clientId={project.client_id} settings={project.settings as Record<string,unknown>} clients={clientsResult.data??[]} priceBook={projectPriceBook as never[]} cabinets={(cabinets??[]) as never[]} currency={project.currency} targetMarginBps={targetMarginBps} minimumMarginBps={minimumMarginBps} overheadBps={overheadBps} role={role} quoteHistory={quoteHistory} statusEvents={statusEvents} locale={locale}/>
    <ModuleOrderPanel projectId={project.id} cabinets={(cabinets??[]) as never[]}/>
    <CabinetEditor projectId={project.id} currency={project.currency} cabinets={(cabinets??[]) as never[]} priceBook={projectPriceBook as PriceBookItem[]} targetMarginBps={targetMarginBps} overheadBps={overheadBps} taxBps={taxBps}/>
  </AppShell>;
}
