import Link from 'next/link';
import { formatMinor } from '@/lib/calculation';
import { INTL_LOCALES, type Locale } from '@/lib/i18n';
import { getProjectMessages } from '@/lib/i18n-project';
import { applySellingAdjustment, manualCostTotal, readCommercialOptions, type CommercialVariantKey } from '@/lib/project-commercial-options';
import { calculateMeasuredExtras, readMeasuredExtraSettings } from '@/lib/project-measured-extras';
import { calculateProjectPricing, minorFromUnknown, readProjectCommercialSettings, type StoredCabinetCost } from '@/lib/project-pricing';
import { saveProjectCommercial } from './commercial-actions';
import { addManualCostLine, removeManualCostLine } from './manual-cost-actions';
import { publishCommercialQuote } from './publish-actions';
import { selectCommercialVariant } from './variant-actions';

type ClientRow={id:string;display_name:string;email:string|null;phone:string|null};
type PriceRow={id:string;category:string;name:string;unit:string;purchase_price_minor:number|string};
type QuoteRow={id:string;quote_version:number;issued_at:string;valid_until:string;total_amount_minor:number|string;client_name:string};
type StatusRow={quote_id:string;status:string;created_at:string;note:string|null};
type Props={projectId:string;clientId:string|null;settings:Record<string,unknown>|null;clients:ClientRow[];priceBook:PriceRow[];cabinets:StoredCabinetCost[];currency:string;targetMarginBps:number;minimumMarginBps:number;overheadBps:number;role:string;quoteHistory:QuoteRow[];statusEvents:StatusRow[];locale:Locale};

function selectedJob(items:PriceRow[],id:string){const item=items.find((row)=>row.id===id&&row.unit==='job');return minorFromUnknown(item?.purchase_price_minor);}
function options(items:PriceRow[],category:string,unit:string){return items.filter((item)=>item.category===category&&item.unit===unit);}
function latestStatus(id:string,events:StatusRow[]){return events.find((event)=>event.quote_id===id)?.status??'approved';}
const variants:CommercialVariantKey[]=['base','standard','premium'];
const variantNames:Record<Locale,Record<CommercialVariantKey,string>>={
  ru:{base:'Базовый',standard:'Стандарт',premium:'Премиум'},
  en:{base:'Base',standard:'Standard',premium:'Premium'},
  cs:{base:'Základní',standard:'Standard',premium:'Premium'},
  de:{base:'Basis',standard:'Standard',premium:'Premium'},
  pl:{base:'Bazowy',standard:'Standard',premium:'Premium'},
};

export function ProjectCommercial({projectId,clientId,settings,clients,priceBook,cabinets,currency,targetMarginBps,minimumMarginBps,overheadBps,role,quoteHistory,statusEvents,locale}:Props){
  const m=getProjectMessages(locale); const intl=INTL_LOCALES[locale];
  const money=(value:bigint)=>formatMinor(value,currency,intl);
  const variantName=(variant:CommercialVariantKey)=>variantNames[locale][variant];
  const moneyOption=(item:PriceRow)=>`${item.name} · ${formatMinor(minorFromUnknown(item.purchase_price_minor),currency,intl)}/${item.unit==='m2'?'m²':item.unit==='m'?'m':m.unitJob}`;
  const statusName:Record<string,string>={draft:m.statusDraft,approved:m.statusApproved,sent:m.statusSent,accepted:m.statusAccepted,rejected:m.statusRejected,expired:m.statusExpired,superseded:m.statusSuperseded};
  const commercial=readProjectCommercialSettings(settings); const commercialOptions=readCommercialOptions(settings,targetMarginBps); const measuredSettings=readMeasuredExtraSettings(settings); const measured=calculateMeasuredExtras(measuredSettings,priceBook); const manualTotal=manualCostTotal(commercialOptions.manualCostLines);
  const commonExtras={deliveryMinor:selectedJob(priceBook,commercial.deliveryItemId),installationMinor:selectedJob(priceBook,commercial.installationItemId),otherMinor:selectedJob(priceBook,commercial.otherItemId)+measured.totalMinor+manualTotal};
  const pricingByVariant=Object.fromEntries(variants.map((variant)=>{const basePricing=calculateProjectPricing(cabinets,commonExtras,{targetMarginBps:commercialOptions.variantMarginsBps[variant],overheadBps,taxBps:commercial.taxBps});return[variant,{...basePricing,adjusted:applySellingAdjustment(basePricing.pricing,commercial.taxBps,commercialOptions.adjustmentMode,commercialOptions.adjustmentBps)}];})) as Record<CommercialVariantKey,ReturnType<typeof calculateProjectPricing>&{adjusted:ReturnType<typeof applySellingAdjustment>}>;
  const selected=pricingByVariant[commercialOptions.selectedVariant]; const marginGuardPassed=selected.adjusted.marginBps>=minimumMarginBps; const quoteReady=selected.cabinetCount>0&&selected.incompleteCabinets===0&&measured.missing.length===0&&marginGuardPassed; const canPublish=['owner','admin','technologist'].includes(role);
  const delivery=options(priceBook,'delivery','job'); const installation=options(priceBook,'installation','job'); const other=options(priceBook,'other','job'); const worktops=options(priceBook,'worktop','m'); const plinths=options(priceBook,'plinth','m'); const fillers=options(priceBook,'filler','m2'); const decor=options(priceBook,'decor','m2');
  const updatingLabel=locale==='ru'?'Обновляем вариант…':locale==='cs'?'Aktualizujeme variantu…':locale==='de'?'Variante wird aktualisiert…':locale==='pl'?'Aktualizujemy wariant…':'Updating variant…';
  const savingLabel=locale==='ru'?'Сохраняем параметры…':locale==='cs'?'Ukládáme parametry…':locale==='de'?'Parameter werden gespeichert…':locale==='pl'?'Zapisujemy parametry…':'Saving settings…';
  const publishingLabel=locale==='ru'?'Выпускаем предложение…':locale==='cs'?'Vydáváme nabídku…':locale==='de'?'Angebot wird veröffentlicht…':locale==='pl'?'Publikujemy ofertę…':'Publishing quotation…';

  return <section className="pageContent compact" id="price"><div className="panel">
    <div className="panelHeader"><div><span className="eyebrow">{m.summary} · COMMERCIAL</span><h2>{m.commercialCalculation}</h2></div><div className="topActions"><Link href={`/projects/${projectId}/quote`} className="secondary linkButton" target="_blank">{m.livePreview}</Link>{canPublish?<form action={publishCommercialQuote} data-loading-label={publishingLabel}><input type="hidden" name="projectId" value={projectId}/><button className="primary" type="submit" disabled={!quoteReady||!clientId} data-loading-label={publishingLabel}>{m.publish} {variantName(commercialOptions.selectedVariant)}</button></form>:null}</div></div>
    <div className="padded">
      {!marginGuardPassed?<div className="notice error"><strong>{m.guardBlocked}</strong> {m.actualMargin} {(selected.adjusted.marginBps/100).toFixed(2)}% {m.belowMinimum} {(minimumMarginBps/100).toFixed(2)}%. {m.reduceDiscount}</div>:!quoteReady?<div className="notice warning"><strong>{m.draftQuote}</strong> {m.modules}: {selected.cabinetCount}; {m.incomplete}: {selected.incompleteCabinets}; {m.finishingMissing}: {measured.missing.length}.</div>:!clientId?<div className="notice warning"><strong>{m.chooseClient}</strong></div>:<div className="notice success"><strong>{m.readyToPublish}</strong> {m.variant} {variantName(commercialOptions.selectedVariant)}, {m.actualMargin.toLowerCase()} {(selected.adjusted.marginBps/100).toFixed(2)}% ≥ {(minimumMarginBps/100).toFixed(2)}%. {m.immutableRevision}</div>}
      <section className="metricGrid commercialMetrics"><article className="metricCard"><span>{m.directCost}</span><strong>{money(selected.pricing.directCostMinor)}</strong><small>{m.directCostHelp}</small></article><article className="metricCard"><span>{m.trueCost}</span><strong>{money(selected.pricing.trueCostMinor)}</strong><small>{m.overhead} {(overheadBps/100).toFixed(2)}%</small></article><article className="metricCard"><span>{m.priceBeforeAdjustment}</span><strong>{money(selected.adjusted.listNetSalesMinor)}</strong><small>{m.variant.toLowerCase()} {variantName(commercialOptions.selectedVariant)}</small></article><article className="metricCard"><span>{m.payable}</span><strong>{money(selected.adjusted.grossSalesMinor)}</strong><small>{m.actual} {(selected.adjusted.marginBps/100).toFixed(2)}% · {m.minimum} {(minimumMarginBps/100).toFixed(2)}%</small></article></section>
      <section className="metricGrid variantGrid" style={{marginBottom:20}}>{variants.map((variant)=>{const row=pricingByVariant[variant];const active=commercialOptions.selectedVariant===variant;const safe=row.adjusted.marginBps>=minimumMarginBps;return <form action={selectCommercialVariant} className="variantSelectForm" key={variant} data-loading-label={updatingLabel}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="selectedVariant" value={variant}/><button type="submit" className={`metricCard variantCard ${active?'variantCardActive':''}`} aria-pressed={active} data-loading-label={updatingLabel}><span>{active?m.selectedVariant:m.priceVariant}</span><strong>{variantName(variant)}</strong><small>{m.target} {(commercialOptions.variantMarginsBps[variant]/100).toFixed(2)}% · {m.actual} {(row.adjusted.marginBps/100).toFixed(2)}% {safe?'✓':m.belowMin}</small><div className="costRows" style={{padding:'10px 0 0'}}><div><span>{m.exclTax}</span><strong>{money(row.adjusted.netSalesMinor)}</strong></div><div><span>{m.payable}</span><strong>{money(row.adjusted.grossSalesMinor)}</strong></div></div></button></form>;})}</section>

      <form action={saveProjectCommercial} className="stackForm commercialForm" data-loading-label={savingLabel}><input type="hidden" name="projectId" value={projectId}/>
        <div className="formSection"><h3>{m.variantsTitle}</h3><p className="muted">{m.variantsHelp}</p><div className="formGrid3"><label>{variantName('base')}, {m.margin} %<input name="baseMarginPercent" type="number" min="0" max="95" step="0.01" defaultValue={(commercialOptions.variantMarginsBps.base/100).toFixed(2)}/></label><label>{variantName('standard')}, {m.margin} %<input name="standardMarginPercent" type="number" min="0" max="95" step="0.01" defaultValue={(commercialOptions.variantMarginsBps.standard/100).toFixed(2)}/></label><label>{variantName('premium')}, {m.margin} %<input name="premiumMarginPercent" type="number" min="0" max="95" step="0.01" defaultValue={(commercialOptions.variantMarginsBps.premium/100).toFixed(2)}/></label></div><div className="formGrid3"><label>{m.publishVariant}<select name="selectedVariant" defaultValue={commercialOptions.selectedVariant}><option value="base">{variantName('base')}</option><option value="standard">{variantName('standard')}</option><option value="premium">{variantName('premium')}</option></select></label><label>{m.adjustment}<select name="adjustmentMode" defaultValue={commercialOptions.adjustmentMode}><option value="none">{m.none}</option><option value="discount">{m.discount}</option><option value="surcharge">{m.surcharge}</option></select></label><label>{m.adjustmentPercent}<input name="adjustmentPercent" type="number" min="0" max="50" step="0.01" defaultValue={(commercialOptions.adjustmentBps/100).toFixed(2)}/></label></div>{commercialOptions.adjustmentMode!=='none'&&commercialOptions.adjustmentBps>0?<div className="engineNote"><strong>{commercialOptions.adjustmentMode==='discount'?m.discount:m.surcharge} {(commercialOptions.adjustmentBps/100).toFixed(2)}%</strong><span>{m.priceChange}: {money(selected.adjusted.sellingAdjustmentMinor)}. {m.marginAfter}: {(selected.adjusted.marginBps/100).toFixed(2)}%.</span></div>:null}<div className="engineNote"><strong>{m.workshopMinimum}: {(minimumMarginBps/100).toFixed(2)}%</strong><span>{m.guardServer}</span></div></div>
        <div className="formGrid3"><label>{m.client}<select name="clientId" defaultValue={clientId??''}><option value="">{m.notSelected}</option>{clients.map((client)=><option key={client.id} value={client.id}>{client.display_name}</option>)}</select></label><label>{m.tax}<input name="taxPercent" type="number" min="0" max="1000" step="0.01" defaultValue={(commercial.taxBps/100).toFixed(2)}/></label><label>{m.validityDays}<input name="validityDays" type="number" min="1" max="365" defaultValue={commercial.validityDays}/></label></div>
        <div className="formSection"><h3>{m.finishingTitle}</h3><p className="muted">{m.finishingHelp}</p><div className="formGrid2"><label>{m.worktop}<select name="worktopItemId" defaultValue={measuredSettings.worktopItemId}><option value="">{m.doNotInclude}</option>{worktops.map((item)=><option key={item.id} value={item.id}>{moneyOption(item)}</option>)}</select></label><label>{m.worktopLength}<input name="worktopLengthM" type="number" min="0" step="0.01" defaultValue={measuredSettings.worktopLengthM}/></label></div><div className="formGrid2"><label>{m.plinth}<select name="plinthItemId" defaultValue={measuredSettings.plinthItemId}><option value="">{m.doNotInclude}</option>{plinths.map((item)=><option key={item.id} value={item.id}>{moneyOption(item)}</option>)}</select></label><label>{m.plinthLength}<input name="plinthLengthM" type="number" min="0" step="0.01" defaultValue={measuredSettings.plinthLengthM}/></label></div><div className="formGrid2"><label>{m.fillers}<select name="fillerItemId" defaultValue={measuredSettings.fillerItemId}><option value="">{m.doNotInclude}</option>{fillers.map((item)=><option key={item.id} value={item.id}>{moneyOption(item)}</option>)}</select></label><label>{m.fillerArea}<input name="fillerAreaM2" type="number" min="0" step="0.01" defaultValue={measuredSettings.fillerAreaM2}/></label></div><div className="formGrid2"><label>{m.decor}<select name="decorItemId" defaultValue={measuredSettings.decorItemId}><option value="">{m.doNotInclude}</option>{decor.map((item)=><option key={item.id} value={item.id}>{moneyOption(item)}</option>)}</select></label><label>{m.decorArea}<input name="decorAreaM2" type="number" min="0" step="0.01" defaultValue={measuredSettings.decorAreaM2}/></label></div>{measured.lines.length?<div className="engineNote"><strong>{m.finishingCost}: {money(measured.totalMinor)}</strong>{measured.lines.map((line)=><span key={line.category}>{line.name}: {line.quantity.toFixed(2)} {line.unit==='m2'?'m²':'m'} · {money(line.amountMinor)}</span>)}</div>:null}</div>
        <div className="formGrid3"><label>{m.delivery}<select name="deliveryItemId" defaultValue={commercial.deliveryItemId}><option value="">{m.doNotInclude}</option>{delivery.map((item)=><option key={item.id} value={item.id}>{moneyOption(item)}</option>)}</select></label><label>{m.installation}<select name="installationItemId" defaultValue={commercial.installationItemId}><option value="">{m.doNotInclude}</option>{installation.map((item)=><option key={item.id} value={item.id}>{moneyOption(item)}</option>)}</select></label><label>{m.otherCosts}<select name="otherItemId" defaultValue={commercial.otherItemId}><option value="">{m.doNotInclude}</option>{other.map((item)=><option key={item.id} value={item.id}>{moneyOption(item)}</option>)}</select></label></div>
        <div className="formGrid3"><label>{m.documentLanguage}<select name="documentLocale" defaultValue={commercial.documentLocale}><option value="ru">Русский</option><option value="cs">Čeština</option><option value="de">Deutsch</option><option value="pl">Polski</option><option value="en">English</option></select></label><label>{m.deposit}<input name="depositPercent" type="number" min="0" max="100" step="0.01" defaultValue={(commercial.depositBps/100).toFixed(2)}/></label><label>{m.leadTime}<input name="productionLeadText" defaultValue={commercial.productionLeadText}/></label></div>
        <div className="formGrid2"><label>{m.paymentTerms}<textarea name="paymentTerms" rows={3} defaultValue={commercial.paymentTerms}/></label><label>{m.warranty}<textarea name="warrantyText" rows={3} defaultValue={commercial.warrantyText}/></label></div>
        <div className="formGrid3"><label>{m.newClientName}<input name="newClientName"/></label><label>{m.newClientEmail}<input name="newClientEmail" type="email"/></label><label>{m.newClientPhone}<input name="newClientPhone"/></label></div><div className="formGrid2"><label>{m.newClientAddress}<input name="newClientAddress"/></label><label>{m.clientComment}<textarea name="clientNote" rows={3} defaultValue={commercial.clientNote}/></label></div><div className="formActions"><Link href="/price-book" className="secondary linkButton">{m.priceBook}</Link><Link href="/settings/pricing" className="secondary linkButton">{m.pricingSettings}</Link><button type="submit" className="primary" data-loading-label={savingLabel}>{m.saveTerms}</button></div>
      </form>

      <section style={{marginTop:28}}><div className="panelHeader"><div><span className="eyebrow">{m.manualEyebrow}</span><h3>{m.manualTitle}</h3><p className="muted">{m.manualHelp}</p></div><strong>{money(manualTotal)}</strong></div>{commercialOptions.manualCostLines.length?<div className="priceList">{commercialOptions.manualCostLines.map((line)=><article className="priceRow" key={line.id}><div><span className="pill">{m.manualItem}</span><strong>{line.name}</strong></div><div className="priceValue"><strong>{money(line.costMinor)}</strong><form action={removeManualCostLine}><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="lineId" value={line.id}/><button className="textLink" type="submit">{m.remove}</button></form></div></article>)}</div>:<p className="muted">{m.noManual}</p>}<form action={addManualCostLine} className="stackForm" style={{marginTop:14}}><input type="hidden" name="projectId" value={projectId}/><div className="formGrid2"><label>{m.name}<input name="manualName" maxLength={200} placeholder={m.manualPlaceholder} required/></label><label>{m.cost}, {currency}<input name="manualCost" inputMode="decimal" placeholder="2500.00" required/></label></div><div className="formActions"><button className="secondary" type="submit">{m.addManual}</button></div></form></section>
      <section style={{marginTop:32}}><div className="panelHeader"><div><span className="eyebrow">{m.historyEyebrow}</span><h3>{quoteHistory.length?`${quoteHistory.length} ${m.issuedVersions}`:m.noVersions}</h3></div></div>{!quoteHistory.length?<p className="muted">{m.immutableSnapshot}</p>:<div className="priceList">{quoteHistory.map((quote)=>{const status=latestStatus(quote.id,statusEvents);return <article className="priceRow" key={quote.id}><div><span className="pill">v{quote.quote_version} · {statusName[status]??status}</span><strong>{quote.client_name}</strong><small>{new Intl.DateTimeFormat(intl).format(new Date(quote.issued_at))} · {m.until} {new Intl.DateTimeFormat(intl).format(new Date(quote.valid_until))}</small></div><div className="priceValue"><strong>{money(minorFromUnknown(quote.total_amount_minor))}</strong><small><Link href={`/projects/${projectId}/quote/${quote.id}`} className="textLink">{m.open}</Link></small></div></article>;})}</div>}</section>
    </div>
  </div></section>;
}
