import type { Locale } from '@/lib/i18n';

export type VisualCopy={
  catalog:string;catalogHelp:string;allPresets:string;visualTitle:string;visualHelp:string;selected:string;lineLength:string;modules:string;emptyTitle:string;emptyText:string;dimensions:string;cost:string;price:string;complete:string;needsCost:string;schematic:string;future3d:string;add:string;presets:Record<string,string>;
};

export const VISUAL_COPY:Record<Locale,VisualCopy>={
  ru:{catalog:'Модули',catalogHelp:'Нажмите на схему — модуль добавится в проект и появится на линии.',allPresets:'Вся библиотека →',visualTitle:'Visual Builder',visualHelp:'Схематическая сборка проекта. Каждый блок соответствует реальному выбранному модулю.',selected:'Выбранный модуль',lineLength:'Длина линии',modules:'модулей',emptyTitle:'Начните собирать мебель',emptyText:'Добавьте первый модуль слева. Здесь сразу появится его точная схема и размер.',dimensions:'Размеры',cost:'Себестоимость',price:'Цена',complete:'Расчёт готов',needsCost:'Нужно заполнить расчёт',schematic:'SCHEMATIC',future3d:'Позже этот же слот автоматически заменится GLB-моделью из Blender.',add:'Добавить',presets:{'base-door-600':'Низ 600 · дверь','base-drawer-600-3':'Низ 600 · 3 ящика','wall-door-600':'Верх 600','sink-600':'Мойка 600','base-oven-600':'Духовка 600','dishwasher-600':'ПММ 600','corner-base-blind-900':'Угол 900 · глухой','tall-oven-600':'Пенал духовки','tall-fridge-600':'Пенал холодильника'}},
  en:{catalog:'Modules',catalogHelp:'Choose a schematic to add the real module to the project line.',allPresets:'Full library →',visualTitle:'Visual Builder',visualHelp:'Schematic project assembly. Every block matches the actual selected module.',selected:'Selected module',lineLength:'Line length',modules:'modules',emptyTitle:'Start building the furniture',emptyText:'Add the first module on the left. Its exact schematic and size will appear here.',dimensions:'Dimensions',cost:'True cost',price:'Price',complete:'Costing ready',needsCost:'Costing needs input',schematic:'SCHEMATIC',future3d:'Later this exact slot will be replaced automatically by the Blender GLB model.',add:'Add',presets:{'base-door-600':'Base 600 · door','base-drawer-600-3':'Base 600 · 3 drawers','wall-door-600':'Wall 600','sink-600':'Sink 600','base-oven-600':'Oven 600','dishwasher-600':'Dishwasher 600','corner-base-blind-900':'Blind corner 900','tall-oven-600':'Tall oven','tall-fridge-600':'Tall fridge'}},
  cs:{catalog:'Moduly',catalogHelp:'Klikněte na schéma — skutečný modul se přidá do projektu a objeví se v sestavě.',allPresets:'Celá knihovna →',visualTitle:'Visual Builder',visualHelp:'Schematické sestavení projektu. Každý blok odpovídá skutečně zvolenému modulu.',selected:'Vybraný modul',lineLength:'Délka sestavy',modules:'modulů',emptyTitle:'Začněte skládat nábytek',emptyText:'Přidejte první modul vlevo. Zde se zobrazí jeho přesné schéma a rozměr.',dimensions:'Rozměry',cost:'Náklady',price:'Cena',complete:'Kalkulace hotová',needsCost:'Doplnit kalkulaci',schematic:'SCHEMATIC',future3d:'Později se tento slot automaticky nahradí GLB modelem z Blenderu.',add:'Přidat',presets:{'base-door-600':'Spodní 600 · dvířka','base-drawer-600-3':'Spodní 600 · 3 zásuvky','wall-door-600':'Horní 600','sink-600':'Dřez 600','base-oven-600':'Trouba 600','dishwasher-600':'Myčka 600','corner-base-blind-900':'Slepý roh 900','tall-oven-600':'Vysoká trouba','tall-fridge-600':'Vysoká lednice'}},
  de:{catalog:'Module',catalogHelp:'Schema anklicken — das echte Modul wird dem Projekt hinzugefügt und erscheint in der Zeile.',allPresets:'Ganze Bibliothek →',visualTitle:'Visual Builder',visualHelp:'Schematischer Projektaufbau. Jeder Block entspricht dem tatsächlich gewählten Modul.',selected:'Ausgewähltes Modul',lineLength:'Zeilenlänge',modules:'Module',emptyTitle:'Möbel zusammenstellen',emptyText:'Links das erste Modul hinzufügen. Hier erscheinen sofort das genaue Schema und die Maße.',dimensions:'Maße',cost:'Selbstkosten',price:'Preis',complete:'Kalkulation fertig',needsCost:'Kalkulation ergänzen',schematic:'SCHEMATIC',future3d:'Später wird dieser Slot automatisch durch das GLB-Modell aus Blender ersetzt.',add:'Hinzufügen',presets:{'base-door-600':'Unterschrank 600 · Tür','base-drawer-600-3':'Unterschrank 600 · 3 Schubladen','wall-door-600':'Oberschrank 600','sink-600':'Spüle 600','base-oven-600':'Backofen 600','dishwasher-600':'Geschirrspüler 600','corner-base-blind-900':'Blind-Ecke 900','tall-oven-600':'Hochschrank Backofen','tall-fridge-600':'Hochschrank Kühlschrank'}},
  pl:{catalog:'Moduły',catalogHelp:'Kliknij schemat — rzeczywisty moduł zostanie dodany do projektu i pojawi się w zabudowie.',allPresets:'Cała biblioteka →',visualTitle:'Visual Builder',visualHelp:'Schematyczne składanie projektu. Każdy blok odpowiada rzeczywiście wybranemu modułowi.',selected:'Wybrany moduł',lineLength:'Długość zabudowy',modules:'modułów',emptyTitle:'Zacznij składać meble',emptyText:'Dodaj pierwszy moduł po lewej. Tu od razu pojawi się jego dokładny schemat i wymiar.',dimensions:'Wymiary',cost:'Koszt',price:'Cena',complete:'Kalkulacja gotowa',needsCost:'Uzupełnij kalkulację',schematic:'SCHEMATIC',future3d:'Później ten sam slot zostanie automatycznie zastąpiony modelem GLB z Blendera.',add:'Dodaj',presets:{'base-door-600':'Dolna 600 · drzwi','base-drawer-600-3':'Dolna 600 · 3 szuflady','wall-door-600':'Górna 600','sink-600':'Zlew 600','base-oven-600':'Piekarnik 600','dishwasher-600':'Zmywarka 600','corner-base-blind-900':'Ślepy narożnik 900','tall-oven-600':'Słupek piekarnik','tall-fridge-600':'Słupek lodówka'}}
};

export const VISUAL_PRESETS=['base-door-600','base-drawer-600-3','wall-door-600','sink-600','base-oven-600','dishwasher-600','corner-base-blind-900','tall-oven-600','tall-fridge-600'] as const;
