import Link from 'next/link';
import type { Locale } from '@/lib/i18n';
import type { PriceBookSetupStep, PriceBookSetupStepKey } from '@/lib/price-book-readiness';
import { seedDemoPriceBook } from './actions';

type Status = {
  steps: PriceBookSetupStep[];
  requiredReady: number;
  requiredTotal: number;
  displayReady: number;
  total: number;
  demoSteps: number;
  coreReady: boolean;
  realItems: number;
  demoItems: number;
};

type Copy = {
  eyebrow:string; title:string; help:string; progress:string; coreReady:string; corePending:string;
  ready:string; demo:string; missing:string; optional:string; add:string; chooseDefault:string;
  demoTitle:string; demoHelp:string; demoButton:string; demoExists:string; realPrices:string;
  step:Record<PriceBookSetupStepKey,{label:string;help:string}>;
};

const copy:Record<Locale,Copy>={
  ru:{eyebrow:'НАСТРОЙКА МАСТЕРСКОЙ',title:'Price Book · готовность',help:'Makster показывает, какие закупочные данные нужны для честного расчёта. DEMO-позиции помогают изучить программу, но не считаются реальными ценами и блокируют готовность расчёта.',progress:'Готово',coreReady:'Базовый Price Book готов для реальных расчётов.',corePending:'Заполните обязательные шаги реальными ценами.',ready:'Готово',demo:'DEMO',missing:'Не заполнено',optional:'необязательно',add:'Добавить цену',chooseDefault:'Назначить по умолчанию',demoTitle:'Начать с DEMO-данных',demoHelp:'Создаёт наглядный пример материалов, фурнитуры, операций и труда. Все позиции явно помечены DEMO и не могут считаться готовыми к коммерческому предложению.',demoButton:'Создать DEMO Price Book',demoExists:'DEMO Price Book уже добавлен.',realPrices:'Реальных активных позиций',step:{board:{label:'1 · Корпус и задняя стенка',help:'Плита корпуса и материал задней стенки; назначьте значения по умолчанию.'},front:{label:'2 · Фасады',help:'Закупочная цена фасадного материала за м² или лист.'},edge:{label:'3 · Кромка',help:'Цена кромки за метр.'},hinge:{label:'4 · Петли',help:'Базовый комплект петель/петля и значение по умолчанию.'},drawer:{label:'5 · Системы ящиков',help:'Комплект ящика и значение по умолчанию.'},operations:{label:'6 · Производственные операции',help:'Распил, кромление, присадка корпуса, петель, ящиков и паз задней стенки.'},labour:{label:'7 · Стоимость часа',help:'Часовая ставка прямого труда.'},extras:{label:'8 · Дополнительные услуги',help:'Столешница, цоколь, доборы, доставка, монтаж и декор.'}}},
  en:{eyebrow:'WORKSHOP SETUP',title:'Price Book readiness',help:'Makster shows which purchase data is needed for trustworthy costing. DEMO items help explore the app, but they are not real prices and do not count as calculation readiness.',progress:'Ready',coreReady:'Core Price Book is ready for real costing.',corePending:'Complete the required steps with real prices.',ready:'Ready',demo:'DEMO',missing:'Missing',optional:'optional',add:'Add price',chooseDefault:'Choose default',demoTitle:'Start with DEMO data',demoHelp:'Creates an illustrative set of materials, hardware, operations and labour. Every item is marked DEMO and cannot make a commercial quote ready.',demoButton:'Create DEMO Price Book',demoExists:'DEMO Price Book already exists.',realPrices:'Real active items',step:{board:{label:'1 · Carcass & back',help:'Carcass board and back-panel material; choose defaults.'},front:{label:'2 · Fronts',help:'Front material purchase price per m² or sheet.'},edge:{label:'3 · Edge band',help:'Edge-band purchase price per metre.'},hinge:{label:'4 · Hinges',help:'Base hinge item/set and a default selection.'},drawer:{label:'5 · Drawer systems',help:'Drawer set and a default selection.'},operations:{label:'6 · Production operations',help:'Cutting, edge banding, carcass, hinge and drawer drilling, plus back groove.'},labour:{label:'7 · Labour rate',help:'Direct labour hourly rate.'},extras:{label:'8 · Extra services',help:'Worktop, plinth, fillers, delivery, installation and decor.'}}},
  cs:{eyebrow:'NASTAVENÍ DÍLNY',title:'Připravenost ceníku',help:'Makster ukazuje, které nákupní údaje jsou potřeba pro spolehlivou kalkulaci. DEMO položky slouží k vyzkoušení, ale nejsou skutečné ceny.',progress:'Hotovo',coreReady:'Základní ceník je připraven pro reálné kalkulace.',corePending:'Doplňte povinné kroky skutečnými cenami.',ready:'Hotovo',demo:'DEMO',missing:'Chybí',optional:'volitelné',add:'Přidat cenu',chooseDefault:'Nastavit výchozí',demoTitle:'Začít s DEMO daty',demoHelp:'Vytvoří názorný příklad materiálů, kování, operací a práce. DEMO položky nemohou označit obchodní kalkulaci jako hotovou.',demoButton:'Vytvořit DEMO ceník',demoExists:'DEMO ceník již existuje.',realPrices:'Skutečné aktivní položky',step:{board:{label:'1 · Korpus a záda',help:'Deska korpusu a materiál zad; nastavte výchozí položky.'},front:{label:'2 · Čela',help:'Nákupní cena čel za m² nebo desku.'},edge:{label:'3 · Hrana',help:'Cena hrany za metr.'},hinge:{label:'4 · Závěsy',help:'Základní závěs/sada a výchozí položka.'},drawer:{label:'5 · Systémy zásuvek',help:'Sada zásuvky a výchozí položka.'},operations:{label:'6 · Výrobní operace',help:'Řezání, olepování, vrtání korpusu, závěsů, zásuvek a drážka zad.'},labour:{label:'7 · Hodinová sazba',help:'Přímá hodinová sazba práce.'},extras:{label:'8 · Doplňkové služby',help:'Deska, sokl, výplně, doprava, montáž a dekor.'}}},
  de:{eyebrow:'WERKSTATT-SETUP',title:'Preisliste · Bereitschaft',help:'Makster zeigt, welche Einkaufspreise für eine belastbare Kalkulation benötigt werden. DEMO-Positionen dienen nur zum Kennenlernen.',progress:'Fertig',coreReady:'Die Basis-Preisliste ist für reale Kalkulationen bereit.',corePending:'Pflichtschritte mit realen Preisen vervollständigen.',ready:'Fertig',demo:'DEMO',missing:'Fehlt',optional:'optional',add:'Preis hinzufügen',chooseDefault:'Standard wählen',demoTitle:'Mit DEMO-Daten starten',demoHelp:'Erstellt ein anschauliches Beispiel für Materialien, Beschläge, Arbeitsgänge und Arbeit. DEMO-Positionen machen ein Angebot nicht veröffentlichungsbereit.',demoButton:'DEMO-Preisliste erstellen',demoExists:'DEMO-Preisliste ist bereits vorhanden.',realPrices:'Reale aktive Positionen',step:{board:{label:'1 · Korpus & Rückwand',help:'Korpusplatte und Rückwandmaterial; Standards wählen.'},front:{label:'2 · Fronten',help:'Einkaufspreis der Front pro m² oder Platte.'},edge:{label:'3 · Kante',help:'Kantenpreis pro Meter.'},hinge:{label:'4 · Scharniere',help:'Basis-Scharnier/Satz und Standardauswahl.'},drawer:{label:'5 · Schubladensysteme',help:'Schubladensatz und Standardauswahl.'},operations:{label:'6 · Fertigungsoperationen',help:'Zuschnitt, Kante, Korpus-, Scharnier- und Schubladenbohrung sowie Rückwandnut.'},labour:{label:'7 · Stundensatz',help:'Direkter Arbeitsstundensatz.'},extras:{label:'8 · Zusatzleistungen',help:'Arbeitsplatte, Sockel, Blenden, Lieferung, Montage und Dekor.'}}},
  pl:{eyebrow:'KONFIGURACJA PRACOWNI',title:'Gotowość cennika',help:'Makster pokazuje, jakie dane zakupowe są potrzebne do wiarygodnej kalkulacji. Pozycje DEMO służą do nauki i nie są realnymi cenami.',progress:'Gotowe',coreReady:'Podstawowy cennik jest gotowy do realnych kalkulacji.',corePending:'Uzupełnij wymagane kroki realnymi cenami.',ready:'Gotowe',demo:'DEMO',missing:'Brak',optional:'opcjonalne',add:'Dodaj cenę',chooseDefault:'Ustaw domyślne',demoTitle:'Zacznij od danych DEMO',demoHelp:'Tworzy przykładowe materiały, okucia, operacje i robociznę. Pozycje DEMO nie mogą oznaczyć oferty handlowej jako gotowej.',demoButton:'Utwórz cennik DEMO',demoExists:'Cennik DEMO już istnieje.',realPrices:'Realne aktywne pozycje',step:{board:{label:'1 · Korpus i plecy',help:'Płyta korpusu i materiał pleców; ustaw wartości domyślne.'},front:{label:'2 · Fronty',help:'Cena zakupu frontu za m² lub arkusz.'},edge:{label:'3 · Obrzeże',help:'Cena obrzeża za metr.'},hinge:{label:'4 · Zawiasy',help:'Podstawowy zawias/zestaw i wybór domyślny.'},drawer:{label:'5 · Systemy szuflad',help:'Zestaw szuflady i wybór domyślny.'},operations:{label:'6 · Operacje produkcyjne',help:'Cięcie, oklejanie, wiercenie korpusu, zawiasów, szuflad i rowek pod plecy.'},labour:{label:'7 · Stawka godzinowa',help:'Bezpośrednia stawka godzinowa pracy.'},extras:{label:'8 · Usługi dodatkowe',help:'Blat, cokół, blendy, dostawa, montaż i dekor.'}}},
};

function stateLabel(state:PriceBookSetupStep['state'], m:Copy){return state==='ready'?m.ready:state==='demo'?m.demo:m.missing;}

export function PriceBookSetup({locale,status,canManage}:{locale:Locale;status:Status;canManage:boolean}){
  const m=copy[locale];
  return <section className="panel" style={{marginBottom:18}}>
    <div className="panelHeader"><div><span className="eyebrow">{m.eyebrow}</span><h2>{m.title}</h2><p className="muted">{m.help}</p></div><div className="pill">{m.progress} {status.displayReady}/{status.total}</div></div>
    <div className="metricGrid" style={{padding:16,marginBottom:0}}>
      {status.steps.map((step)=>{const s=m.step[step.key];return <article className="metricCard" key={step.key}><span>{stateLabel(step.state,m)}{!step.required?` · ${m.optional}`:''}</span><strong style={{fontSize:17}}>{s.label}</strong><small>{s.help}</small>{step.key==='operations'&&step.missingKeys?.length?<small>{step.missingKeys.join(' · ')}</small>:null}<div className="formActions" style={{marginTop:8,flexWrap:'wrap'}}>{step.state!=='ready'?<Link href="#add-price" className="textLink">{m.add}</Link>:null}{step.required&&step.key!=='operations'?<Link href="/settings/pricing#price-book-defaults" className="textLink">{m.chooseDefault}</Link>:null}</div></article>;})}
    </div>
    <div className={status.coreReady?'notice success':'notice warning'} style={{margin:'0 16px 16px'}}><strong>{status.coreReady?m.coreReady:m.corePending}</strong> {m.realPrices}: {status.realItems}.</div>
    {canManage?<div className="engineNote" style={{margin:'0 16px 16px'}}><strong>{m.demoTitle}</strong><span>{m.demoHelp}</span>{status.demoItems?<span>{m.demoExists}</span>:<form action={seedDemoPriceBook}><button className="secondary" type="submit">{m.demoButton}</button></form>}</div>:null}
  </section>;
}
