import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { formatMinor } from '@/lib/calculation';
import { loadPublicQuote } from '@/lib/client-quote-access';
import { minorFromUnknown } from '@/lib/project-pricing';
import { respondToPublicQuote } from './actions';

export const dynamic = 'force-dynamic';
export const revalidate = 0;
export const metadata: Metadata = { robots:{ index:false, follow:false }, referrer:'no-referrer' };

type Props = { params: Promise<{ token:string }>; searchParams: Promise<{ responded?:string; error?:string }> };

type Labels = {
  title:string; client:string; project:string; issued:string; valid:string; scope:string; module:string; dimensions:string; quantity:string;
  included:string; net:string; tax:string; total:string; terms:string; deposit:string; lead:string; payment:string; warranty:string; note:string;
  pdf:string; accept:string; reject:string; decisionNote:string; decisionHelp:string; accepted:string; rejected:string; expired:string; sent:string; approved:string;
  acceptedThanks:string; rejectedThanks:string; error:string; version:string; revision:string;
};

const labels: Record<string, Labels> = {
  ru:{ title:'Коммерческое предложение',client:'Клиент',project:'Проект',issued:'Дата',valid:'Действительно до',scope:'Состав проекта',module:'Модуль',dimensions:'Размеры',quantity:'Кол-во',included:'Включено',net:'Итого без НДС',tax:'НДС / налог',total:'К оплате',terms:'Условия',deposit:'Аванс',lead:'Срок изготовления',payment:'Оплата',warranty:'Гарантия / условия',note:'Примечание',pdf:'Скачать PDF',accept:'Принять предложение',reject:'Отклонить',decisionNote:'Комментарий (необязательно)',decisionHelp:'Ответ является финальным для этой версии предложения.',accepted:'Принято',rejected:'Отклонено',expired:'Истекло',sent:'Отправлено',approved:'Выпущено',acceptedThanks:'Спасибо. Ваше принятие предложения зафиксировано.',rejectedThanks:'Ваш отказ по этой версии предложения зафиксирован.',error:'Не удалось сохранить ответ. Возможно, ссылка или предложение уже недействительны.',version:'Версия предложения',revision:'Ревизия' },
  en:{ title:'Quotation',client:'Client',project:'Project',issued:'Issued',valid:'Valid until',scope:'Project scope',module:'Module',dimensions:'Dimensions',quantity:'Qty',included:'Included',net:'Total excl. tax',tax:'Tax',total:'Total payable',terms:'Terms',deposit:'Deposit',lead:'Production lead time',payment:'Payment',warranty:'Warranty / terms',note:'Note',pdf:'Download PDF',accept:'Accept quotation',reject:'Reject',decisionNote:'Comment (optional)',decisionHelp:'Your response is final for this version of the quotation.',accepted:'Accepted',rejected:'Rejected',expired:'Expired',sent:'Sent',approved:'Issued',acceptedThanks:'Thank you. Your acceptance has been recorded.',rejectedThanks:'Your rejection of this quotation version has been recorded.',error:'Your response could not be saved. The link or quotation may no longer be valid.',version:'Quote version',revision:'Revision' },
  cs:{ title:'Cenová nabídka',client:'Klient',project:'Projekt',issued:'Datum',valid:'Platnost do',scope:'Rozsah projektu',module:'Modul',dimensions:'Rozměry',quantity:'Počet',included:'Zahrnuto',net:'Celkem bez DPH',tax:'DPH / daň',total:'Celkem k úhradě',terms:'Podmínky',deposit:'Záloha',lead:'Doba výroby',payment:'Platba',warranty:'Záruka / podmínky',note:'Poznámka',pdf:'Stáhnout PDF',accept:'Přijmout nabídku',reject:'Odmítnout',decisionNote:'Komentář (volitelné)',decisionHelp:'Vaše odpověď je pro tuto verzi nabídky konečná.',accepted:'Přijato',rejected:'Odmítnuto',expired:'Platnost vypršela',sent:'Odesláno',approved:'Vydáno',acceptedThanks:'Děkujeme. Přijetí nabídky bylo zaznamenáno.',rejectedThanks:'Odmítnutí této verze nabídky bylo zaznamenáno.',error:'Odpověď se nepodařilo uložit. Odkaz nebo nabídka již nemusí být platné.',version:'Verze nabídky',revision:'Revize' },
  de:{ title:'Angebot',client:'Kunde',project:'Projekt',issued:'Datum',valid:'Gültig bis',scope:'Projektumfang',module:'Modul',dimensions:'Maße',quantity:'Anzahl',included:'Enthalten',net:'Summe netto',tax:'MwSt. / Steuer',total:'Gesamtbetrag',terms:'Bedingungen',deposit:'Anzahlung',lead:'Fertigungszeit',payment:'Zahlung',warranty:'Garantie / Bedingungen',note:'Hinweis',pdf:'PDF herunterladen',accept:'Angebot annehmen',reject:'Ablehnen',decisionNote:'Kommentar (optional)',decisionHelp:'Ihre Antwort ist für diese Angebotsversion endgültig.',accepted:'Angenommen',rejected:'Abgelehnt',expired:'Abgelaufen',sent:'Gesendet',approved:'Ausgestellt',acceptedThanks:'Vielen Dank. Ihre Annahme wurde gespeichert.',rejectedThanks:'Ihre Ablehnung dieser Angebotsversion wurde gespeichert.',error:'Ihre Antwort konnte nicht gespeichert werden. Der Link oder das Angebot ist möglicherweise nicht mehr gültig.',version:'Angebotsversion',revision:'Revision' },
  pl:{ title:'Oferta',client:'Klient',project:'Projekt',issued:'Data',valid:'Ważna do',scope:'Zakres projektu',module:'Moduł',dimensions:'Wymiary',quantity:'Ilość',included:'Uwzględniono',net:'Razem netto',tax:'VAT / podatek',total:'Razem do zapłaty',terms:'Warunki',deposit:'Zaliczka',lead:'Termin wykonania',payment:'Płatność',warranty:'Gwarancja / warunki',note:'Uwagi',pdf:'Pobierz PDF',accept:'Zaakceptuj ofertę',reject:'Odrzuć',decisionNote:'Komentarz (opcjonalnie)',decisionHelp:'Odpowiedź jest ostateczna dla tej wersji oferty.',accepted:'Zaakceptowano',rejected:'Odrzucono',expired:'Wygasła',sent:'Wysłano',approved:'Wystawiono',acceptedThanks:'Dziękujemy. Akceptacja oferty została zapisana.',rejectedThanks:'Odrzucenie tej wersji oferty zostało zapisane.',error:'Nie udało się zapisać odpowiedzi. Link lub oferta mogą być już nieważne.',version:'Wersja oferty',revision:'Rewizja' },
};

const intlLocale: Record<string,string> = { ru:'ru-RU', en:'en-GB', cs:'cs-CZ', de:'de-DE', pl:'pl-PL' };

export default async function PublicQuotePage({ params, searchParams }: Props) {
  const { token } = await params;
  const query = await searchParams;
  const access = await loadPublicQuote(token);
  if (!access) notFound();
  const snapshot = access.snapshot;
  const t = labels[snapshot.locale] ?? labels.ru;
  const locale = intlLocale[snapshot.locale] ?? 'ru-RU';
  const date = (value:string) => new Intl.DateTimeFormat(locale, { year:'numeric', month:'long', day:'numeric' }).format(new Date(value));
  const statusLabel = access.status === 'accepted' ? t.accepted : access.status === 'rejected' ? t.rejected : access.status === 'expired' ? t.expired : access.status === 'sent' ? t.sent : t.approved;
  const deposit = minorFromUnknown(snapshot.amounts.depositMinor);

  return <main className="publicQuote">
    <style>{`
      body{margin:0;background:#edf3ef;color:#18211d}.publicQuote{max-width:920px;margin:28px auto;background:#fff;padding:48px;box-shadow:0 18px 60px rgba(24,33,29,.12);font-family:Inter,Arial,sans-serif}.head{display:flex;justify-content:space-between;gap:28px;border-bottom:2px solid #18211d;padding-bottom:22px}.brand{font-size:25px;font-weight:800;color:#196c50}.brand small{display:block;font-size:11px;color:#68746d;margin-top:4px}.ref{text-align:right;color:#68746d;font-size:12px}.ref strong{display:block;color:#18211d;font-size:18px}.title{margin:34px 0 22px}.title h1{font-size:32px;margin:0}.status{display:inline-block;margin-top:10px;border:1px solid #1f7a5a;color:#1f7a5a;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:800}.notice{padding:14px 16px;border-radius:10px;margin:18px 0;background:#eef7f2}.notice.error{background:#faeeee;color:#8b3131}.info{display:grid;grid-template-columns:1fr 1fr;gap:28px;margin:24px 0 32px}.info h3{font-size:11px;text-transform:uppercase;color:#68746d}.info span,.info strong{display:block;margin-top:4px}.table{width:100%;border-collapse:collapse;margin:18px 0 28px}.table th,.table td{text-align:left;padding:11px;border-bottom:1px solid #dfe7e2}.table th{font-size:11px;text-transform:uppercase;color:#68746d}.totals{width:min(440px,100%);margin-left:auto}.totals div{display:flex;justify-content:space-between;padding:8px 0}.totals .grand{border-top:2px solid #18211d;font-size:21px;font-weight:800;padding-top:13px}.terms{margin-top:30px;padding:18px;background:#f4f7f5;border-radius:12px}.terms div{margin:7px 0}.actions{margin-top:34px;border-top:1px solid #dfe7e2;padding-top:24px}.actions form{display:grid;gap:12px}.actions textarea{min-height:76px;border:1px solid #cfd9d3;border-radius:9px;padding:11px;font:inherit}.buttons{display:flex;gap:10px;flex-wrap:wrap}.buttons button,.pdf{border:0;border-radius:9px;padding:12px 16px;text-decoration:none;font-weight:800;cursor:pointer}.accept{background:#1f7a5a;color:#fff}.reject{background:#f5e8e8;color:#8b3131}.pdf{display:inline-block;background:#edf2ef;color:#244438;margin-top:16px}.muted{color:#68746d;font-size:12px}.footer{margin-top:38px;padding-top:18px;border-top:1px solid #dfe7e2;color:#68746d;font-size:11px}@media(max-width:700px){.publicQuote{margin:0;padding:24px}.head,.info{display:grid;grid-template-columns:1fr}.ref{text-align:left}.title h1{font-size:27px}}@media print{body{background:#fff}.publicQuote{max-width:none;margin:0;padding:14mm;box-shadow:none}.actions,.pdf{display:none}@page{size:A4;margin:0}}
    `}</style>
    <header className="head"><div className="brand">{snapshot.supplier.tradeName}<small>{snapshot.supplier.legalName}</small></div><div className="ref"><strong>MQ-v{access.quoteVersion}</strong><span>{t.issued}: {date(access.issuedAt)}</span><span>{t.valid}: {date(access.validUntil)}</span></div></header>
    <section className="title"><h1>{t.title}</h1><span className="status">{statusLabel}</span></section>
    {query.responded === 'accepted' ? <div className="notice">{t.acceptedThanks}</div> : null}
    {query.responded === 'rejected' ? <div className="notice">{t.rejectedThanks}</div> : null}
    {query.error ? <div className="notice error">{t.error}</div> : null}
    <section className="info"><div><h3>{t.client}</h3><strong>{snapshot.client.name}</strong>{snapshot.client.email ? <span>{snapshot.client.email}</span> : null}{snapshot.client.phone ? <span>{snapshot.client.phone}</span> : null}{snapshot.client.address ? <span>{snapshot.client.address}</span> : null}</div><div><h3>{t.project}</h3><strong>{snapshot.project.name}</strong><span>{t.revision} {snapshot.project.revisionNumber}</span><span>{t.version} {access.quoteVersion}</span></div></section>
    <h2>{t.scope}</h2>
    <table className="table"><thead><tr><th>{t.module}</th><th>{t.dimensions}</th><th>{t.quantity}</th></tr></thead><tbody>{snapshot.modules.map((module) => <tr key={module.id}><td>{module.name}</td><td>{module.widthMm} × {module.heightMm} × {module.depthMm} mm</td><td>{module.quantity}</td></tr>)}</tbody></table>
    {snapshot.extras.length ? <p><strong>{t.included}:</strong> {snapshot.extras.map((extra) => extra.name).join(' · ')}</p> : null}
    <section className="totals"><div><span>{t.net}</span><strong>{formatMinor(minorFromUnknown(snapshot.amounts.netMinor), snapshot.currency, locale)}</strong></div>{snapshot.amounts.taxBps > 0 ? <div><span>{t.tax} {(snapshot.amounts.taxBps/100).toFixed(2)}%</span><strong>{formatMinor(minorFromUnknown(snapshot.amounts.taxMinor), snapshot.currency, locale)}</strong></div> : null}<div className="grand"><span>{t.total}</span><strong>{formatMinor(minorFromUnknown(snapshot.amounts.totalMinor), snapshot.currency, locale)}</strong></div></section>
    {(snapshot.terms.depositBps > 0 || snapshot.terms.productionLeadText || snapshot.terms.paymentTerms || snapshot.terms.warrantyText || snapshot.terms.clientNote) ? <section className="terms"><h3>{t.terms}</h3>{snapshot.terms.depositBps > 0 ? <div><strong>{t.deposit}:</strong> {(snapshot.terms.depositBps/100).toFixed(2)}% · {formatMinor(deposit, snapshot.currency, locale)}</div> : null}{snapshot.terms.productionLeadText ? <div><strong>{t.lead}:</strong> {snapshot.terms.productionLeadText}</div> : null}{snapshot.terms.paymentTerms ? <div><strong>{t.payment}:</strong> {snapshot.terms.paymentTerms}</div> : null}{snapshot.terms.warrantyText ? <div><strong>{t.warranty}:</strong> {snapshot.terms.warrantyText}</div> : null}{snapshot.terms.clientNote ? <div><strong>{t.note}:</strong> {snapshot.terms.clientNote}</div> : null}</section> : null}
    <a className="pdf" href={`/q/${token}/pdf`}>{t.pdf}</a>
    <section className="actions">
      {access.actionAllowed ? <form action={respondToPublicQuote}><input type="hidden" name="token" value={token}/><textarea name="note" maxLength={500} placeholder={t.decisionNote}/><p className="muted">{t.decisionHelp}</p><div className="buttons"><button className="accept" name="decision" value="accepted">{t.accept}</button><button className="reject" name="decision" value="rejected">{t.reject}</button></div></form> : <div className="notice">{statusLabel}</div>}
    </section>
    <footer className="footer">{snapshot.supplier.tradeName}{snapshot.supplier.footerText ? ` · ${snapshot.supplier.footerText}` : ''}<br/>Makster Quote · MQ 0.1.5</footer>
  </main>;
}
