import type { QuoteModulePreset } from './module-presets';

export type ReadyModuleLibraryRow = {
  module_code: string;
  template_code: string;
  version: number;
  release_status: string;
  width_mm: number | string;
  depth_mm: number | string;
  body_height_mm: number | string;
  preview_bucket: string | null;
  preview_path: string | null;
  preview_mime_type: string | null;
  metadata?: Record<string, unknown> | null;
};

export type ReadyModulePreview = {
  moduleCode: string;
  version: number;
  bucket: string;
  path: string;
};

const TEMPLATE_CODES_BY_GROUP: Partial<Record<QuoteModulePreset['group'], string[]>> = {
  'base-door': ['M_BASE_DOOR'],
  'base-drawer': [
    'M_BASE_DRAWER',
    'M_BASE_DRAWER_TANDEMBOX',
    'M_BASE_DRAWER_WOOD_UNDERMOUNT',
  ],
};

function sameMm(value: number | string, expected: number) {
  return Math.abs(Number(value) - expected) < 0.001;
}

function textValue(value: unknown) {
  return typeof value === 'string' ? value.trim() : '';
}

function previewCanBeShown(row: ReadyModuleLibraryRow) {
  const source = row.metadata ?? {};
  const style = textValue(source.preview_style || source.previewStyle).toLowerCase();
  if (source.preview_approved === false || source.previewApproved === false) return false;
  if (source.preview_approved === true || source.previewApproved === true || style === 'studio_v1' || style === 'studio') return true;

  // The first drawer previews (TANDEMBOX V12 / WOOD V13) were generated by the old
  // dark preview pipeline and are not readable in the Quote library. Until those
  // modules are republished by the newer renderer, use the clean schematic card.
  if ((row.template_code === 'M_BASE_DRAWER_TANDEMBOX' && Number(row.version) <= 12) ||
      (row.template_code === 'M_BASE_DRAWER_WOOD_UNDERMOUNT' && Number(row.version) <= 13)) return false;

  return true;
}

export function findReadyModulePreview(
  preset: QuoteModulePreset,
  rows: ReadyModuleLibraryRow[],
): ReadyModulePreview | null {
  const templateCodes = TEMPLATE_CODES_BY_GROUP[preset.group];
  if (!templateCodes?.length) return null;

  const matches = rows
    .filter((row) =>
      row.release_status === 'READY' &&
      templateCodes.includes(row.template_code) &&
      sameMm(row.width_mm, preset.widthMm) &&
      sameMm(row.body_height_mm, preset.heightMm) &&
      sameMm(row.depth_mm, preset.depthMm) &&
      Boolean(row.preview_bucket) &&
      Boolean(row.preview_path) &&
      previewCanBeShown(row),
    )
    .sort((a, b) => Number(b.version) - Number(a.version));

  const row = matches[0];
  if (!row?.preview_bucket || !row.preview_path) return null;

  return {
    moduleCode: row.module_code,
    version: Number(row.version),
    bucket: row.preview_bucket,
    path: row.preview_path,
  };
}
