import type { Locale } from './i18n';

export type AuthMessages={
  headline:string;loginHelp:string;missing:string;invalid:string;passwordError:string;signupError:string;genericError:string;checkEmail:string;email:string;password:string;login:string;createAccount:string;languageNote:string;interfaceLanguage:string;
  firstRun:string;createWorkspace:string;workspaceHelp:string;workspaceError:string;workspaceName:string;workspacePlaceholder:string;country:string;currency:string;timezone:string;createWorkshop:string;
  countries:Record<string,string>;
};

const messages:Record<Locale,AuthMessages>={
  ru:{headline:'Расчёт мебели без гадания',loginHelp:'Войдите или создайте аккаунт, чтобы считать реальные проекты своей мастерской.',missing:'Введите email и пароль.',invalid:'Не удалось войти. Проверьте email и пароль.',passwordError:'Пароль должен содержать минимум 8 символов.',signupError:'Не удалось создать аккаунт. Попробуйте ещё раз.',genericError:'Произошла ошибка.',checkEmail:'Проверьте почту и подтвердите регистрацию. После подтверждения вернитесь в Makster Quote.',email:'Эл. почта',password:'Пароль',login:'Войти',createAccount:'Создать аккаунт',languageNote:'Язык интерфейса можно менять в любой момент. Английский используется как fallback для неподдерживаемых системных языков.',interfaceLanguage:'Язык интерфейса',firstRun:'ПЕРВЫЙ ЗАПУСК',createWorkspace:'Создайте рабочее пространство',workspaceHelp:'Это отдельная защищённая мастерская. Её проекты, закупочные цены и клиенты не видны другим пользователям.',workspaceError:'Не удалось создать рабочее пространство. Проверьте поля и повторите.',workspaceName:'Название мастерской',workspacePlaceholder:'Например, Makster Atelier',country:'Страна',currency:'Валюта',timezone:'Часовой пояс',createWorkshop:'Создать мастерскую',countries:{CZ:'Чехия',DE:'Германия',PL:'Польша',AT:'Австрия',UA:'Украина'}},
  en:{headline:'Furniture costing without guesswork',loginHelp:'Sign in or create an account to calculate real projects for your workshop.',missing:'Enter email and password.',invalid:'Could not sign in. Check your email and password.',passwordError:'Password must contain at least 8 characters.',signupError:'Could not create the account. Try again.',genericError:'Something went wrong.',checkEmail:'Check your email and confirm registration. Then return to Makster Quote.',email:'Email',password:'Password',login:'Sign in',createAccount:'Create account',languageNote:'You can change the interface language at any time. English is the fallback for unsupported system languages.',interfaceLanguage:'Interface language',firstRun:'FIRST RUN',createWorkspace:'Create your workspace',workspaceHelp:'This is a separate protected workshop. Its projects, purchase prices and customers are not visible to other users.',workspaceError:'Could not create the workspace. Check the fields and try again.',workspaceName:'Workshop name',workspacePlaceholder:'For example, Makster Atelier',country:'Country',currency:'Currency',timezone:'Time zone',createWorkshop:'Create workshop',countries:{CZ:'Czech Republic',DE:'Germany',PL:'Poland',AT:'Austria',UA:'Ukraine'}},
  cs:{headline:'Kalkulace nábytku bez hádání',loginHelp:'Přihlaste se nebo si vytvořte účet a kalkulujte skutečné projekty své dílny.',missing:'Zadejte e-mail a heslo.',invalid:'Přihlášení se nepodařilo. Zkontrolujte e-mail a heslo.',passwordError:'Heslo musí mít alespoň 8 znaků.',signupError:'Účet se nepodařilo vytvořit. Zkuste to znovu.',genericError:'Došlo k chybě.',checkEmail:'Zkontrolujte e-mail a potvrďte registraci. Potom se vraťte do Makster Quote.',email:'E-mail',password:'Heslo',login:'Přihlásit se',createAccount:'Vytvořit účet',languageNote:'Jazyk rozhraní můžete kdykoli změnit. Pro nepodporované systémové jazyky se použije angličtina.',interfaceLanguage:'Jazyk rozhraní',firstRun:'PRVNÍ SPUŠTĚNÍ',createWorkspace:'Vytvořte pracovní prostor',workspaceHelp:'Jde o samostatnou chráněnou dílnu. Její projekty, nákupní ceny a zákazníci nejsou viditelní ostatním uživatelům.',workspaceError:'Pracovní prostor se nepodařilo vytvořit. Zkontrolujte pole a zkuste to znovu.',workspaceName:'Název dílny',workspacePlaceholder:'Například Makster Atelier',country:'Země',currency:'Měna',timezone:'Časové pásmo',createWorkshop:'Vytvořit dílnu',countries:{CZ:'Česko',DE:'Německo',PL:'Polsko',AT:'Rakousko',UA:'Ukrajina'}},
  de:{headline:'Möbel kalkulieren ohne Rätselraten',loginHelp:'Anmelden oder Konto erstellen, um echte Projekte Ihrer Werkstatt zu kalkulieren.',missing:'E-Mail und Passwort eingeben.',invalid:'Anmeldung fehlgeschlagen. E-Mail und Passwort prüfen.',passwordError:'Das Passwort muss mindestens 8 Zeichen enthalten.',signupError:'Konto konnte nicht erstellt werden. Bitte erneut versuchen.',genericError:'Ein Fehler ist aufgetreten.',checkEmail:'Prüfen Sie Ihre E-Mail und bestätigen Sie die Registrierung. Danach zu Makster Quote zurückkehren.',email:'E-Mail',password:'Passwort',login:'Anmelden',createAccount:'Konto erstellen',languageNote:'Die Sprache der Oberfläche kann jederzeit geändert werden. Englisch ist der Fallback für nicht unterstützte Systemsprachen.',interfaceLanguage:'Sprache der Oberfläche',firstRun:'ERSTER START',createWorkspace:'Arbeitsbereich erstellen',workspaceHelp:'Dies ist eine separate geschützte Werkstatt. Projekte, Einkaufspreise und Kunden sind für andere Benutzer nicht sichtbar.',workspaceError:'Arbeitsbereich konnte nicht erstellt werden. Felder prüfen und erneut versuchen.',workspaceName:'Werkstattname',workspacePlaceholder:'Zum Beispiel Makster Atelier',country:'Land',currency:'Währung',timezone:'Zeitzone',createWorkshop:'Werkstatt erstellen',countries:{CZ:'Tschechien',DE:'Deutschland',PL:'Polen',AT:'Österreich',UA:'Ukraine'}},
  pl:{headline:'Wycena mebli bez zgadywania',loginHelp:'Zaloguj się albo utwórz konto, aby liczyć rzeczywiste projekty swojego warsztatu.',missing:'Podaj email i hasło.',invalid:'Nie udało się zalogować. Sprawdź email i hasło.',passwordError:'Hasło musi mieć co najmniej 8 znaków.',signupError:'Nie udało się utworzyć konta. Spróbuj ponownie.',genericError:'Wystąpił błąd.',checkEmail:'Sprawdź pocztę i potwierdź rejestrację. Potem wróć do Makster Quote.',email:'E-mail',password:'Hasło',login:'Zaloguj',createAccount:'Utwórz konto',languageNote:'Język interfejsu można zmienić w każdej chwili. Angielski jest fallbackiem dla nieobsługiwanych języków systemowych.',interfaceLanguage:'Język interfejsu',firstRun:'PIERWSZE URUCHOMIENIE',createWorkspace:'Utwórz przestrzeń roboczą',workspaceHelp:'To osobny chroniony warsztat. Jego projekty, ceny zakupu i klienci nie są widoczni dla innych użytkowników.',workspaceError:'Nie udało się utworzyć przestrzeni roboczej. Sprawdź pola i spróbuj ponownie.',workspaceName:'Nazwa warsztatu',workspacePlaceholder:'Na przykład Makster Atelier',country:'Kraj',currency:'Waluta',timezone:'Strefa czasowa',createWorkshop:'Utwórz warsztat',countries:{CZ:'Czechy',DE:'Niemcy',PL:'Polska',AT:'Austria',UA:'Ukraina'}}
};

export function getAuthMessages(locale:Locale){return messages[locale];}
