import type { Locale } from './i18n';

type AnalyticsMessages = {
  title:string; quotes:string; back:string; conversion:string; accepted:string; rejected:string; openPipeline:string; activeNotExpired:string;
  accepted30:string; wonQuotes:string; accepted180:string; quotesInCurrency:string; avgAccepted:string; acceptedPrimary:string; avgDecision:string;
  issuedToDecision:string; issued30:string; newVersions:string; needsFollowUp:string; afterLastStatus:string; overdueNoDecision:string; openQuotes:string;
  noDecisionClients:string; followUpHelp:string; noFollowUp:string; noFollowUpHelp:string; client:string; noMovement:string; amount:string; open:string;
  pipelineAge:string; pipelineMoney:string; pipelineMoneyHelp:string; quotesCount:string; acceptedSection:string; revenueByCurrency:string; revenueHelp:string;
  noAccepted:string; noAcceptedHelp:string; accepted180Short:string; days0_2:string; days3_7:string; days8_14:string; days15plus:string; days:string;
};

const messages: Record<Locale, AnalyticsMessages> = {
  ru:{title:'Аналитика предложений',quotes:'Предложения',back:'← Главная',conversion:'Конверсия',accepted:'принято',rejected:'отклонено',openPipeline:'Открытый pipeline',activeNotExpired:'активных · не просрочены',accepted30:'Принято за 30 дней',wonQuotes:'выигранных предложений',accepted180:'Принято за 180 дней',quotesInCurrency:'предложений',avgAccepted:'Средний принятый заказ',acceptedPrimary:'принятых в основной валюте',avgDecision:'Среднее решение клиента',issuedToDecision:'от выпуска до принятия/отказа',issued30:'Выпущено за 30 дней',newVersions:'новых версий предложений',needsFollowUp:'Нужен follow-up',afterLastStatus:'3+ дня после последнего статуса',overdueNoDecision:'Просрочено без решения',openQuotes:'открытых предложений',noDecisionClients:'Клиенты без решения',followUpHelp:'Отсчёт идёт от последнего коммерческого статуса, а не только от даты выпуска.',noFollowUp:'Follow-up сейчас не нужен',noFollowUpHelp:'Активные предложения либо свежие, либо уже получили решение клиента.',client:'Клиент',noMovement:'Без движения',amount:'Сумма',open:'Открыть →',pipelineAge:'ВОЗРАСТ PIPELINE',pipelineMoney:'Сколько денег ждёт решения',pipelineMoneyHelp:'Только активные и ещё действующие предложения в основной валюте.',quotesCount:'предложений',acceptedSection:'ПРИНЯТО',revenueByCurrency:'Выручка по валютам',revenueHelp:'Суммируем только предложения со статусом «Принято» за последние 180 дней.',noAccepted:'Принятых предложений пока нет',noAcceptedHelp:'После первого принятого предложения здесь появится коммерческая статистика.',accepted180Short:'принятые предложения за 180 дней',days0_2:'0–2 дня',days3_7:'3–7 дней',days8_14:'8–14 дней',days15plus:'15+ дней',days:'дн.'},
  en:{title:'Quote Analytics',quotes:'Quotes',back:'← Dashboard',conversion:'Conversion',accepted:'accepted',rejected:'rejected',openPipeline:'Open pipeline',activeNotExpired:'active · not overdue',accepted30:'Accepted in 30 days',wonQuotes:'won quotes',accepted180:'Accepted in 180 days',quotesInCurrency:'quotes',avgAccepted:'Average accepted order',acceptedPrimary:'accepted in primary currency',avgDecision:'Average customer decision',issuedToDecision:'from issue to accept/reject',issued30:'Issued in 30 days',newVersions:'new quote versions',needsFollowUp:'Needs follow-up',afterLastStatus:'3+ days since last status',overdueNoDecision:'Overdue without decision',openQuotes:'open quotes',noDecisionClients:'Customers without decision',followUpHelp:'Age is counted from the latest commercial status, not only the issue date.',noFollowUp:'No follow-up needed now',noFollowUpHelp:'Active quotes are either fresh or already have a customer decision.',client:'Customer',noMovement:'No movement',amount:'Amount',open:'Open →',pipelineAge:'PIPELINE AGE',pipelineMoney:'Money waiting for a decision',pipelineMoneyHelp:'Only active, non-expired quotes in the primary currency.',quotesCount:'quotes',acceptedSection:'ACCEPTED',revenueByCurrency:'Revenue by currency',revenueHelp:'Only quotes accepted during the last 180 days are included.',noAccepted:'No accepted quotes yet',noAcceptedHelp:'Commercial statistics will appear after the first accepted quote.',accepted180Short:'accepted quotes in 180 days',days0_2:'0–2 days',days3_7:'3–7 days',days8_14:'8–14 days',days15plus:'15+ days',days:'days'},
  cs:{title:'Analytika nabídek',quotes:'Nabídky',back:'← Přehled',conversion:'Konverze',accepted:'přijato',rejected:'odmítnuto',openPipeline:'Otevřený pipeline',activeNotExpired:'aktivních · po platnosti ne',accepted30:'Přijato za 30 dní',wonQuotes:'vyhraných nabídek',accepted180:'Přijato za 180 dní',quotesInCurrency:'nabídek',avgAccepted:'Průměrná přijatá zakázka',acceptedPrimary:'přijatých v hlavní měně',avgDecision:'Průměrné rozhodnutí klienta',issuedToDecision:'od vydání do přijetí/odmítnutí',issued30:'Vydáno za 30 dní',newVersions:'nových verzí nabídek',needsFollowUp:'Vyžaduje follow-up',afterLastStatus:'3+ dny od posledního stavu',overdueNoDecision:'Po termínu bez rozhodnutí',openQuotes:'otevřených nabídek',noDecisionClients:'Klienti bez rozhodnutí',followUpHelp:'Stáří se počítá od posledního obchodního stavu, ne jen od data vydání.',noFollowUp:'Follow-up nyní není potřeba',noFollowUpHelp:'Aktivní nabídky jsou buď čerstvé, nebo už mají rozhodnutí klienta.',client:'Klient',noMovement:'Bez pohybu',amount:'Částka',open:'Otevřít →',pipelineAge:'STÁŘÍ PIPELINE',pipelineMoney:'Kolik peněz čeká na rozhodnutí',pipelineMoneyHelp:'Pouze aktivní a stále platné nabídky v hlavní měně.',quotesCount:'nabídek',acceptedSection:'PŘIJATO',revenueByCurrency:'Tržby podle měny',revenueHelp:'Započítávají se pouze nabídky se stavem „Přijato“ za posledních 180 dní.',noAccepted:'Zatím žádné přijaté nabídky',noAcceptedHelp:'Po první přijaté nabídce se zde zobrazí obchodní statistiky.',accepted180Short:'přijaté nabídky za 180 dní',days0_2:'0–2 dny',days3_7:'3–7 dní',days8_14:'8–14 dní',days15plus:'15+ dní',days:'dní'},
  de:{title:'Angebotsanalyse',quotes:'Angebote',back:'← Übersicht',conversion:'Konversion',accepted:'angenommen',rejected:'abgelehnt',openPipeline:'Offene Pipeline',activeNotExpired:'aktiv · nicht überfällig',accepted30:'Angenommen in 30 Tagen',wonQuotes:'gewonnene Angebote',accepted180:'Angenommen in 180 Tagen',quotesInCurrency:'Angebote',avgAccepted:'Ø angenommener Auftrag',acceptedPrimary:'angenommen in Hauptwährung',avgDecision:'Ø Kundenentscheidung',issuedToDecision:'von Ausgabe bis Annahme/Ablehnung',issued30:'Ausgestellt in 30 Tagen',newVersions:'neue Angebotsversionen',needsFollowUp:'Follow-up nötig',afterLastStatus:'3+ Tage seit letztem Status',overdueNoDecision:'Überfällig ohne Entscheidung',openQuotes:'offene Angebote',noDecisionClients:'Kunden ohne Entscheidung',followUpHelp:'Das Alter zählt ab dem letzten kommerziellen Status, nicht nur ab Ausgabedatum.',noFollowUp:'Aktuell kein Follow-up nötig',noFollowUpHelp:'Aktive Angebote sind entweder frisch oder bereits entschieden.',client:'Kunde',noMovement:'Ohne Bewegung',amount:'Betrag',open:'Öffnen →',pipelineAge:'PIPELINE-ALTER',pipelineMoney:'Geld wartet auf Entscheidung',pipelineMoneyHelp:'Nur aktive, noch gültige Angebote in der Hauptwährung.',quotesCount:'Angebote',acceptedSection:'ANGENOMMEN',revenueByCurrency:'Umsatz nach Währung',revenueHelp:'Es zählen nur in den letzten 180 Tagen angenommene Angebote.',noAccepted:'Noch keine angenommenen Angebote',noAcceptedHelp:'Nach dem ersten angenommenen Angebot erscheinen hier Vertriebskennzahlen.',accepted180Short:'angenommene Angebote in 180 Tagen',days0_2:'0–2 Tage',days3_7:'3–7 Tage',days8_14:'8–14 Tage',days15plus:'15+ Tage',days:'Tage'},
  pl:{title:'Analityka ofert',quotes:'Oferty',back:'← Pulpit',conversion:'Konwersja',accepted:'zaakceptowano',rejected:'odrzucono',openPipeline:'Otwarty pipeline',activeNotExpired:'aktywnych · nieprzeterminowane',accepted30:'Zaakceptowano w 30 dni',wonQuotes:'wygranych ofert',accepted180:'Zaakceptowano w 180 dni',quotesInCurrency:'ofert',avgAccepted:'Średnie zaakceptowane zlecenie',acceptedPrimary:'zaakceptowanych w głównej walucie',avgDecision:'Średni czas decyzji klienta',issuedToDecision:'od wystawienia do akceptacji/odrzucenia',issued30:'Wystawiono w 30 dni',newVersions:'nowych wersji ofert',needsFollowUp:'Wymaga follow-up',afterLastStatus:'3+ dni od ostatniego statusu',overdueNoDecision:'Po terminie bez decyzji',openQuotes:'otwartych ofert',noDecisionClients:'Klienci bez decyzji',followUpHelp:'Wiek liczony jest od ostatniego statusu handlowego, nie tylko od daty wystawienia.',noFollowUp:'Follow-up nie jest teraz potrzebny',noFollowUpHelp:'Aktywne oferty są świeże albo klient już podjął decyzję.',client:'Klient',noMovement:'Bez ruchu',amount:'Kwota',open:'Otwórz →',pipelineAge:'WIEK PIPELINE',pipelineMoney:'Ile pieniędzy czeka na decyzję',pipelineMoneyHelp:'Tylko aktywne i ważne oferty w głównej walucie.',quotesCount:'ofert',acceptedSection:'ZAAKCEPTOWANE',revenueByCurrency:'Przychód według walut',revenueHelp:'Sumowane są tylko oferty zaakceptowane w ostatnich 180 dniach.',noAccepted:'Brak zaakceptowanych ofert',noAcceptedHelp:'Po pierwszej zaakceptowanej ofercie pojawią się tutaj statystyki handlowe.',accepted180Short:'zaakceptowane oferty w 180 dni',days0_2:'0–2 dni',days3_7:'3–7 dni',days8_14:'8–14 dni',days15plus:'15+ dni',days:'dni'},
};

export function getAnalyticsMessages(locale: Locale) {
  return messages[locale];
}
