import type { Locale } from './i18n';

export type Phase1Messages = {
  upload:string; uploadHint:string; uploading:string; uploadFailed:string; invalidPhoto:string; remove:string; noPhotos:string; photos:string;
  dimensionSource:string; sourceHelp:string; measurementReference:string; referencePlaceholder:string;
  refWallA:string; refWallB:string; refWallC:string; refWallD:string; refNiche:string; refWindow:string; refDoor:string; refAppliance:string;
  nextAction:string; nextMeasurements:string; nextModules:string; nextMaterials:string; nextCost:string; nextPrice:string; nextProposal:string; ready:string; modulesIncomplete:string;
  blocked:string; available:string; blockedByMeasurements:string; blockedByModules:string; blockedByMaterials:string; blockedByCost:string; blockedByPrice:string;
  fixHere:string; remaining:string;
};

const ru:Phase1Messages={upload:'Добавить фотографии',uploadHint:'JPG, PNG, WEBP, HEIC · до 10 МБ на фото',uploading:'Загрузка…',uploadFailed:'Не удалось загрузить фотографию.',invalidPhoto:'Поддерживаются фотографии до 10 МБ.',remove:'Удалить',noPhotos:'Фотографий пока нет.',photos:'Фото',dimensionSource:'Источник размеров',sourceHelp:'Показывает, откуда взяты размеры модуля.',measurementReference:'Привязка к замеру',referencePlaceholder:'Например: Стена A / ниша 1',refWallA:'Стена A',refWallB:'Стена B',refWallC:'Стена C',refWallD:'Стена D',refNiche:'Ниша / выступ',refWindow:'Окно / подоконник',refDoor:'Дверь / проём',refAppliance:'Техника',nextAction:'Следующий шаг',nextMeasurements:'Завершите замеры объекта.',nextModules:'Добавьте первый мебельный модуль.',nextMaterials:'Заполните материалы и фурнитуру для всех модулей.',nextCost:'Завершите расчёт себестоимости всех модулей.',nextPrice:'Сохраните коммерческую цену и параметры предложения.',nextProposal:'Сформируйте и выпустите предложение клиенту.',ready:'Проект готов по текущему рабочему маршруту.',modulesIncomplete:'Модулей с неполным расчётом',blocked:'Заблокировано',available:'Доступно',blockedByMeasurements:'Сначала завершите замеры',blockedByModules:'Сначала добавьте хотя бы один модуль',blockedByMaterials:'Сначала заполните материалы и фурнитуру',blockedByCost:'Сначала завершите себестоимость',blockedByPrice:'Сначала сохраните коммерческую цену',fixHere:'Исправить',remaining:'Осталось'};
const en:Phase1Messages={upload:'Add photos',uploadHint:'JPG, PNG, WEBP, HEIC · up to 10 MB per photo',uploading:'Uploading…',uploadFailed:'Photo upload failed.',invalidPhoto:'Supported photos up to 10 MB only.',remove:'Remove',noPhotos:'No photos yet.',photos:'Photos',dimensionSource:'Dimension source',sourceHelp:'Shows where the module dimensions came from.',measurementReference:'Measurement reference',referencePlaceholder:'For example: Wall A / niche 1',refWallA:'Wall A',refWallB:'Wall B',refWallC:'Wall C',refWallD:'Wall D',refNiche:'Niche / projection',refWindow:'Window / sill',refDoor:'Door / opening',refAppliance:'Appliance',nextAction:'Next action',nextMeasurements:'Complete the site measurements.',nextModules:'Add the first furniture module.',nextMaterials:'Complete materials and hardware for every module.',nextCost:'Finish true-cost calculation for every module.',nextPrice:'Save commercial price and quote parameters.',nextProposal:'Create and issue the customer proposal.',ready:'The project is ready on the current workflow.',modulesIncomplete:'Modules with incomplete costing',blocked:'Blocked',available:'Available',blockedByMeasurements:'Complete measurements first',blockedByModules:'Add at least one module first',blockedByMaterials:'Complete materials and hardware first',blockedByCost:'Complete true cost first',blockedByPrice:'Save the commercial price first',fixHere:'Fix',remaining:'Remaining'};
const cs:Phase1Messages={...en,upload:'Přidat fotografie',uploadHint:'JPG, PNG, WEBP, HEIC · max. 10 MB na fotografii',uploading:'Nahrávání…',uploadFailed:'Fotografii se nepodařilo nahrát.',invalidPhoto:'Podporovány jsou fotografie do 10 MB.',remove:'Odstranit',noPhotos:'Zatím žádné fotografie.',photos:'Fotografie',dimensionSource:'Zdroj rozměrů',sourceHelp:'Ukazuje, odkud pochází rozměry modulu.',measurementReference:'Vazba na zaměření',referencePlaceholder:'Například: Stěna A / nika 1',refWallA:'Stěna A',refWallB:'Stěna B',refWallC:'Stěna C',refWallD:'Stěna D',nextAction:'Další krok',nextMeasurements:'Dokončete zaměření objektu.',nextModules:'Přidejte první nábytkový modul.',nextMaterials:'Doplňte materiály a kování u všech modulů.',nextCost:'Dokončete kalkulaci nákladů všech modulů.',nextPrice:'Uložte obchodní cenu a parametry nabídky.',nextProposal:'Vytvořte a vydejte nabídku zákazníkovi.',ready:'Projekt je připraven.',modulesIncomplete:'Moduly s neúplnou kalkulací',blocked:'Blokováno',available:'Dostupné',blockedByMeasurements:'Nejprve dokončete zaměření',blockedByModules:'Nejprve přidejte alespoň jeden modul',blockedByMaterials:'Nejprve doplňte materiály a kování',blockedByCost:'Nejprve dokončete náklady',blockedByPrice:'Nejprve uložte obchodní cenu',fixHere:'Opravit',remaining:'Zbývá'};
const de:Phase1Messages={...en,upload:'Fotos hinzufügen',uploadHint:'JPG, PNG, WEBP, HEIC · bis 10 MB pro Foto',uploading:'Wird hochgeladen…',uploadFailed:'Foto konnte nicht hochgeladen werden.',invalidPhoto:'Nur Fotos bis 10 MB sind erlaubt.',remove:'Entfernen',noPhotos:'Noch keine Fotos.',photos:'Fotos',dimensionSource:'Maßquelle',sourceHelp:'Zeigt, woher die Modulmaße stammen.',measurementReference:'Aufmaß-Referenz',referencePlaceholder:'Zum Beispiel: Wand A / Nische 1',refWallA:'Wand A',refWallB:'Wand B',refWallC:'Wand C',refWallD:'Wand D',nextAction:'Nächster Schritt',nextMeasurements:'Schließen Sie das Aufmaß ab.',nextModules:'Fügen Sie das erste Möbelmodul hinzu.',nextMaterials:'Vervollständigen Sie Materialien und Beschläge.',nextCost:'Schließen Sie die Kostenkalkulation aller Module ab.',nextPrice:'Speichern Sie Preis und Angebotsparameter.',nextProposal:'Erstellen und veröffentlichen Sie das Angebot.',ready:'Das Projekt ist bereit.',modulesIncomplete:'Module mit unvollständiger Kalkulation',blocked:'Gesperrt',available:'Verfügbar',blockedByMeasurements:'Zuerst das Aufmaß abschließen',blockedByModules:'Zuerst mindestens ein Modul hinzufügen',blockedByMaterials:'Zuerst Materialien und Beschläge vervollständigen',blockedByCost:'Zuerst die Kosten abschließen',blockedByPrice:'Zuerst den Verkaufspreis speichern',fixHere:'Beheben',remaining:'Verbleibend'};
const pl:Phase1Messages={...en,upload:'Dodaj zdjęcia',uploadHint:'JPG, PNG, WEBP, HEIC · do 10 MB na zdjęcie',uploading:'Przesyłanie…',uploadFailed:'Nie udało się przesłać zdjęcia.',invalidPhoto:'Obsługiwane są zdjęcia do 10 MB.',remove:'Usuń',noPhotos:'Brak zdjęć.',photos:'Zdjęcia',dimensionSource:'Źródło wymiarów',sourceHelp:'Pokazuje źródło wymiarów modułu.',measurementReference:'Powiązanie z pomiarem',referencePlaceholder:'Na przykład: Ściana A / wnęka 1',refWallA:'Ściana A',refWallB:'Ściana B',refWallC:'Ściana C',refWallD:'Ściana D',nextAction:'Następny krok',nextMeasurements:'Zakończ pomiary obiektu.',nextModules:'Dodaj pierwszy moduł meblowy.',nextMaterials:'Uzupełnij materiały i okucia.',nextCost:'Zakończ kalkulację kosztu wszystkich modułów.',nextPrice:'Zapisz cenę i parametry oferty.',nextProposal:'Utwórz i opublikuj ofertę.',ready:'Projekt jest gotowy.',modulesIncomplete:'Moduły z niepełną kalkulacją',blocked:'Zablokowane',available:'Dostępne',blockedByMeasurements:'Najpierw zakończ pomiary',blockedByModules:'Najpierw dodaj co najmniej jeden moduł',blockedByMaterials:'Najpierw uzupełnij materiały i okucia',blockedByCost:'Najpierw zakończ kalkulację kosztu',blockedByPrice:'Najpierw zapisz cenę sprzedaży',fixHere:'Napraw',remaining:'Pozostało'};

const messages:Record<Locale,Phase1Messages>={ru,en,cs,de,pl};
export function getPhase1Messages(locale:Locale){return messages[locale]??en;}
