import type { Locale } from './i18n';

type Text={title:string;help:string;currency:string;board:string;front:string;back:string;edge:string;hinge:string;drawer:string;labour:string;none:string;operations:string;save:string;saved:string;invalid:string};
const m:Record<Locale,Text>={
ru:{title:'Материалы и фурнитура по умолчанию',help:'Quick Add и библиотека автоматически используют эти позиции. Неподходящая или недоступная позиция не подставляется.',currency:'Валюта настроек',board:'Плита корпуса',front:'Фасад',back:'Задняя стенка',edge:'Кромка',hinge:'Петля',drawer:'Система ящиков',labour:'Ставка прямого труда',none:'— не назначено —',operations:'Операции выбираются автоматически по operationKey из активного Price Book той же валюты.',save:'Сохранить материалы по умолчанию',saved:'Материалы по умолчанию сохранены.',invalid:'Выбранная позиция не подходит по категории, единице или валюте.'},
en:{title:'Default materials & hardware',help:'Quick Add and Module Library apply these items automatically. Invalid or unavailable items are not applied.',currency:'Defaults currency',board:'Carcass board',front:'Front',back:'Back panel',edge:'Edge band',hinge:'Hinge',drawer:'Drawer system',labour:'Direct labour rate',none:'— not assigned —',operations:'Operations are selected automatically by operationKey from the active Price Book in the same currency.',save:'Save default materials',saved:'Default materials saved.',invalid:'A selected item does not match the required category, unit or currency.'},
cs:{title:'Výchozí materiály a kování',help:'Rychlé přidání a knihovna modulů použijí tyto položky automaticky. Neplatná nebo nedostupná položka se nepoužije.',currency:'Měna výchozích položek',board:'Deska korpusu',front:'Čelo',back:'Zadní stěna',edge:'Hrana',hinge:'Závěs',drawer:'Zásuvkový systém',labour:'Sazba přímé práce',none:'— nepřiřazeno —',operations:'Operace se vybírají automaticky podle operationKey z aktivního ceníku ve stejné měně.',save:'Uložit výchozí materiály',saved:'Výchozí materiály byly uloženy.',invalid:'Vybraná položka neodpovídá požadované kategorii, jednotce nebo měně.'},
de:{title:'Standardmaterialien & Beschläge',help:'Quick Add und Modulbibliothek verwenden diese Positionen automatisch. Ungültige oder nicht verfügbare Positionen werden nicht verwendet.',currency:'Währung der Standards',board:'Korpusplatte',front:'Front',back:'Rückwand',edge:'Kante',hinge:'Scharnier',drawer:'Schubladensystem',labour:'Direkter Arbeitsstundensatz',none:'— nicht zugewiesen —',operations:'Operationen werden automatisch per operationKey aus der aktiven Preisliste derselben Währung gewählt.',save:'Standardmaterialien speichern',saved:'Standardmaterialien gespeichert.',invalid:'Eine Position passt nicht zu Kategorie, Einheit oder Währung.'},
pl:{title:'Domyślne materiały i okucia',help:'Quick Add i biblioteka modułów stosują te pozycje automatycznie. Nieprawidłowa lub niedostępna pozycja nie jest używana.',currency:'Waluta ustawień domyślnych',board:'Płyta korpusu',front:'Front',back:'Plecy',edge:'Obrzeże',hinge:'Zawias',drawer:'System szuflad',labour:'Stawka pracy bezpośredniej',none:'— nie przypisano —',operations:'Operacje są dobierane automatycznie po operationKey z aktywnego cennika w tej samej walucie.',save:'Zapisz domyślne materiały',saved:'Domyślne materiały zapisane.',invalid:'Wybrana pozycja nie pasuje do kategorii, jednostki lub waluty.'}
};
export function getPricingDefaultsMessages(locale:Locale){return m[locale];}
