import type { QuotePlan } from './billing';
import type { Locale } from './i18n';

type BillingMessages = {
  title:string; back:string; checkoutSuccess:string; checkoutWebhook:string; existingSubscription:string; billingError:string;
  currentPlan:string; forWorkshop:string; status:string; until:string; noEndDate:string; billingBackend:string; awaitsSetup:string;
  currentSubscription:string; managePayment:string; currentPaidUntil:string; plans:string; changePlan:string; choosePlan:string;
  pricesFromProvider:string; subscriptionActive:string; portalHelp:string; openPortal:string; choose:string; planPermission:string;
  monthly:string; free:string; configured:string; pending:string; pendingHelp:string; vatNote:string;
};

const messages:Record<Locale,BillingMessages>={
  ru:{title:'Тариф и подписка',back:'← Главная',checkoutSuccess:'Оплата завершена.',checkoutWebhook:'Подписка обновится после подтверждённого webhook Stripe.',existingSubscription:'У мастерской уже есть активная подписка. Для смены тарифа используйте управление подпиской, чтобы не создать дубликат.',billingError:'Не удалось выполнить действие с подпиской.',currentPlan:'Текущий тариф',forWorkshop:'для этой мастерской',status:'Статус',until:'до',noEndDate:'без даты окончания',billingBackend:'Billing backend',awaitsSetup:'ожидает настройки',currentSubscription:'ТЕКУЩАЯ ПОДПИСКА',managePayment:'Управлять оплатой',currentPaidUntil:'Текущий оплаченный период действует до',plans:'ТАРИФЫ',changePlan:'Смена тарифа',choosePlan:'Выбрать тариф',pricesFromProvider:'Тарифная сетка Makster Quote едина. Оплата и налоги обрабатываются Stripe.',subscriptionActive:'Подписка уже активна',portalHelp:'Платёжные данные, отмена и доступные изменения подписки выполняются через Stripe Customer Portal.',openPortal:'Открыть управление подпиской',choose:'Выбрать',planPermission:'Изменить тариф может владелец или администратор',monthly:'в месяц',free:'бесплатно',configured:'Stripe готов',pending:'Stripe price ещё не подключён',pendingHelp:'Тариф уже зафиксирован в Makster Quote, но checkout станет доступен после создания соответствующей цены в Stripe.',vatNote:'Налог/VAT рассчитывается Stripe по данным покупателя и правилам оплаты.'},
  en:{title:'Plan & subscription',back:'← Dashboard',checkoutSuccess:'Payment completed.',checkoutWebhook:'The subscription updates after a verified Stripe webhook.',existingSubscription:'This workshop already has an active subscription. Use subscription management to change plan and avoid duplicates.',billingError:'Could not complete the subscription action.',currentPlan:'Current plan',forWorkshop:'for this workshop',status:'Status',until:'until',noEndDate:'no end date',billingBackend:'Billing backend',awaitsSetup:'awaits setup',currentSubscription:'CURRENT SUBSCRIPTION',managePayment:'Manage billing',currentPaidUntil:'Current paid period runs until',plans:'PLANS',changePlan:'Change plan',choosePlan:'Choose plan',pricesFromProvider:'Makster Quote uses one canonical plan grid. Payments and taxes are handled by Stripe.',subscriptionActive:'Subscription already active',portalHelp:'Payment details, cancellation and available subscription changes are handled in Stripe Customer Portal.',openPortal:'Open subscription management',choose:'Choose',planPermission:'Only the owner or administrator can change plan',monthly:'per month',free:'free',configured:'Stripe ready',pending:'Stripe price not connected yet',pendingHelp:'The Makster Quote plan is already fixed, but checkout becomes available after its Stripe price is created.',vatNote:'Tax/VAT is calculated by Stripe from buyer details and payment rules.'},
  cs:{title:'Tarif a předplatné',back:'← Přehled',checkoutSuccess:'Platba dokončena.',checkoutWebhook:'Předplatné se aktualizuje po ověřeném webhooku Stripe.',existingSubscription:'Dílna už má aktivní předplatné. Pro změnu tarifu použijte správu předplatného, aby nevznikla duplicita.',billingError:'Akci s předplatným se nepodařilo dokončit.',currentPlan:'Aktuální tarif',forWorkshop:'pro tuto dílnu',status:'Stav',until:'do',noEndDate:'bez data ukončení',billingBackend:'Billing backend',awaitsSetup:'čeká na nastavení',currentSubscription:'AKTUÁLNÍ PŘEDPLATNÉ',managePayment:'Spravovat platbu',currentPaidUntil:'Aktuální placené období platí do',plans:'TARIFY',changePlan:'Změnit tarif',choosePlan:'Vybrat tarif',pricesFromProvider:'Makster Quote používá jednu jednotnou tarifní strukturu. Platby a daně zpracovává Stripe.',subscriptionActive:'Předplatné je již aktivní',portalHelp:'Platební údaje, zrušení a dostupné změny předplatného se řeší přes Stripe Customer Portal.',openPortal:'Otevřít správu předplatného',choose:'Vybrat',planPermission:'Tarif může měnit pouze vlastník nebo administrátor',monthly:'měsíčně',free:'zdarma',configured:'Stripe připraven',pending:'Stripe cena zatím není připojena',pendingHelp:'Tarif v Makster Quote je už pevně daný, checkout se zpřístupní po vytvoření ceny ve Stripe.',vatNote:'Daň/VAT vypočítá Stripe podle údajů kupujícího a pravidel platby.'},
  de:{title:'Tarif & Abonnement',back:'← Übersicht',checkoutSuccess:'Zahlung abgeschlossen.',checkoutWebhook:'Das Abonnement wird nach einem verifizierten Stripe-Webhook aktualisiert.',existingSubscription:'Die Werkstatt hat bereits ein aktives Abonnement. Nutzen Sie die Abonnementverwaltung für Tarifwechsel, um Duplikate zu vermeiden.',billingError:'Abonnementaktion konnte nicht ausgeführt werden.',currentPlan:'Aktueller Tarif',forWorkshop:'für diese Werkstatt',status:'Status',until:'bis',noEndDate:'ohne Enddatum',billingBackend:'Billing backend',awaitsSetup:'wartet auf Einrichtung',currentSubscription:'AKTUELLES ABONNEMENT',managePayment:'Zahlung verwalten',currentPaidUntil:'Der aktuelle bezahlte Zeitraum läuft bis',plans:'TARIFE',changePlan:'Tarif wechseln',choosePlan:'Tarif wählen',pricesFromProvider:'Makster Quote verwendet eine einheitliche Tarifstruktur. Zahlungen und Steuern werden von Stripe verarbeitet.',subscriptionActive:'Abonnement ist bereits aktiv',portalHelp:'Zahlungsdaten, Kündigung und verfügbare Änderungen werden im Stripe Customer Portal verwaltet.',openPortal:'Abonnement verwalten',choose:'Wählen',planPermission:'Nur Eigentümer oder Administrator können den Tarif ändern',monthly:'pro Monat',free:'kostenlos',configured:'Stripe bereit',pending:'Stripe-Preis noch nicht verbunden',pendingHelp:'Der Makster-Quote-Tarif ist bereits festgelegt; Checkout wird nach Anlegen des Stripe-Preises verfügbar.',vatNote:'Steuer/USt. wird von Stripe anhand der Käuferdaten und Zahlungsregeln berechnet.'},
  pl:{title:'Plan i subskrypcja',back:'← Pulpit',checkoutSuccess:'Płatność zakończona.',checkoutWebhook:'Subskrypcja zaktualizuje się po zweryfikowanym webhooku Stripe.',existingSubscription:'Warsztat ma już aktywną subskrypcję. Do zmiany planu użyj zarządzania subskrypcją, aby nie tworzyć duplikatu.',billingError:'Nie udało się wykonać operacji na subskrypcji.',currentPlan:'Aktualny plan',forWorkshop:'dla tego warsztatu',status:'Status',until:'do',noEndDate:'bez daty końcowej',billingBackend:'Billing backend',awaitsSetup:'czeka na konfigurację',currentSubscription:'AKTUALNA SUBSKRYPCJA',managePayment:'Zarządzaj płatnością',currentPaidUntil:'Bieżący opłacony okres trwa do',plans:'PLANY',changePlan:'Zmiana planu',choosePlan:'Wybierz plan',pricesFromProvider:'Makster Quote używa jednego spójnego cennika planów. Płatności i podatki obsługuje Stripe.',subscriptionActive:'Subskrypcja jest już aktywna',portalHelp:'Dane płatnicze, anulowanie i dostępne zmiany subskrypcji są obsługiwane w Stripe Customer Portal.',openPortal:'Otwórz zarządzanie subskrypcją',choose:'Wybierz',planPermission:'Plan może zmieniać tylko właściciel lub administrator',monthly:'miesięcznie',free:'bezpłatnie',configured:'Stripe gotowy',pending:'Cena Stripe nie jest jeszcze podłączona',pendingHelp:'Plan Makster Quote jest już ustalony, ale checkout będzie dostępny po utworzeniu ceny w Stripe.',vatNote:'Podatek/VAT jest obliczany przez Stripe na podstawie danych kupującego i reguł płatności.'},
};

const descriptions:Record<Locale,Record<QuotePlan,string>>={
  ru:{free:'Проверка продукта на реальном проекте без обязательной платной подписки.',starter:'Для одного мебельщика: проекты, клиенты, Price Book, полная библиотека, себестоимость, PDF и отправка предложения.',workshop:'Для мастерской: до 5 пользователей, общие цены, история изменений, расширенные шаблоны и командная работа.',atelier:'Для растущей команды: до 15 пользователей, роли, несколько рабочих пространств, Makster Pro integration и приоритетная поддержка.'},
  en:{free:'Try Makster Quote on a real project without a required paid subscription.',starter:'For one furniture maker: projects, clients, Price Book, full library, true cost, PDF and quote delivery.',workshop:'For a workshop: up to 5 users, shared prices, change history, advanced templates and collaboration.',atelier:'For a growing team: up to 15 users, roles, multiple workspaces, Makster Pro integration and priority support.'},
  cs:{free:'Vyzkoušejte Makster Quote na reálném projektu bez povinného placeného předplatného.',starter:'Pro jednoho truhláře: projekty, klienti, ceník, celá knihovna, skutečné náklady, PDF a odeslání nabídky.',workshop:'Pro dílnu: až 5 uživatelů, sdílené ceny, historie změn, pokročilé šablony a spolupráce.',atelier:'Pro rostoucí tým: až 15 uživatelů, role, více pracovních prostorů, integrace Makster Pro a prioritní podpora.'},
  de:{free:'Makster Quote mit einem echten Projekt testen, ohne verpflichtendes Bezahlabo.',starter:'Für einen Möbelbauer: Projekte, Kunden, Preisliste, volle Bibliothek, Vollkosten, PDF und Angebotsversand.',workshop:'Für eine Werkstatt: bis zu 5 Nutzer, gemeinsame Preise, Änderungshistorie, erweiterte Vorlagen und Zusammenarbeit.',atelier:'Für wachsende Teams: bis zu 15 Nutzer, Rollen, mehrere Workspaces, Makster-Pro-Integration und Prioritätssupport.'},
  pl:{free:'Wypróbuj Makster Quote na realnym projekcie bez obowiązkowej płatnej subskrypcji.',starter:'Dla jednego stolarza: projekty, klienci, cennik, pełna biblioteka, pełny koszt, PDF i wysyłka oferty.',workshop:'Dla warsztatu: do 5 użytkowników, wspólne ceny, historia zmian, rozszerzone szablony i współpraca.',atelier:'Dla rozwijającego się zespołu: do 15 użytkowników, role, wiele przestrzeni roboczych, integracja Makster Pro i priorytetowe wsparcie.'},
};

const statuses:Record<Locale,Record<string,string>>={
  ru:{inactive:'Неактивна',trialing:'Пробный период',active:'Активна',past_due:'Нужна оплата',paused:'Приостановлена',cancelled:'Отменена до конца периода',expired:'Истекла'},
  en:{inactive:'Inactive',trialing:'Trial',active:'Active',past_due:'Payment due',paused:'Paused',cancelled:'Cancelled at period end',expired:'Expired'},
  cs:{inactive:'Neaktivní',trialing:'Zkušební období',active:'Aktivní',past_due:'Vyžaduje platbu',paused:'Pozastaveno',cancelled:'Zrušeno ke konci období',expired:'Vypršelo'},
  de:{inactive:'Inaktiv',trialing:'Testzeitraum',active:'Aktiv',past_due:'Zahlung fällig',paused:'Pausiert',cancelled:'Zum Periodenende gekündigt',expired:'Abgelaufen'},
  pl:{inactive:'Nieaktywna',trialing:'Okres próbny',active:'Aktywna',past_due:'Wymaga płatności',paused:'Wstrzymana',cancelled:'Anulowana na koniec okresu',expired:'Wygasła'},
};

export function getBillingMessages(locale:Locale){return messages[locale];}
export function billingPlanDescription(locale:Locale,plan:QuotePlan){return descriptions[locale][plan];}
export function billingStatusLabel(locale:Locale,status:string){return statuses[locale][status]??status;}
