import type { Locale } from './i18n';
import type { QuoteModuleFamily, QuoteModulePreset } from './module-presets';

export type LibraryMessages={
  title:string;openProject:string;back:string;addError:string;readyPresets:string;presetSummary:string;groups:string;groupsSummary:string;activeProject:string;notSelected:string;createFirst:string;targetProject:string;whereToAdd:string;targetHelp:string;project:string;noActiveProjects:string;selectProject:string;newProject:string;createProjectFirst:string;standardPresets:string;size:string;construction:string;backPanel:string;none:string;groove:string;overlay:string;quantity:string;addTo:string;quickKitchen:string;quickKitchenHelp:string;quoteBoundary:string;quoteBoundaryHelp:string;mm:string;door:string;doors:string;drawers:string;shelves:string;visibleFront:string;frontOnly:string;ovenNiche:string;opening:string;frontsHigh:string;withoutFront:string;
  family:string;allFamilies:string;search:string;searchPlaceholder:string;noResults:string;
};

const messages:Record<Locale,LibraryMessages>={
  ru:{title:'Библиотека модулей',openProject:'Открыть проект',back:'← Главная',addError:'Не удалось добавить модуль',readyPresets:'Готовых пресетов',presetSummary:'кухня, гардероб, ванная и хозяйственные зоны',groups:'Групп',groupsSummary:'структурированные мебельные категории',activeProject:'Активный проект',notSelected:'не выбран',createFirst:'создайте первый проект',targetProject:'ЦЕЛЕВОЙ ПРОЕКТ',whereToAdd:'Куда добавить модули',targetHelp:'Пресет создаёт коммерческую геометрию и конструкцию. Материал, фасад, кромку и фурнитуру выбираем уже в проекте.',project:'Проект',noActiveProjects:'Нет активных проектов',selectProject:'Выбрать проект',newProject:'+ Новый проект',createProjectFirst:'Сначала создайте проект.',standardPresets:'STANDARD PRESETS',size:'Размер',construction:'Конструкция',backPanel:'Задняя стенка',none:'нет',groove:'в паз',overlay:'накладная',quantity:'Количество',addTo:'Добавить в',quickKitchen:'Коммерческая библиотека мебели.',quickKitchenHelp:'Теперь библиотека покрывает кухню, гардероб, ванную и хозяйственные зоны. Точные монтажные зазоры и производство остаются в Makster Pro.',quoteBoundary:'Граница Quote.',quoteBoundaryHelp:'Здесь используется коммерческая геометрия для расчёта материалов и цены. Точная конструкция, присадка, CNC и монтажные карты остаются в Makster Pro.',mm:'мм',door:'дверь',doors:'двери',drawers:'ящика',shelves:'полки',visibleFront:'видимый фасад',frontOnly:'только мебельный фасад',ovenNiche:'ниша под духовку',opening:'проём',frontsHigh:'фасада по высоте',withoutFront:'без фасада',family:'Категория',allFamilies:'Все категории',search:'Поиск',searchPlaceholder:'Например: пенал, гардероб, раковина…',noResults:'По этому фильтру модулей не найдено.'},
  en:{title:'Module Library',openProject:'Open project',back:'← Dashboard',addError:'Could not add module',readyPresets:'Ready presets',presetSummary:'kitchen, wardrobe, bathroom and utility',groups:'Groups',groupsSummary:'structured furniture categories',activeProject:'Active project',notSelected:'not selected',createFirst:'create the first project',targetProject:'TARGET PROJECT',whereToAdd:'Where to add modules',targetHelp:'A preset creates commercial geometry and construction. Materials, fronts, edge band and hardware are selected inside the project.',project:'Project',noActiveProjects:'No active projects',selectProject:'Select project',newProject:'+ New project',createProjectFirst:'Create a project first.',standardPresets:'STANDARD PRESETS',size:'Size',construction:'Construction',backPanel:'Back panel',none:'none',groove:'in groove',overlay:'overlay',quantity:'Quantity',addTo:'Add to',quickKitchen:'Commercial furniture library.',quickKitchenHelp:'The library now covers kitchen, wardrobe, bathroom and utility zones. Exact installation clearances and production remain in Makster Pro.',quoteBoundary:'Quote boundary.',quoteBoundaryHelp:'Commercial geometry is used here for material and price estimation. Exact construction, drilling, CNC and installation maps remain in Makster Pro.',mm:'mm',door:'door',doors:'doors',drawers:'drawers',shelves:'shelves',visibleFront:'visible front',frontOnly:'furniture front only',ovenNiche:'oven niche',opening:'opening',frontsHigh:'fronts vertically',withoutFront:'without front',family:'Category',allFamilies:'All categories',search:'Search',searchPlaceholder:'For example: pantry, wardrobe, vanity…',noResults:'No modules match this filter.'},
  cs:{title:'Knihovna modulů',openProject:'Otevřít projekt',back:'← Přehled',addError:'Modul se nepodařilo přidat',readyPresets:'Hotové presety',presetSummary:'kuchyně, šatny, koupelna a technické zóny',groups:'Skupiny',groupsSummary:'strukturované kategorie nábytku',activeProject:'Aktivní projekt',notSelected:'nevybrán',createFirst:'vytvořte první projekt',targetProject:'CÍLOVÝ PROJEKT',whereToAdd:'Kam přidat moduly',targetHelp:'Preset vytváří obchodní geometrii a konstrukci. Materiál, čelo, hranu a kování vyberete v projektu.',project:'Projekt',noActiveProjects:'Žádné aktivní projekty',selectProject:'Vybrat projekt',newProject:'+ Nový projekt',createProjectFirst:'Nejprve vytvořte projekt.',standardPresets:'STANDARDNÍ PRESETY',size:'Rozměr',construction:'Konstrukce',backPanel:'Zadní stěna',none:'bez',groove:'do drážky',overlay:'překrytá',quantity:'Množství',addTo:'Přidat do',quickKitchen:'Obchodní knihovna nábytku.',quickKitchenHelp:'Knihovna nyní pokrývá kuchyně, šatny, koupelny a technické zóny. Přesné montážní vůle a výroba zůstávají v Makster Pro.',quoteBoundary:'Hranice Quote.',quoteBoundaryHelp:'Zde se používá obchodní geometrie pro odhad materiálu a ceny. Přesná konstrukce, vrtání, CNC a montážní mapy zůstávají v Makster Pro.',mm:'mm',door:'dvířka',doors:'dvířka',drawers:'zásuvky',shelves:'police',visibleFront:'viditelné čelo',frontOnly:'pouze nábytkové čelo',ovenNiche:'otvor pro troubu',opening:'otvor',frontsHigh:'čela na výšku',withoutFront:'bez čela',family:'Kategorie',allFamilies:'Všechny kategorie',search:'Hledat',searchPlaceholder:'Například: spíž, šatna, umyvadlo…',noResults:'Tomuto filtru neodpovídají žádné moduly.'},
  de:{title:'Modulbibliothek',openProject:'Projekt öffnen',back:'← Übersicht',addError:'Modul konnte nicht hinzugefügt werden',readyPresets:'Fertige Presets',presetSummary:'Küche, Garderobe, Bad und Hauswirtschaft',groups:'Gruppen',groupsSummary:'strukturierte Möbelkategorien',activeProject:'Aktives Projekt',notSelected:'nicht gewählt',createFirst:'erstes Projekt erstellen',targetProject:'ZIELPROJEKT',whereToAdd:'Module hinzufügen zu',targetHelp:'Ein Preset erzeugt kommerzielle Geometrie und Konstruktion. Material, Front, Kante und Beschläge werden im Projekt gewählt.',project:'Projekt',noActiveProjects:'Keine aktiven Projekte',selectProject:'Projekt wählen',newProject:'+ Neues Projekt',createProjectFirst:'Zuerst ein Projekt erstellen.',standardPresets:'STANDARD-PRESETS',size:'Maß',construction:'Konstruktion',backPanel:'Rückwand',none:'keine',groove:'in Nut',overlay:'aufgesetzt',quantity:'Menge',addTo:'Hinzufügen zu',quickKitchen:'Kommerzielle Möbelbibliothek.',quickKitchenHelp:'Die Bibliothek deckt jetzt Küche, Garderobe, Bad und Hauswirtschaft ab. Exakte Montageabstände und Produktion bleiben in Makster Pro.',quoteBoundary:'Grenze von Quote.',quoteBoundaryHelp:'Hier wird kommerzielle Geometrie für Material- und Preiskalkulation genutzt. Exakte Konstruktion, Bohrungen, CNC und Montagepläne bleiben in Makster Pro.',mm:'mm',door:'Tür',doors:'Türen',drawers:'Schubladen',shelves:'Böden',visibleFront:'sichtbare Front',frontOnly:'nur Möbelfront',ovenNiche:'Backofennische',opening:'Öffnung',frontsHigh:'Fronten in der Höhe',withoutFront:'ohne Front',family:'Kategorie',allFamilies:'Alle Kategorien',search:'Suche',searchPlaceholder:'Zum Beispiel: Vorrat, Garderobe, Waschtisch…',noResults:'Keine Module entsprechen diesem Filter.'},
  pl:{title:'Biblioteka modułów',openProject:'Otwórz projekt',back:'← Pulpit',addError:'Nie udało się dodać modułu',readyPresets:'Gotowe presety',presetSummary:'kuchnia, garderoba, łazienka i gospodarcze',groups:'Grupy',groupsSummary:'uporządkowane kategorie mebli',activeProject:'Aktywny projekt',notSelected:'nie wybrano',createFirst:'utwórz pierwszy projekt',targetProject:'PROJEKT DOCELOWY',whereToAdd:'Gdzie dodać moduły',targetHelp:'Preset tworzy geometrię handlową i konstrukcję. Materiał, front, obrzeże i okucia wybiera się już w projekcie.',project:'Projekt',noActiveProjects:'Brak aktywnych projektów',selectProject:'Wybierz projekt',newProject:'+ Nowy projekt',createProjectFirst:'Najpierw utwórz projekt.',standardPresets:'STANDARDOWE PRESETY',size:'Wymiar',construction:'Konstrukcja',backPanel:'Plecy',none:'brak',groove:'w rowku',overlay:'nakładane',quantity:'Ilość',addTo:'Dodaj do',quickKitchen:'Komercyjna biblioteka mebli.',quickKitchenHelp:'Biblioteka obejmuje teraz kuchnię, garderobę, łazienkę i strefy gospodarcze. Dokładne luzy montażowe i produkcja pozostają w Makster Pro.',quoteBoundary:'Granica Quote.',quoteBoundaryHelp:'Tutaj używana jest geometria handlowa do kalkulacji materiałów i ceny. Dokładna konstrukcja, nawierty, CNC i mapy montażowe pozostają w Makster Pro.',mm:'mm',door:'drzwi',doors:'drzwi',drawers:'szuflady',shelves:'półki',visibleFront:'widoczny front',frontOnly:'tylko front meblowy',ovenNiche:'wnęka piekarnika',opening:'otwór',frontsHigh:'fronty w pionie',withoutFront:'bez frontu',family:'Kategoria',allFamilies:'Wszystkie kategorie',search:'Szukaj',searchPlaceholder:'Na przykład: spiżarnia, garderoba, umywalka…',noResults:'Brak modułów pasujących do filtra.'}
};

const familyLabels:Record<Locale,Record<QuoteModuleFamily,string>>={
  ru:{kitchen:'Кухня',wardrobe:'Гардероб',bathroom:'Ванная',utility:'Хозяйственные'},
  en:{kitchen:'Kitchen',wardrobe:'Wardrobe',bathroom:'Bathroom',utility:'Utility'},
  cs:{kitchen:'Kuchyně',wardrobe:'Šatna',bathroom:'Koupelna',utility:'Technické'},
  de:{kitchen:'Küche',wardrobe:'Garderobe',bathroom:'Bad',utility:'Hauswirtschaft'},
  pl:{kitchen:'Kuchnia',wardrobe:'Garderoba',bathroom:'Łazienka',utility:'Gospodarcze'},
};

const ruGroups:Record<string,{label:string;hint:string}>={
  'base-door':{label:'Нижние с дверями',hint:'Стандартные нижние шкафы.'},'base-drawer':{label:'Нижние с ящиками',hint:'Модули с 2–4 выдвижными ящиками.'},sink:{label:'Под мойку',hint:'Без полки и задней стенки для коммуникаций.'},'wall-door':{label:'Верхние шкафы',hint:'Стандартные, низкие и высокие навесные шкафы.'},tall:{label:'Пеналы',hint:'Высокие хозяйственные пеналы.'},appliance:{label:'Техника / ниши',hint:'Духовка, СВЧ, кофемашина, ПММ и холодильник.'},corner:{label:'Угловые модули',hint:'Коммерческая геометрия глухих углов.'},open:{label:'Открытые модули',hint:'Открытые верхние и нижние секции.'},hob:{label:'Под варочную поверхность',hint:'Нижние шкафы под зону варочной панели.'},pantry:{label:'Кладовые пеналы',hint:'Высокие секции хранения с полками.'},'wardrobe-hinged':{label:'Гардеробные секции',hint:'Длинная одежда, короткая одежда, полки и обувь.'},'wardrobe-drawer':{label:'Ящики гардероба',hint:'Низкие секции с 3–4 ящиками.'},'wardrobe-open':{label:'Открытый гардероб',hint:'Открытые секции без фасадов.'},'wardrobe-top':{label:'Антресоли',hint:'Верхние секции гардероба.'},'bathroom-vanity':{label:'Тумбы под раковину',hint:'Подвесные тумбы с дверями или ящиками.'},'bathroom-wall':{label:'Шкафы ванной',hint:'Навесные и высокие шкафы небольшой глубины.'},'utility-laundry':{label:'Прачечная',hint:'Ниши под стиральную и сушильную технику.'},'utility-storage':{label:'Хозяйственные шкафы',hint:'Высокие шкафы для хранения и уборочного инвентаря.'}
};
const groupTranslations:Record<Exclude<Locale,'ru'>,Record<string,{label:string;hint:string}>>={
  en:{'base-door':{label:'Base cabinets with doors',hint:'Standard base cabinets.'},'base-drawer':{label:'Base cabinets with drawers',hint:'Modules with 2–4 drawers.'},sink:{label:'Sink cabinets',hint:'Open back and no shelf for services.'},'wall-door':{label:'Wall cabinets',hint:'Standard, low and tall wall cabinets.'},tall:{label:'Tall cabinets',hint:'Tall utility cabinets.'},appliance:{label:'Appliances / niches',hint:'Oven, microwave, coffee machine, dishwasher and fridge.'},corner:{label:'Corner modules',hint:'Commercial geometry for blind corners.'},open:{label:'Open modules',hint:'Open wall and base sections.'},hob:{label:'Hob base cabinets',hint:'Base cabinets for hob zones.'},pantry:{label:'Pantry cabinets',hint:'Tall shelf storage sections.'},'wardrobe-hinged':{label:'Wardrobe sections',hint:'Long clothes, short clothes, shelves and shoes.'},'wardrobe-drawer':{label:'Wardrobe drawers',hint:'Low sections with 3–4 drawers.'},'wardrobe-open':{label:'Open wardrobe',hint:'Open sections without fronts.'},'wardrobe-top':{label:'Top cabinets',hint:'Wardrobe top sections.'},'bathroom-vanity':{label:'Vanity units',hint:'Wall-hung vanity units with doors or drawers.'},'bathroom-wall':{label:'Bathroom cabinets',hint:'Wall and tall shallow bathroom cabinets.'},'utility-laundry':{label:'Laundry',hint:'Niches for washer and dryer.'},'utility-storage':{label:'Utility storage',hint:'Tall storage and cleaning cabinets.'}},
  cs:{'base-door':{label:'Spodní s dvířky',hint:'Standardní spodní skříňky.'},'base-drawer':{label:'Spodní se zásuvkami',hint:'Moduly se 2–4 zásuvkami.'},sink:{label:'Pod dřez',hint:'Bez police a zad pro instalace.'},'wall-door':{label:'Horní skříňky',hint:'Standardní, nízké a vysoké závěsné skříňky.'},tall:{label:'Vysoké skříně',hint:'Vysoké užitkové skříně.'},appliance:{label:'Spotřebiče / niky',hint:'Trouba, mikrovlnka, kávovar, myčka a lednice.'},corner:{label:'Rohové moduly',hint:'Obchodní geometrie slepých rohů.'},open:{label:'Otevřené moduly',hint:'Otevřené horní a spodní sekce.'},hob:{label:'Pod varnou desku',hint:'Spodní skříňky pro varnou zónu.'},pantry:{label:'Potravinové skříně',hint:'Vysoké policové skladovací sekce.'},'wardrobe-hinged':{label:'Šatní sekce',hint:'Dlouhé a krátké oděvy, police a boty.'},'wardrobe-drawer':{label:'Šatní zásuvky',hint:'Nízké sekce se 3–4 zásuvkami.'},'wardrobe-open':{label:'Otevřená šatna',hint:'Otevřené sekce bez čel.'},'wardrobe-top':{label:'Nástavce',hint:'Horní šatní sekce.'},'bathroom-vanity':{label:'Skříňky pod umyvadlo',hint:'Závěsné skříňky s dvířky nebo zásuvkami.'},'bathroom-wall':{label:'Koupelnové skříňky',hint:'Závěsné a vysoké mělké skříňky.'},'utility-laundry':{label:'Prádelna',hint:'Niky pro pračku a sušičku.'},'utility-storage':{label:'Technické skříně',hint:'Vysoké skladovací a úklidové skříně.'}},
  de:{'base-door':{label:'Unterschränke mit Türen',hint:'Standard-Unterschränke.'},'base-drawer':{label:'Unterschränke mit Schubladen',hint:'Module mit 2–4 Schubladen.'},sink:{label:'Spülenschränke',hint:'Ohne Boden und Rückwand für Installationen.'},'wall-door':{label:'Oberschränke',hint:'Standard-, niedrige und hohe Oberschränke.'},tall:{label:'Hochschränke',hint:'Hohe Nutzschränke.'},appliance:{label:'Geräte / Nischen',hint:'Backofen, Mikrowelle, Kaffeemaschine, Spüler und Kühlschrank.'},corner:{label:'Eckmodule',hint:'Kommerzielle Geometrie für blinde Ecken.'},open:{label:'Offene Module',hint:'Offene Ober- und Unterschrank-Sektionen.'},hob:{label:'Kochfeld-Unterschränke',hint:'Unterschränke für Kochfeldzonen.'},pantry:{label:'Vorratsschränke',hint:'Hohe Regalsektionen für Vorräte.'},'wardrobe-hinged':{label:'Garderobensektionen',hint:'Lange/kurze Kleidung, Böden und Schuhe.'},'wardrobe-drawer':{label:'Garderoben-Schubladen',hint:'Niedrige Sektionen mit 3–4 Schubladen.'},'wardrobe-open':{label:'Offene Garderobe',hint:'Offene Sektionen ohne Fronten.'},'wardrobe-top':{label:'Aufsatzschränke',hint:'Obere Garderobensektionen.'},'bathroom-vanity':{label:'Waschtischunterschränke',hint:'Hängende Einheiten mit Türen oder Schubladen.'},'bathroom-wall':{label:'Badschränke',hint:'Hängende und hohe flache Badschränke.'},'utility-laundry':{label:'Wäscherei',hint:'Nischen für Waschmaschine und Trockner.'},'utility-storage':{label:'Haushaltsschränke',hint:'Hohe Lager- und Putzschränke.'}},
  pl:{'base-door':{label:'Dolne z drzwiami',hint:'Standardowe szafki dolne.'},'base-drawer':{label:'Dolne z szufladami',hint:'Moduły z 2–4 szufladami.'},sink:{label:'Pod zlew',hint:'Bez półki i pleców dla instalacji.'},'wall-door':{label:'Szafki górne',hint:'Standardowe, niskie i wysokie wiszące.'},tall:{label:'Słupki',hint:'Wysokie szafy gospodarcze.'},appliance:{label:'AGD / wnęki',hint:'Piekarnik, mikrofalówka, ekspres, zmywarka i lodówka.'},corner:{label:'Moduły narożne',hint:'Geometria handlowa ślepych narożników.'},open:{label:'Moduły otwarte',hint:'Otwarte sekcje górne i dolne.'},hob:{label:'Pod płytę grzewczą',hint:'Szafki dolne dla strefy płyty.'},pantry:{label:'Spiżarnie',hint:'Wysokie sekcje półkowe do przechowywania.'},'wardrobe-hinged':{label:'Sekcje garderoby',hint:'Długie i krótkie ubrania, półki i buty.'},'wardrobe-drawer':{label:'Szuflady garderoby',hint:'Niskie sekcje z 3–4 szufladami.'},'wardrobe-open':{label:'Garderoba otwarta',hint:'Otwarte sekcje bez frontów.'},'wardrobe-top':{label:'Nadstawki',hint:'Górne sekcje garderoby.'},'bathroom-vanity':{label:'Szafki pod umywalkę',hint:'Wiszące szafki z drzwiami lub szufladami.'},'bathroom-wall':{label:'Szafki łazienkowe',hint:'Wiszące i wysokie płytkie szafki.'},'utility-laundry':{label:'Pralnia',hint:'Wnęki na pralkę i suszarkę.'},'utility-storage':{label:'Szafy gospodarcze',hint:'Wysokie szafy do przechowywania i sprzątania.'}}
};

export function getLibraryMessages(locale:Locale){return messages[locale];}
export function libraryFamily(locale:Locale,family:QuoteModuleFamily){return familyLabels[locale][family];}
export function libraryGroup(locale:Locale,group:string){return locale==='ru'?(ruGroups[group]??{label:group,hint:''}):(groupTranslations[locale][group]??{label:group,hint:''});}

export function localizePreset(locale:Locale,preset:QuoteModulePreset){
  if(locale==='ru')return{name:preset.name,description:preset.description};
  const translated=preset.translations?.[locale];
  if(translated)return translated;
  const m=messages[locale];const w=preset.widthMm;
  if(preset.group==='base-door')return{name:`${locale==='de'?'Unterschrank':locale==='cs'?'Spodní':locale==='pl'?'Dolna':'Base'} ${w}`,description:`${w} ${m.mm} · ${preset.doors} ${m.doors} · ${preset.shelfCount} ${m.shelves}.`};
  if(preset.group==='base-drawer')return{name:`${locale==='de'?'Unterschrank':locale==='cs'?'Spodní':locale==='pl'?'Dolna':'Base'} ${w} · ${preset.drawers} ${m.drawers}`,description:`${w} ${m.mm} · ${preset.drawers} ${m.drawers}.`};
  if(preset.group==='sink')return{name:`${locale==='de'?'Spüle':locale==='cs'?'Dřez':locale==='pl'?'Zlew':'Sink'} ${w}`,description:`${w} ${m.mm} · ${preset.doors} ${m.doors}.`};
  if(preset.group==='wall-door')return{name:`${locale==='de'?'Oberschrank':locale==='cs'?'Horní':locale==='pl'?'Górna':'Wall'} ${w} × ${preset.heightMm}`,description:`${w} × ${preset.heightMm} × ${preset.depthMm} ${m.mm} · ${preset.shelfCount} ${m.shelves}.`};
  if(preset.group==='tall')return{name:`${locale==='de'?'Hochschrank':locale==='cs'?'Vysoká':locale==='pl'?'Słupek':'Tall'} ${w}`,description:`${w} × ${preset.heightMm} ${m.mm} · ${preset.shelfCount} ${m.shelves}.`};
  if(preset.group==='corner')return{name:`${locale==='de'?'Eckmodul':locale==='cs'?'Rohový modul':locale==='pl'?'Narożnik':'Corner'} ${w}`,description:`${w} ${m.mm} · ${m.visibleFront} ${preset.frontWidthMm??preset.widthMm} ${m.mm}.`};
  if(preset.group==='open')return{name:`${locale==='de'?'Offenes Modul':locale==='cs'?'Otevřený modul':locale==='pl'?'Moduł otwarty':'Open module'} ${w}`,description:`${w} ${m.mm} · ${preset.shelfCount} ${m.shelves} · ${m.withoutFront}.`};
  if(preset.moduleKey==='dishwasher')return{name:`${locale==='de'?'Geschirrspüler':locale==='cs'?'Myčka':locale==='pl'?'Zmywarka':'Dishwasher'} ${w}`,description:`${w} ${m.mm} · ${m.frontOnly}.`};
  if(preset.moduleKey==='b-oven')return{name:`${locale==='de'?'Backofen':locale==='cs'?'Trouba':locale==='pl'?'Piekarnik':'Oven'} ${w}`,description:`${w} ${m.mm} · ${m.ovenNiche}.`};
  if(preset.moduleKey==='t-oven')return{name:`${locale==='de'?'Hochschrank Backofen':locale==='cs'?'Vysoká trouba':locale==='pl'?'Słupek piekarnik':'Tall oven'} ${w}`,description:`${m.opening} ${preset.applianceOpeningHeightMm??600} ${m.mm}.`};
  if(preset.moduleKey==='t-fridge')return{name:`${locale==='de'?'Hochschrank Kühlschrank':locale==='cs'?'Vysoká lednice':locale==='pl'?'Słupek lodówka':'Tall fridge'} ${w}`,description:`${preset.doors} ${m.frontsHigh} · ${m.none} ${m.backPanel.toLowerCase()}.`};
  return{name:preset.name,description:preset.description};
}

export function presetFeature(locale:Locale,preset:QuoteModulePreset){
  const m=messages[locale];
  if(preset.group==='corner')return `${m.visibleFront} ${preset.frontWidthMm??preset.widthMm} ${m.mm}`;
  if(preset.moduleKey==='b-drawer')return `${preset.drawers} ${m.drawers}`;
  if(preset.moduleKey==='dishwasher')return m.frontOnly;
  if(preset.moduleKey==='b-oven')return m.ovenNiche;
  if(preset.moduleKey==='t-oven')return `${m.opening} ${preset.applianceOpeningHeightMm??600} ${m.mm}`;
  if(preset.moduleKey==='t-fridge')return `${preset.doors} ${m.frontsHigh}`;
  if(preset.moduleKey==='open')return `${preset.shelfCount} ${m.shelves} · ${m.withoutFront}`;
  return `${preset.doors} ${preset.doors===1?m.door:m.doors} · ${preset.shelfCount} ${m.shelves}`;
}
