import type { Locale } from './i18n';
import type { ModuleKey } from './engineering';

export type CabinetMessages = {
  modules:string; addFirst:string; savedProject:string; cost:string; price:string; editing:string; newModule:string; duplicate:string; remove:string; confirmRemove:string; save:string;
  typeAndSize:string; type:string; name:string; quantity:string; carcassThickness:string; width:string; height:string; depth:string; construction:string; frontGap:string; drawers:string; doors:string; frontsHeight:string; shelves:string; stretcherDepth:string; shelfSetback:string; ovenOpening:string; frontEdge:string; edgeIncluded:string; sameEdge:string; labourHours:string;
  back:string; mounting:string; groove:string; overlay:string; noBack:string; thickness:string; grooveInset:string; grooveDepth:string; materialsHardware:string; board:string; front:string; backMaterial:string; edge:string; hinge:string; drawerSet:string; labourRate:string; notSelected:string;
  parts:string; part:string; material:string; qty:string; size:string; edgeColumn:string; detailsPerUnit:string; usageParts:string; carcass:string; fronts:string; hardware:string; operations:string; labour:string; overhead:string; unitCost:string; recommended:string; margin:string; total:string; missingPrice:string; needsFill:string; complete:string; assumptions:string; identicalModules:string; autoMultiply:string; pcs:string; meterPerPiece:string; mm:string;
  defaultName:string;
  modulesMap:Record<ModuleKey,string>; roles:Record<string,string>;
};

const baseModules: Record<Locale, Record<ModuleKey,string>> = {
  ru:{'b-door':'Нижний с дверью','b-drawer':'Нижний с ящиками','b-oven':'Нижний под духовку','w-door':'Верхний с дверью','t-door':'Высокий пенал','t-oven':'Пенал под духовку','t-fridge':'Пенал под холодильник',dishwasher:'ПММ · фасад',open:'Открытый модуль',generic:'Универсальный корпус'},
  en:{'b-door':'Base with door','b-drawer':'Base with drawers','b-oven':'Base oven','w-door':'Wall with door','t-door':'Tall cabinet','t-oven':'Tall oven','t-fridge':'Tall fridge',dishwasher:'Dishwasher · front',open:'Open module',generic:'Generic cabinet'},
  cs:{'b-door':'Spodní s dvířky','b-drawer':'Spodní se zásuvkami','b-oven':'Spodní pro troubu','w-door':'Horní s dvířky','t-door':'Vysoká skříň','t-oven':'Vysoká pro troubu','t-fridge':'Vysoká pro lednici',dishwasher:'Myčka · čelo',open:'Otevřený modul',generic:'Univerzální korpus'},
  de:{'b-door':'Unterschrank mit Tür','b-drawer':'Unterschrank mit Schubladen','b-oven':'Unterschrank Backofen','w-door':'Oberschrank mit Tür','t-door':'Hochschrank','t-oven':'Hochschrank Backofen','t-fridge':'Hochschrank Kühlschrank',dishwasher:'Geschirrspüler · Front',open:'Offenes Modul',generic:'Universalkorpus'},
  pl:{'b-door':'Dolna z drzwiami','b-drawer':'Dolna z szufladami','b-oven':'Dolna pod piekarnik','w-door':'Górna z drzwiami','t-door':'Słupek','t-oven':'Słupek pod piekarnik','t-fridge':'Słupek pod lodówkę',dishwasher:'Zmywarka · front',open:'Moduł otwarty',generic:'Korpus uniwersalny'},
};

const messages: Record<Locale, Omit<CabinetMessages,'modulesMap'>> = {
  ru:{modules:'Модули',addFirst:'Добавьте первый модуль.',savedProject:'Сохранено по проекту',cost:'Себестоимость',price:'Цена',editing:'РЕДАКТИРОВАНИЕ',newModule:'НОВЫЙ МОДУЛЬ',duplicate:'Дублировать',remove:'Удалить',confirmRemove:'Удалить этот модуль из текущего проекта? Выпущенные ранее предложения не изменятся.',save:'Сохранить',typeAndSize:'Тип и размеры',type:'Тип',name:'Название',quantity:'Количество',carcassThickness:'Толщина корпуса, мм',width:'Ширина, мм',height:'Высота, мм',depth:'Глубина, мм',construction:'Конструкция',frontGap:'Зазор фасада, мм',drawers:'Ящиков',doors:'Дверей',frontsHeight:'Фасадов по высоте',shelves:'Полок / перегородок',stretcherDepth:'Глубина царги, мм',shelfSetback:'Отступ полки сзади, мм',ovenOpening:'Высота проёма духовки, мм',frontEdge:'Кромка фасада',edgeIncluded:'Входит в цену фасада',sameEdge:'Считать той же кромкой',labourHours:'Прямой труд, часов',back:'Задняя стенка',mounting:'Монтаж',groove:'В паз',overlay:'Накладная',noBack:'Без задней стенки',thickness:'Толщина, мм',grooveInset:'Отступ паза, мм',grooveDepth:'Глубина паза, мм',materialsHardware:'Материалы и фурнитура',board:'Плита корпуса',front:'Фасад',backMaterial:'Задняя стенка',edge:'Кромка',hinge:'Петля',drawerSet:'Комплект ящика',labourRate:'Ставка труда',notSelected:'— не выбрано —',parts:'Деталировка на 1 шт.',part:'Деталь',material:'Материал',qty:'Кол.',size:'Размер, мм',edgeColumn:'Кромка',detailsPerUnit:'деталей/шт',usageParts:'использование',carcass:'Корпус',fronts:'Фасады',hardware:'Фурнитура',operations:'Производственные операции',labour:'Прямой труд',overhead:'Накладные',unitCost:'Себестоимость 1 шт.',recommended:'Рекомендуемая цена 1 шт.',margin:'маржа',total:'Итого',missingPrice:'цена не выбрана',needsFill:'До полного расчёта нужно заполнить',complete:'Модуль рассчитан полностью.',assumptions:'Допущения engine 0.1.10',identicalModules:'одинаковых модулей',autoMultiply:'Итоговая стоимость умножается автоматически.',pcs:'шт',meterPerPiece:'м/шт',mm:'мм',defaultName:'Шкаф с ящиками',roles:{board:'Корпус',front:'Фасад',back:'Задняя стенка'}},
  en:{modules:'Modules',addFirst:'Add the first module.',savedProject:'Saved project totals',cost:'Cost',price:'Price',editing:'EDITING',newModule:'NEW MODULE',duplicate:'Duplicate',remove:'Delete',confirmRemove:'Delete this module from the working project? Previously published quotes will not change.',save:'Save',typeAndSize:'Type & dimensions',type:'Type',name:'Name',quantity:'Quantity',carcassThickness:'Carcass thickness, mm',width:'Width, mm',height:'Height, mm',depth:'Depth, mm',construction:'Construction',frontGap:'Front gap, mm',drawers:'Drawers',doors:'Doors',frontsHeight:'Fronts vertically',shelves:'Shelves / dividers',stretcherDepth:'Stretcher depth, mm',shelfSetback:'Rear shelf setback, mm',ovenOpening:'Oven opening height, mm',frontEdge:'Front edge band',edgeIncluded:'Included in front price',sameEdge:'Use selected edge band',labourHours:'Direct labour, hours',back:'Back panel',mounting:'Mounting',groove:'In groove',overlay:'Overlay',noBack:'No back panel',thickness:'Thickness, mm',grooveInset:'Groove inset, mm',grooveDepth:'Groove depth, mm',materialsHardware:'Materials & hardware',board:'Carcass board',front:'Front',backMaterial:'Back panel',edge:'Edge band',hinge:'Hinge',drawerSet:'Drawer set',labourRate:'Labour rate',notSelected:'— not selected —',parts:'Parts per unit',part:'Part',material:'Material',qty:'Qty',size:'Size, mm',edgeColumn:'Edge',detailsPerUnit:'parts/unit',usageParts:'usage',carcass:'Carcass',fronts:'Fronts',hardware:'Hardware',operations:'Production operations',labour:'Direct labour',overhead:'Overhead',unitCost:'Cost per unit',recommended:'Recommended price per unit',margin:'margin',total:'Total',missingPrice:'price not selected',needsFill:'Complete the following before full costing',complete:'Module is fully calculated.',assumptions:'Engine 0.1.10 assumptions',identicalModules:'identical modules',autoMultiply:'Total cost is multiplied automatically.',pcs:'pcs',meterPerPiece:'m/pc',mm:'mm',defaultName:'Drawer cabinet',roles:{board:'Carcass',front:'Front',back:'Back panel'}},
  cs:{modules:'Moduly',addFirst:'Přidejte první modul.',savedProject:'Uloženo za projekt',cost:'Náklady',price:'Cena',editing:'ÚPRAVA',newModule:'NOVÝ MODUL',duplicate:'Duplikovat',remove:'Smazat',confirmRemove:'Smazat tento modul z pracovního projektu? Dříve vydané nabídky se nezmění.',save:'Uložit',typeAndSize:'Typ a rozměry',type:'Typ',name:'Název',quantity:'Množství',carcassThickness:'Tloušťka korpusu, mm',width:'Šířka, mm',height:'Výška, mm',depth:'Hloubka, mm',construction:'Konstrukce',frontGap:'Spára čela, mm',drawers:'Zásuvky',doors:'Dvířka',frontsHeight:'Čela na výšku',shelves:'Police / příčky',stretcherDepth:'Hloubka lubu, mm',shelfSetback:'Odsazení police zezadu, mm',ovenOpening:'Výška otvoru trouby, mm',frontEdge:'Hrana čela',edgeIncluded:'V ceně čela',sameEdge:'Počítat stejnou hranou',labourHours:'Přímá práce, hodiny',back:'Zadní stěna',mounting:'Montáž',groove:'Do drážky',overlay:'Překrytá',noBack:'Bez zadní stěny',thickness:'Tloušťka, mm',grooveInset:'Odsazení drážky, mm',grooveDepth:'Hloubka drážky, mm',materialsHardware:'Materiály a kování',board:'Korpusová deska',front:'Čelo',backMaterial:'Zadní stěna',edge:'Hrana',hinge:'Závěs',drawerSet:'Sada zásuvky',labourRate:'Sazba práce',notSelected:'— nevybráno —',parts:'Díly na 1 ks',part:'Díl',material:'Materiál',qty:'Počet',size:'Rozměr, mm',edgeColumn:'Hrana',detailsPerUnit:'dílů/ks',usageParts:'spotřeba',carcass:'Korpus',fronts:'Čela',hardware:'Kování',operations:'Výrobní operace',labour:'Přímá práce',overhead:'Režie',unitCost:'Náklady na 1 ks',recommended:'Doporučená cena za 1 ks',margin:'marže',total:'Celkem',missingPrice:'cena nevybrána',needsFill:'Pro úplnou kalkulaci doplňte',complete:'Modul je kompletně spočítán.',assumptions:'Předpoklady engine 0.1.10',identicalModules:'stejných modulů',autoMultiply:'Celková cena se násobí automaticky.',pcs:'ks',meterPerPiece:'m/ks',mm:'mm',defaultName:'Skříňka se zásuvkami',roles:{board:'Korpus',front:'Čelo',back:'Zadní stěna'}},
  de:{modules:'Module',addFirst:'Erstes Modul hinzufügen.',savedProject:'Gespeicherte Projektsumme',cost:'Kosten',price:'Preis',editing:'BEARBEITUNG',newModule:'NEUES MODUL',duplicate:'Duplizieren',remove:'Löschen',confirmRemove:'Dieses Modul aus dem Arbeitsprojekt löschen? Frühere veröffentlichte Angebote bleiben unverändert.',save:'Speichern',typeAndSize:'Typ & Maße',type:'Typ',name:'Name',quantity:'Menge',carcassThickness:'Korpusdicke, mm',width:'Breite, mm',height:'Höhe, mm',depth:'Tiefe, mm',construction:'Konstruktion',frontGap:'Frontfuge, mm',drawers:'Schubladen',doors:'Türen',frontsHeight:'Fronten in der Höhe',shelves:'Böden / Trennwände',stretcherDepth:'Zargentiefe, mm',shelfSetback:'Bodenrücksprung, mm',ovenOpening:'Backofenöffnung Höhe, mm',frontEdge:'Frontkante',edgeIncluded:'Im Frontpreis enthalten',sameEdge:'Gleiche Kante berechnen',labourHours:'Direkte Arbeit, Stunden',back:'Rückwand',mounting:'Montage',groove:'In Nut',overlay:'Aufgesetzt',noBack:'Ohne Rückwand',thickness:'Dicke, mm',grooveInset:'Nutabstand, mm',grooveDepth:'Nuttiefe, mm',materialsHardware:'Materialien & Beschläge',board:'Korpusplatte',front:'Front',backMaterial:'Rückwand',edge:'Kante',hinge:'Scharnier',drawerSet:'Schubladensatz',labourRate:'Arbeitsstundensatz',notSelected:'— nicht gewählt —',parts:'Teile pro Stück',part:'Teil',material:'Material',qty:'Anz.',size:'Maß, mm',edgeColumn:'Kante',detailsPerUnit:'Teile/Stk',usageParts:'Verbrauch',carcass:'Korpus',fronts:'Fronten',hardware:'Beschläge',operations:'Produktionsoperationen',labour:'Direkte Arbeit',overhead:'Gemeinkosten',unitCost:'Kosten pro Stück',recommended:'Empfohlener Preis pro Stück',margin:'Marge',total:'Gesamt',missingPrice:'Preis nicht gewählt',needsFill:'Für vollständige Kalkulation ergänzen',complete:'Modul vollständig kalkuliert.',assumptions:'Annahmen Engine 0.1.10',identicalModules:'identische Module',autoMultiply:'Gesamtkosten werden automatisch multipliziert.',pcs:'Stk',meterPerPiece:'m/Stk',mm:'mm',defaultName:'Schubladenschrank',roles:{board:'Korpus',front:'Front',back:'Rückwand'}},
  pl:{modules:'Moduły',addFirst:'Dodaj pierwszy moduł.',savedProject:'Zapisane dla projektu',cost:'Koszt',price:'Cena',editing:'EDYCJA',newModule:'NOWY MODUŁ',duplicate:'Duplikuj',remove:'Usuń',confirmRemove:'Usunąć ten moduł z projektu roboczego? Wcześniej opublikowane oferty pozostaną bez zmian.',save:'Zapisz',typeAndSize:'Typ i wymiary',type:'Typ',name:'Nazwa',quantity:'Ilość',carcassThickness:'Grubość korpusu, mm',width:'Szerokość, mm',height:'Wysokość, mm',depth:'Głębokość, mm',construction:'Konstrukcja',frontGap:'Szczelina frontu, mm',drawers:'Szuflady',doors:'Drzwi',frontsHeight:'Fronty w pionie',shelves:'Półki / przegrody',stretcherDepth:'Głębokość listwy, mm',shelfSetback:'Cofnięcie półki, mm',ovenOpening:'Wysokość wnęki piekarnika, mm',frontEdge:'Obrzeże frontu',edgeIncluded:'W cenie frontu',sameEdge:'Liczyć tym samym obrzeżem',labourHours:'Praca bezpośrednia, godziny',back:'Plecy',mounting:'Montaż',groove:'W rowku',overlay:'Nakładane',noBack:'Bez pleców',thickness:'Grubość, mm',grooveInset:'Odsunięcie rowka, mm',grooveDepth:'Głębokość rowka, mm',materialsHardware:'Materiały i okucia',board:'Płyta korpusu',front:'Front',backMaterial:'Plecy',edge:'Obrzeże',hinge:'Zawias',drawerSet:'Komplet szuflady',labourRate:'Stawka robocizny',notSelected:'— nie wybrano —',parts:'Rozkrój na 1 szt.',part:'Element',material:'Materiał',qty:'Ilość',size:'Wymiar, mm',edgeColumn:'Obrzeże',detailsPerUnit:'elementów/szt',usageParts:'zużycie',carcass:'Korpus',fronts:'Fronty',hardware:'Okucia',operations:'Operacje produkcyjne',labour:'Praca bezpośrednia',overhead:'Koszty ogólne',unitCost:'Koszt 1 szt.',recommended:'Zalecana cena 1 szt.',margin:'marża',total:'Razem',missingPrice:'nie wybrano ceny',needsFill:'Do pełnej kalkulacji uzupełnij',complete:'Moduł policzony w całości.',assumptions:'Założenia engine 0.1.10',identicalModules:'identycznych modułów',autoMultiply:'Koszt całkowity jest mnożony automatycznie.',pcs:'szt',meterPerPiece:'m/szt',mm:'mm',defaultName:'Szafka z szufladami',roles:{board:'Korpus',front:'Front',back:'Plecy'}}
};

export function getCabinetMessages(locale: Locale): CabinetMessages {
  return {...messages[locale], modulesMap:baseModules[locale]};
}
