import type { Locale } from './i18n';
import type { QuoteModulePreset } from './module-presets';

export type LibraryMessages={
  title:string;openProject:string;back:string;addError:string;readyPresets:string;presetSummary:string;groups:string;groupsSummary:string;activeProject:string;notSelected:string;createFirst:string;targetProject:string;whereToAdd:string;targetHelp:string;project:string;noActiveProjects:string;selectProject:string;newProject:string;createProjectFirst:string;standardPresets:string;size:string;construction:string;backPanel:string;none:string;groove:string;overlay:string;quantity:string;addTo:string;quickKitchen:string;quickKitchenHelp:string;quoteBoundary:string;quoteBoundaryHelp:string;mm:string;door:string;doors:string;drawers:string;shelves:string;visibleFront:string;frontOnly:string;ovenNiche:string;opening:string;frontsHigh:string;withoutFront:string;
};

const messages:Record<Locale,LibraryMessages>={
  ru:{title:'Библиотека модулей',openProject:'Открыть проект',back:'← Главная',addError:'Не удалось добавить модуль',readyPresets:'Готовых пресетов',presetSummary:'низ, верх, пеналы, техника, углы и открытые',groups:'Групп',groupsSummary:'для быстрого набора кухни',activeProject:'Активный проект',notSelected:'не выбран',createFirst:'создайте первый проект',targetProject:'ЦЕЛЕВОЙ ПРОЕКТ',whereToAdd:'Куда добавить модули',targetHelp:'Пресет создаёт коммерческую геометрию и конструкцию. Материал, фасад, кромку и фурнитуру выбираем уже в проекте.',project:'Проект',noActiveProjects:'Нет активных проектов',selectProject:'Выбрать проект',newProject:'+ Новый проект',createProjectFirst:'Сначала создайте проект.',standardPresets:'STANDARD PRESETS',size:'Размер',construction:'Конструкция',backPanel:'Задняя стенка',none:'нет',groove:'в паз',overlay:'накладная',quantity:'Количество',addTo:'Добавить в',quickKitchen:'Быстрый набор кухни.',quickKitchenHelp:'Библиотека покрывает низ, верх, пеналы, мойку, технику, глухие углы и открытые секции. Столешница, цоколь, доборы и декоративные боковины считаются на уровне проекта.',quoteBoundary:'Граница Quote.',quoteBoundaryHelp:'Угловые модули и техника здесь имеют коммерческую геометрию. Точная конструкция, монтажные зазоры, присадка и CNC остаются в Makster Pro.',mm:'мм',door:'дверь',doors:'двери',drawers:'ящика',shelves:'полки',visibleFront:'видимый фасад',frontOnly:'только мебельный фасад',ovenNiche:'ниша под духовку',opening:'проём',frontsHigh:'фасада по высоте',withoutFront:'без фасада'},
  en:{title:'Module Library',openProject:'Open project',back:'← Dashboard',addError:'Could not add module',readyPresets:'Ready presets',presetSummary:'base, wall, tall, appliances, corners and open modules',groups:'Groups',groupsSummary:'for quick kitchen composition',activeProject:'Active project',notSelected:'not selected',createFirst:'create the first project',targetProject:'TARGET PROJECT',whereToAdd:'Where to add modules',targetHelp:'A preset creates commercial geometry and construction. Materials, fronts, edge band and hardware are selected inside the project.',project:'Project',noActiveProjects:'No active projects',selectProject:'Select project',newProject:'+ New project',createProjectFirst:'Create a project first.',standardPresets:'STANDARD PRESETS',size:'Size',construction:'Construction',backPanel:'Back panel',none:'none',groove:'in groove',overlay:'overlay',quantity:'Quantity',addTo:'Add to',quickKitchen:'Quick kitchen composition.',quickKitchenHelp:'The library covers base, wall and tall cabinets, sink, appliances, blind corners and open modules. Worktop, plinth, fillers and decorative sides are costed at project level.',quoteBoundary:'Quote boundary.',quoteBoundaryHelp:'Corner and appliance modules use commercial geometry here. Exact construction, installation clearances, drilling and CNC remain in Makster Pro.',mm:'mm',door:'door',doors:'doors',drawers:'drawers',shelves:'shelves',visibleFront:'visible front',frontOnly:'furniture front only',ovenNiche:'oven niche',opening:'opening',frontsHigh:'fronts vertically',withoutFront:'without front'},
  cs:{title:'Knihovna modulů',openProject:'Otevřít projekt',back:'← Přehled',addError:'Modul se nepodařilo přidat',readyPresets:'Hotové presety',presetSummary:'spodní, horní, vysoké, spotřebiče, rohy a otevřené',groups:'Skupiny',groupsSummary:'pro rychlé sestavení kuchyně',activeProject:'Aktivní projekt',notSelected:'nevybrán',createFirst:'vytvořte první projekt',targetProject:'CÍLOVÝ PROJEKT',whereToAdd:'Kam přidat moduly',targetHelp:'Preset vytváří obchodní geometrii a konstrukci. Materiál, čelo, hranu a kování vyberete v projektu.',project:'Projekt',noActiveProjects:'Žádné aktivní projekty',selectProject:'Vybrat projekt',newProject:'+ Nový projekt',createProjectFirst:'Nejprve vytvořte projekt.',standardPresets:'STANDARDNÍ PRESETY',size:'Rozměr',construction:'Konstrukce',backPanel:'Zadní stěna',none:'bez',groove:'do drážky',overlay:'překrytá',quantity:'Množství',addTo:'Přidat do',quickKitchen:'Rychlé sestavení kuchyně.',quickKitchenHelp:'Knihovna pokrývá spodní, horní a vysoké skříně, dřez, spotřebiče, slepé rohy a otevřené moduly. Pracovní deska, sokl, výplně a dekorativní boky se počítají na úrovni projektu.',quoteBoundary:'Hranice Quote.',quoteBoundaryHelp:'Rohové a spotřebičové moduly zde používají obchodní geometrii. Přesná konstrukce, montážní vůle, vrtání a CNC zůstávají v Makster Pro.',mm:'mm',door:'dvířka',doors:'dvířka',drawers:'zásuvky',shelves:'police',visibleFront:'viditelné čelo',frontOnly:'pouze nábytkové čelo',ovenNiche:'otvor pro troubu',opening:'otvor',frontsHigh:'čela na výšku',withoutFront:'bez čela'},
  de:{title:'Modulbibliothek',openProject:'Projekt öffnen',back:'← Übersicht',addError:'Modul konnte nicht hinzugefügt werden',readyPresets:'Fertige Presets',presetSummary:'Unter-, Ober-, Hochschränke, Geräte, Ecken und offene Module',groups:'Gruppen',groupsSummary:'für schnellen Küchenaufbau',activeProject:'Aktives Projekt',notSelected:'nicht gewählt',createFirst:'erstes Projekt erstellen',targetProject:'ZIELPROJEKT',whereToAdd:'Module hinzufügen zu',targetHelp:'Ein Preset erzeugt kommerzielle Geometrie und Konstruktion. Material, Front, Kante und Beschläge werden im Projekt gewählt.',project:'Projekt',noActiveProjects:'Keine aktiven Projekte',selectProject:'Projekt wählen',newProject:'+ Neues Projekt',createProjectFirst:'Zuerst ein Projekt erstellen.',standardPresets:'STANDARD-PRESETS',size:'Maß',construction:'Konstruktion',backPanel:'Rückwand',none:'keine',groove:'in Nut',overlay:'aufgesetzt',quantity:'Menge',addTo:'Hinzufügen zu',quickKitchen:'Schnelle Küchenzusammenstellung.',quickKitchenHelp:'Die Bibliothek deckt Unter-, Ober- und Hochschränke, Spüle, Geräte, blinde Ecken und offene Module ab. Arbeitsplatte, Sockel, Blenden und Dekorseiten werden auf Projektebene kalkuliert.',quoteBoundary:'Grenze von Quote.',quoteBoundaryHelp:'Eck- und Gerätemodule verwenden hier kommerzielle Geometrie. Exakte Konstruktion, Montageabstände, Bohrungen und CNC bleiben Makster Pro.',mm:'mm',door:'Tür',doors:'Türen',drawers:'Schubladen',shelves:'Böden',visibleFront:'sichtbare Front',frontOnly:'nur Möbelfront',ovenNiche:'Backofennische',opening:'Öffnung',frontsHigh:'Fronten in der Höhe',withoutFront:'ohne Front'},
  pl:{title:'Biblioteka modułów',openProject:'Otwórz projekt',back:'← Pulpit',addError:'Nie udało się dodać modułu',readyPresets:'Gotowe presety',presetSummary:'dolne, górne, słupki, AGD, narożniki i otwarte',groups:'Grupy',groupsSummary:'do szybkiego zestawienia kuchni',activeProject:'Aktywny projekt',notSelected:'nie wybrano',createFirst:'utwórz pierwszy projekt',targetProject:'PROJEKT DOCELOWY',whereToAdd:'Gdzie dodać moduły',targetHelp:'Preset tworzy geometrię handlową i konstrukcję. Materiał, front, obrzeże i okucia wybiera się już w projekcie.',project:'Projekt',noActiveProjects:'Brak aktywnych projektów',selectProject:'Wybierz projekt',newProject:'+ Nowy projekt',createProjectFirst:'Najpierw utwórz projekt.',standardPresets:'STANDARDOWE PRESETY',size:'Wymiar',construction:'Konstrukcja',backPanel:'Plecy',none:'brak',groove:'w rowku',overlay:'nakładane',quantity:'Ilość',addTo:'Dodaj do',quickKitchen:'Szybkie zestawienie kuchni.',quickKitchenHelp:'Biblioteka obejmuje moduły dolne, górne, słupki, zlew, AGD, ślepe narożniki i moduły otwarte. Blat, cokół, blendy i boki dekoracyjne są liczone na poziomie projektu.',quoteBoundary:'Granica Quote.',quoteBoundaryHelp:'Moduły narożne i AGD mają tutaj geometrię handlową. Dokładna konstrukcja, luzy montażowe, nawiercanie i CNC pozostają w Makster Pro.',mm:'mm',door:'drzwi',doors:'drzwi',drawers:'szuflady',shelves:'półki',visibleFront:'widoczny front',frontOnly:'tylko front meblowy',ovenNiche:'wnęka piekarnika',opening:'otwór',frontsHigh:'fronty w pionie',withoutFront:'bez frontu'}
};

const groups:Record<Locale,Record<string,{label:string;hint:string}>>={
  ru:{'base-door':{label:'Нижние с дверями',hint:'Стандартные ширины для обычных нижних шкафов.'},'base-drawer':{label:'Нижние с ящиками',hint:'Быстрые модули с 2 или 3 ящиками.'},sink:{label:'Под мойку',hint:'Без полки и задней стенки — для зоны мойки.'},'wall-door':{label:'Верхние шкафы',hint:'Навесные шкафы высотой 720 мм и глубиной 350 мм.'},tall:{label:'Пеналы',hint:'Высокие хозяйственные пеналы для кухни и встроенных зон.'},appliance:{label:'Техника / ниши',hint:'Мебельная оболочка и фасады под духовку, ПММ и встроенный холодильник.'},corner:{label:'Угловые модули',hint:'Глухие угловые модули с отдельной видимой шириной фасада. Это коммерческая геометрия, не CNC.'},open:{label:'Открытые модули',hint:'Открытые верхние и нижние модули без мебельного фасада.'}},
  en:{'base-door':{label:'Base cabinets with doors',hint:'Standard widths for regular base cabinets.'},'base-drawer':{label:'Base cabinets with drawers',hint:'Quick modules with 2 or 3 drawers.'},sink:{label:'Sink cabinets',hint:'No shelf and no back panel for the sink zone.'},'wall-door':{label:'Wall cabinets',hint:'720 mm high, 350 mm deep wall cabinets.'},tall:{label:'Tall cabinets',hint:'Tall utility cabinets for kitchens and built-in zones.'},appliance:{label:'Appliances / niches',hint:'Furniture shell and fronts for oven, dishwasher and built-in fridge.'},corner:{label:'Corner modules',hint:'Blind corner modules with a separate visible front width. Commercial geometry, not CNC.'},open:{label:'Open modules',hint:'Open wall and base modules without furniture fronts.'}},
  cs:{'base-door':{label:'Spodní s dvířky',hint:'Standardní šířky běžných spodních skříněk.'},'base-drawer':{label:'Spodní se zásuvkami',hint:'Rychlé moduly se 2 nebo 3 zásuvkami.'},sink:{label:'Pod dřez',hint:'Bez police a zadní stěny pro dřezovou zónu.'},'wall-door':{label:'Horní skříňky',hint:'Závěsné skříňky výšky 720 mm a hloubky 350 mm.'},tall:{label:'Vysoké skříně',hint:'Vysoké užitkové skříně pro kuchyně a vestavby.'},appliance:{label:'Spotřebiče / niky',hint:'Nábytkový korpus a čela pro troubu, myčku a vestavnou lednici.'},corner:{label:'Rohové moduly',hint:'Slepé rohové moduly se samostatnou viditelnou šířkou čela. Obchodní geometrie, ne CNC.'},open:{label:'Otevřené moduly',hint:'Otevřené horní a spodní moduly bez nábytkového čela.'}},
  de:{'base-door':{label:'Unterschränke mit Türen',hint:'Standardbreiten für normale Unterschränke.'},'base-drawer':{label:'Unterschränke mit Schubladen',hint:'Schnelle Module mit 2 oder 3 Schubladen.'},sink:{label:'Spülenschränke',hint:'Ohne Boden und Rückwand für den Spülenbereich.'},'wall-door':{label:'Oberschränke',hint:'720 mm hohe und 350 mm tiefe Oberschränke.'},tall:{label:'Hochschränke',hint:'Hohe Vorrats- und Einbauschränke.'},appliance:{label:'Geräte / Nischen',hint:'Möbelkorpus und Fronten für Backofen, Geschirrspüler und Einbaukühlschrank.'},corner:{label:'Eckmodule',hint:'Blinde Eckmodule mit separater sichtbarer Frontbreite. Kommerzielle Geometrie, kein CNC.'},open:{label:'Offene Module',hint:'Offene Ober- und Unterschränke ohne Möbelfront.'}},
  pl:{'base-door':{label:'Dolne z drzwiami',hint:'Standardowe szerokości zwykłych szafek dolnych.'},'base-drawer':{label:'Dolne z szufladami',hint:'Szybkie moduły z 2 lub 3 szufladami.'},sink:{label:'Pod zlew',hint:'Bez półki i pleców — do strefy zlewu.'},'wall-door':{label:'Szafki górne',hint:'Szafki wiszące o wysokości 720 mm i głębokości 350 mm.'},tall:{label:'Słupki',hint:'Wysokie szafy gospodarcze do kuchni i zabudów.'},appliance:{label:'AGD / wnęki',hint:'Korpus i fronty pod piekarnik, zmywarkę i lodówkę do zabudowy.'},corner:{label:'Moduły narożne',hint:'Ślepe narożniki z osobną widoczną szerokością frontu. Geometria handlowa, nie CNC.'},open:{label:'Moduły otwarte',hint:'Otwarte moduły górne i dolne bez frontu meblowego.'}}
};

export function getLibraryMessages(locale:Locale){return messages[locale];}
export function libraryGroup(locale:Locale,group:string){return groups[locale][group]??{label:group,hint:''};}

export function localizePreset(locale:Locale,preset:QuoteModulePreset){
  if(locale==='ru')return{name:preset.name,description:preset.description};
  const m=messages[locale];const w=preset.widthMm;
  if(preset.group==='base-door')return{name:`${locale==='de'?'Unterschrank':locale==='cs'?'Spodní':locale==='pl'?'Dolna':'Base'} ${w} · ${preset.doors===1?m.door:`${preset.doors} ${m.doors}`}`,description:`${libraryGroup(locale,preset.group).label} ${w} ${m.mm} · ${preset.doors} ${m.doors} · ${preset.shelfCount} ${m.shelves}.`};
  if(preset.group==='base-drawer')return{name:`${locale==='de'?'Unterschrank':locale==='cs'?'Spodní':locale==='pl'?'Dolna':'Base'} ${w} · ${preset.drawers} ${m.drawers}`,description:`${w} ${m.mm} · ${preset.drawers} ${m.drawers}.`};
  if(preset.group==='sink')return{name:`${locale==='de'?'Spüle':locale==='cs'?'Dřez':locale==='pl'?'Zlew':'Sink'} ${w}`,description:`${w} ${m.mm} · ${m.withoutFront.replace('front','back panel')} · ${preset.doors} ${m.doors}.`};
  if(preset.group==='wall-door')return{name:`${locale==='de'?'Oberschrank':locale==='cs'?'Horní':locale==='pl'?'Górna':'Wall'} ${w}`,description:`${w} × ${preset.heightMm} × ${preset.depthMm} ${m.mm} · ${preset.shelfCount} ${m.shelves}.`};
  if(preset.group==='tall')return{name:`${locale==='de'?'Hochschrank':locale==='cs'?'Vysoká':locale==='pl'?'Słupek':'Tall'} ${w}`,description:`${w} × ${preset.heightMm} ${m.mm} · ${preset.shelfCount} ${m.shelves}.`};
  if(preset.group==='corner')return{name:`${locale==='de'?'Eckmodul':locale==='cs'?'Rohový modul':locale==='pl'?'Narożnik':'Corner'} ${w}`,description:`${w} ${m.mm} · ${m.visibleFront} ${preset.frontWidthMm??preset.widthMm} ${m.mm}.`};
  if(preset.group==='open')return{name:`${locale==='de'?'Offenes Modul':locale==='cs'?'Otevřený modul':locale==='pl'?'Moduł otwarty':'Open module'} ${w}`,description:`${w} ${m.mm} · ${preset.shelfCount} ${m.shelves} · ${m.withoutFront}.`};
  if(preset.moduleKey==='dishwasher')return{name:`${locale==='de'?'Geschirrspüler':locale==='cs'?'Myčka':locale==='pl'?'Zmywarka':'Dishwasher'} ${w}`,description:`${w} ${m.mm} · ${m.frontOnly}.`};
  if(preset.moduleKey==='b-oven')return{name:`${locale==='de'?'Backofen':locale==='cs'?'Trouba':locale==='pl'?'Piekarnik':'Oven'} ${w}`,description:`${w} ${m.mm} · ${m.ovenNiche}.`};
  if(preset.moduleKey==='t-oven')return{name:`${locale==='de'?'Hochschrank Backofen':locale==='cs'?'Vysoká trouba':locale==='pl'?'Słupek piekarnik':'Tall oven'} ${w}`,description:`${m.opening} ${preset.applianceOpeningHeightMm??600} ${m.mm}.`};
  if(preset.moduleKey==='t-fridge')return{name:`${locale==='de'?'Hochschrank Kühlschrank':locale==='cs'?'Vysoká lednice':locale==='pl'?'Słupek lodówka':'Tall fridge'} ${w}`,description:`${preset.doors} ${m.frontsHigh} · ${m.none} ${m.backPanel.toLowerCase()}.`};
  return{name:preset.name,description:preset.description};
}

export function presetFeature(locale:Locale,preset:QuoteModulePreset){const m=messages[locale];if(preset.group==='corner')return `${m.visibleFront} ${preset.frontWidthMm??preset.widthMm} ${m.mm}`;if(preset.moduleKey==='b-drawer')return `${preset.drawers} ${m.drawers}`;if(preset.moduleKey==='dishwasher')return m.frontOnly;if(preset.moduleKey==='b-oven')return m.ovenNiche;if(preset.moduleKey==='t-oven')return `${m.opening} ${preset.applianceOpeningHeightMm??600} ${m.mm}`;if(preset.moduleKey==='t-fridge')return `${preset.doors} ${m.frontsHigh}`;if(preset.moduleKey==='open')return `${preset.shelfCount} ${m.shelves} · ${m.withoutFront}`;return `${preset.doors} ${preset.doors===1?m.door:m.doors} · ${preset.shelfCount} ${m.shelves}`;}
