import type { Locale } from './i18n';

export type MeasurementMessages = {
  title:string; shortTitle:string; subtitle:string; backToProject:string; savedDraft:string; savedComplete:string; requiredError:string; saveError:string;
  projectStep:string; measurementsStep:string; modulesStep:string; materialsStep:string; costStep:string; priceStep:string; proposalStep:string;
  complete:string; inProgress:string; notStarted:string;
  basics:string; basicsHelp:string; measuredAt:string; measuredBy:string; siteAddress:string; roomShape:string; shapeStraight:string; shapeL:string; shapeU:string; shapeIsland:string; shapeOther:string;
  geometry:string; geometryHelp:string; roomHeight:string; wallA:string; wallB:string; wallC:string; wallD:string; millimeters:string;
  openings:string; openingsHelp:string; niches:string; windows:string; doors:string;
  utilities:string; utilitiesHelp:string; plumbing:string; gas:string; ventilation:string; electrical:string;
  appliances:string; appliancesHelp:string; applianceNotes:string; conditions:string; conditionsHelp:string; floorWalls:string; notes:string;
  photos:string; photosHelp:string; photosComing:string; draft:string; saveDraft:string; saveComplete:string; completeRequirements:string;
  sourceStandard:string; sourceMeasurement:string; sourceManual:string;
};

const messages: Record<Locale, MeasurementMessages> = {
  ru:{title:'Замеры',shortTitle:'Замеры',subtitle:'Зафиксируйте фактическую геометрию помещения до сборки модулей.',backToProject:'← Проект',savedDraft:'Черновик замеров сохранён.',savedComplete:'Замеры отмечены как завершённые.',requiredError:'Чтобы завершить замер, заполните дату, адрес объекта, высоту помещения и стену A.',saveError:'Не удалось сохранить замеры.',projectStep:'Проект',measurementsStep:'Замеры',modulesStep:'Модули',materialsStep:'Материалы',costStep:'Себестоимость',priceStep:'Цена',proposalStep:'Предложение',complete:'Готово',inProgress:'В работе',notStarted:'Не начато',basics:'Объект и замер',basicsHelp:'Кто, когда и где выполнил замер.',measuredAt:'Дата замера',measuredBy:'Кто замерял',siteAddress:'Адрес объекта',roomShape:'Форма помещения',shapeStraight:'Прямая',shapeL:'L-образная',shapeU:'U-образная',shapeIsland:'С островом',shapeOther:'Другая',geometry:'Геометрия помещения',geometryHelp:'Введите чистовые размеры в миллиметрах. Для простой кухни достаточно стены A и высоты помещения.',roomHeight:'Высота помещения',wallA:'Стена A',wallB:'Стена B',wallC:'Стена C',wallD:'Стена D',millimeters:'мм',openings:'Ниши и проёмы',openingsHelp:'Фиксируйте размеры и привязки от углов помещения.',niches:'Ниши / выступы / колонны',windows:'Окна / подоконники',doors:'Двери / проёмы',utilities:'Коммуникации',utilitiesHelp:'Запишите положение точек и высоты от чистового пола.',plumbing:'Вода / канализация',gas:'Газ',ventilation:'Вентиляция / вытяжка',electrical:'Электрика / розетки',appliances:'Техника',appliancesHelp:'Укажите встроенную и отдельно стоящую технику, модель или монтажный размер, если известен.',applianceNotes:'Техника и монтажные размеры',conditions:'Состояние помещения',conditionsHelp:'То, что может повлиять на монтаж, зазоры и доборы.',floorWalls:'Кривизна стен / пола / углы',notes:'Общие примечания',photos:'Фото объекта',photosHelp:'Фотографии должны быть привязаны к этому замеру и сохраняться вместе с проектом.',photosComing:'Структура для фотографий уже создана. Загрузку файлов подключаем следующим подпунктом Phase 1.',draft:'Черновик',saveDraft:'Сохранить черновик',saveComplete:'Сохранить и завершить замер',completeRequirements:'Для статуса «Готово» обязательны: дата, адрес, высота помещения и стена A.',sourceStandard:'Стандарт Makster',sourceMeasurement:'Из замеров',sourceManual:'Изменено вручную'},
  en:{title:'Measurements',shortTitle:'Measurements',subtitle:'Record the real room geometry before assembling furniture modules.',backToProject:'← Project',savedDraft:'Measurement draft saved.',savedComplete:'Measurements marked complete.',requiredError:'To complete measurements, fill in date, site address, room height and Wall A.',saveError:'Could not save measurements.',projectStep:'Project',measurementsStep:'Measurements',modulesStep:'Modules',materialsStep:'Materials',costStep:'True cost',priceStep:'Price',proposalStep:'Proposal',complete:'Ready',inProgress:'In progress',notStarted:'Not started',basics:'Site & visit',basicsHelp:'Who measured, when, and where.',measuredAt:'Measurement date',measuredBy:'Measured by',siteAddress:'Site address',roomShape:'Room shape',shapeStraight:'Straight',shapeL:'L-shaped',shapeU:'U-shaped',shapeIsland:'With island',shapeOther:'Other',geometry:'Room geometry',geometryHelp:'Enter finished dimensions in millimetres. For a simple kitchen Wall A and room height are enough.',roomHeight:'Room height',wallA:'Wall A',wallB:'Wall B',wallC:'Wall C',wallD:'Wall D',millimeters:'mm',openings:'Niches & openings',openingsHelp:'Record dimensions and offsets from room corners.',niches:'Niches / projections / columns',windows:'Windows / sills',doors:'Doors / openings',utilities:'Utilities',utilitiesHelp:'Record connection positions and heights from finished floor.',plumbing:'Water / drainage',gas:'Gas',ventilation:'Ventilation / hood',electrical:'Electrical / sockets',appliances:'Appliances',appliancesHelp:'List built-in and freestanding appliances and installation dimensions when known.',applianceNotes:'Appliances & installation dimensions',conditions:'Room condition',conditionsHelp:'Anything that may affect installation, gaps or fillers.',floorWalls:'Wall / floor unevenness / angles',notes:'General notes',photos:'Site photos',photosHelp:'Photos belong to this measurement record and project.',photosComing:'Photo metadata is ready. File upload is the next Phase 1 sub-step.',draft:'Draft',saveDraft:'Save draft',saveComplete:'Save & complete measurements',completeRequirements:'Ready status requires date, address, room height and Wall A.',sourceStandard:'Makster standard',sourceMeasurement:'From measurements',sourceManual:'Edited manually'},
  cs:{title:'Zaměření',shortTitle:'Zaměření',subtitle:'Před sestavením modulů zaznamenejte skutečnou geometrii prostoru.',backToProject:'← Projekt',savedDraft:'Koncept zaměření byl uložen.',savedComplete:'Zaměření je označeno jako dokončené.',requiredError:'Pro dokončení vyplňte datum, adresu, výšku místnosti a stěnu A.',saveError:'Zaměření se nepodařilo uložit.',projectStep:'Projekt',measurementsStep:'Zaměření',modulesStep:'Moduly',materialsStep:'Materiály',costStep:'Náklady',priceStep:'Cena',proposalStep:'Nabídka',complete:'Hotovo',inProgress:'Rozpracováno',notStarted:'Nezahájeno',basics:'Objekt a zaměření',basicsHelp:'Kdo, kdy a kde zaměřoval.',measuredAt:'Datum zaměření',measuredBy:'Zaměřil',siteAddress:'Adresa objektu',roomShape:'Tvar místnosti',shapeStraight:'Rovná',shapeL:'Do L',shapeU:'Do U',shapeIsland:'S ostrůvkem',shapeOther:'Jiná',geometry:'Geometrie místnosti',geometryHelp:'Zadejte hotové rozměry v milimetrech. Pro jednoduchou kuchyň stačí stěna A a výška.',roomHeight:'Výška místnosti',wallA:'Stěna A',wallB:'Stěna B',wallC:'Stěna C',wallD:'Stěna D',millimeters:'mm',openings:'Nik y a otvory',openingsHelp:'Uveďte rozměry a vzdálenosti od rohů.',niches:'Nik y / výstupky / sloupy',windows:'Okna / parapety',doors:'Dveře / otvory',utilities:'Přípojky',utilitiesHelp:'Zapište polohu a výšku od hotové podlahy.',plumbing:'Voda / odpad',gas:'Plyn',ventilation:'Větrání / digestoř',electrical:'Elektro / zásuvky',appliances:'Spotřebiče',appliancesHelp:'Uveďte vestavné i volně stojící spotřebiče a montážní rozměry.',applianceNotes:'Spotřebiče a montážní rozměry',conditions:'Stav místnosti',conditionsHelp:'Vše, co může ovlivnit montáž, mezery nebo výplně.',floorWalls:'Nerovnosti stěn / podlahy / úhly',notes:'Obecné poznámky',photos:'Fotografie objektu',photosHelp:'Fotografie patří k tomuto zaměření a projektu.',photosComing:'Datová struktura fotografií je připravena. Nahrávání souborů je další krok fáze 1.',draft:'Koncept',saveDraft:'Uložit koncept',saveComplete:'Uložit a dokončit zaměření',completeRequirements:'Stav Hotovo vyžaduje datum, adresu, výšku místnosti a stěnu A.',sourceStandard:'Standard Makster',sourceMeasurement:'Ze zaměření',sourceManual:'Ručně změněno'},
  de:{title:'Aufmaß',shortTitle:'Aufmaß',subtitle:'Erfassen Sie die reale Raumgeometrie, bevor Möbelmodule zusammengestellt werden.',backToProject:'← Projekt',savedDraft:'Aufmaß-Entwurf gespeichert.',savedComplete:'Aufmaß als abgeschlossen markiert.',requiredError:'Für den Abschluss Datum, Objektadresse, Raumhöhe und Wand A ausfüllen.',saveError:'Aufmaß konnte nicht gespeichert werden.',projectStep:'Projekt',measurementsStep:'Aufmaß',modulesStep:'Module',materialsStep:'Materialien',costStep:'Kosten',priceStep:'Preis',proposalStep:'Angebot',complete:'Fertig',inProgress:'In Arbeit',notStarted:'Nicht begonnen',basics:'Objekt & Aufmaß',basicsHelp:'Wer hat wann und wo gemessen.',measuredAt:'Aufmaßdatum',measuredBy:'Gemessen von',siteAddress:'Objektadresse',roomShape:'Raumform',shapeStraight:'Gerade',shapeL:'L-Form',shapeU:'U-Form',shapeIsland:'Mit Insel',shapeOther:'Andere',geometry:'Raumgeometrie',geometryHelp:'Fertigmaße in Millimetern eingeben. Für eine einfache Küche reichen Wand A und Raumhöhe.',roomHeight:'Raumhöhe',wallA:'Wand A',wallB:'Wand B',wallC:'Wand C',wallD:'Wand D',millimeters:'mm',openings:'Nischen & Öffnungen',openingsHelp:'Maße und Abstände von den Raumecken erfassen.',niches:'Nischen / Vorsprünge / Säulen',windows:'Fenster / Fensterbänke',doors:'Türen / Öffnungen',utilities:'Anschlüsse',utilitiesHelp:'Positionen und Höhen ab Fertigfußboden notieren.',plumbing:'Wasser / Abfluss',gas:'Gas',ventilation:'Lüftung / Haube',electrical:'Elektro / Steckdosen',appliances:'Geräte',appliancesHelp:'Einbau- und Standgeräte sowie Einbaumaße erfassen.',applianceNotes:'Geräte und Einbaumaße',conditions:'Raumzustand',conditionsHelp:'Alles, was Montage, Fugen oder Blenden beeinflussen kann.',floorWalls:'Unebenheiten Wände / Boden / Winkel',notes:'Allgemeine Hinweise',photos:'Objektfotos',photosHelp:'Fotos gehören zu diesem Aufmaß und Projekt.',photosComing:'Die Fotodatenstruktur ist vorbereitet. Datei-Upload folgt im nächsten Teil von Phase 1.',draft:'Entwurf',saveDraft:'Entwurf speichern',saveComplete:'Speichern & Aufmaß abschließen',completeRequirements:'Fertig erfordert Datum, Adresse, Raumhöhe und Wand A.',sourceStandard:'Makster-Standard',sourceMeasurement:'Aus Aufmaß',sourceManual:'Manuell geändert'},
  pl:{title:'Pomiary',shortTitle:'Pomiary',subtitle:'Zapisz rzeczywistą geometrię pomieszczenia przed budowaniem modułów.',backToProject:'← Projekt',savedDraft:'Szkic pomiarów zapisany.',savedComplete:'Pomiary oznaczono jako zakończone.',requiredError:'Aby zakończyć pomiary, podaj datę, adres, wysokość pomieszczenia i ścianę A.',saveError:'Nie udało się zapisać pomiarów.',projectStep:'Projekt',measurementsStep:'Pomiary',modulesStep:'Moduły',materialsStep:'Materiały',costStep:'Koszt',priceStep:'Cena',proposalStep:'Oferta',complete:'Gotowe',inProgress:'W toku',notStarted:'Nie rozpoczęto',basics:'Obiekt i pomiar',basicsHelp:'Kto, kiedy i gdzie wykonał pomiar.',measuredAt:'Data pomiaru',measuredBy:'Mierzył',siteAddress:'Adres obiektu',roomShape:'Kształt pomieszczenia',shapeStraight:'Prosta',shapeL:'L',shapeU:'U',shapeIsland:'Z wyspą',shapeOther:'Inny',geometry:'Geometria pomieszczenia',geometryHelp:'Wprowadź wymiary wykończone w milimetrach. Dla prostej kuchni wystarczy ściana A i wysokość.',roomHeight:'Wysokość pomieszczenia',wallA:'Ściana A',wallB:'Ściana B',wallC:'Ściana C',wallD:'Ściana D',millimeters:'mm',openings:'Wnęki i otwory',openingsHelp:'Zapisz wymiary i odległości od narożników.',niches:'Wnęki / występy / słupy',windows:'Okna / parapety',doors:'Drzwi / otwory',utilities:'Instalacje',utilitiesHelp:'Zapisz położenie punktów i wysokości od gotowej podłogi.',plumbing:'Woda / odpływ',gas:'Gaz',ventilation:'Wentylacja / okap',electrical:'Elektryka / gniazda',appliances:'Sprzęt AGD',appliancesHelp:'Podaj sprzęt do zabudowy i wolnostojący oraz wymiary montażowe.',applianceNotes:'AGD i wymiary montażowe',conditions:'Stan pomieszczenia',conditionsHelp:'Wszystko, co może wpłynąć na montaż, szczeliny lub blendy.',floorWalls:'Nierówności ścian / podłogi / kąty',notes:'Uwagi ogólne',photos:'Zdjęcia obiektu',photosHelp:'Zdjęcia należą do tego pomiaru i projektu.',photosComing:'Struktura danych zdjęć jest gotowa. Wgrywanie plików to kolejny krok fazy 1.',draft:'Szkic',saveDraft:'Zapisz szkic',saveComplete:'Zapisz i zakończ pomiary',completeRequirements:'Status Gotowe wymaga daty, adresu, wysokości pomieszczenia i ściany A.',sourceStandard:'Standard Makster',sourceMeasurement:'Z pomiarów',sourceManual:'Zmieniono ręcznie'}
};

export function getMeasurementMessages(locale: Locale) {
  return messages[locale];
}
