import type { Locale } from './i18n';

export type Phase1Messages = {
  upload:string; uploadHint:string; uploading:string; uploadFailed:string; invalidPhoto:string; remove:string; noPhotos:string; photos:string;
  dimensionSource:string; sourceHelp:string; measurementReference:string; referencePlaceholder:string;
  refWallA:string; refWallB:string; refWallC:string; refWallD:string; refNiche:string; refWindow:string; refDoor:string; refAppliance:string;
  nextAction:string; nextMeasurements:string; nextModules:string; nextMaterials:string; nextPrice:string; nextProposal:string; ready:string; modulesIncomplete:string;
};

const ru:Phase1Messages={upload:'Добавить фотографии',uploadHint:'JPG, PNG, WEBP, HEIC · до 10 МБ на фото',uploading:'Загрузка…',uploadFailed:'Не удалось загрузить фотографию.',invalidPhoto:'Поддерживаются фотографии до 10 МБ.',remove:'Удалить',noPhotos:'Фотографий пока нет.',photos:'Фото',dimensionSource:'Источник размеров',sourceHelp:'Показывает, откуда взяты размеры модуля.',measurementReference:'Привязка к замеру',referencePlaceholder:'Например: Стена A / ниша 1',refWallA:'Стена A',refWallB:'Стена B',refWallC:'Стена C',refWallD:'Стена D',refNiche:'Ниша / выступ',refWindow:'Окно / подоконник',refDoor:'Дверь / проём',refAppliance:'Техника',nextAction:'Следующий шаг',nextMeasurements:'Завершите замеры объекта.',nextModules:'Добавьте первый мебельный модуль.',nextMaterials:'Заполните материалы и фурнитуру для всех модулей.',nextPrice:'Сохраните коммерческую цену и параметры предложения.',nextProposal:'Сформируйте и выпустите предложение клиенту.',ready:'Проект готов по текущему рабочему маршруту.',modulesIncomplete:'Модулей с неполным расчётом'};
const en:Phase1Messages={upload:'Add photos',uploadHint:'JPG, PNG, WEBP, HEIC · up to 10 MB per photo',uploading:'Uploading…',uploadFailed:'Photo upload failed.',invalidPhoto:'Supported photos up to 10 MB only.',remove:'Remove',noPhotos:'No photos yet.',photos:'Photos',dimensionSource:'Dimension source',sourceHelp:'Shows where the module dimensions came from.',measurementReference:'Measurement reference',referencePlaceholder:'For example: Wall A / niche 1',refWallA:'Wall A',refWallB:'Wall B',refWallC:'Wall C',refWallD:'Wall D',refNiche:'Niche / projection',refWindow:'Window / sill',refDoor:'Door / opening',refAppliance:'Appliance',nextAction:'Next action',nextMeasurements:'Complete the site measurements.',nextModules:'Add the first furniture module.',nextMaterials:'Complete materials and hardware for every module.',nextPrice:'Save commercial price and quote parameters.',nextProposal:'Create and issue the customer proposal.',ready:'The project is ready on the current workflow.',modulesIncomplete:'Modules with incomplete costing'};
const cs:Phase1Messages={...en,upload:'Přidat fotografie',uploadHint:'JPG, PNG, WEBP, HEIC · max. 10 MB na fotografii',uploading:'Nahrávání…',uploadFailed:'Fotografii se nepodařilo nahrát.',invalidPhoto:'Podporovány jsou fotografie do 10 MB.',remove:'Odstranit',noPhotos:'Zatím žádné fotografie.',photos:'Fotografie',dimensionSource:'Zdroj rozměrů',sourceHelp:'Ukazuje, odkud pochází rozměry modulu.',measurementReference:'Vazba na zaměření',referencePlaceholder:'Například: Stěna A / nika 1',refWallA:'Stěna A',refWallB:'Stěna B',refWallC:'Stěna C',refWallD:'Stěna D',nextAction:'Další krok',nextMeasurements:'Dokončete zaměření objektu.',nextModules:'Přidejte první nábytkový modul.',nextMaterials:'Doplňte materiály a kování u všech modulů.',nextPrice:'Uložte obchodní cenu a parametry nabídky.',nextProposal:'Vytvořte a vydejte nabídku zákazníkovi.',ready:'Projekt je připraven.',modulesIncomplete:'Moduly s neúplnou kalkulací'};
const de:Phase1Messages={...en,upload:'Fotos hinzufügen',uploadHint:'JPG, PNG, WEBP, HEIC · bis 10 MB pro Foto',uploading:'Wird hochgeladen…',uploadFailed:'Foto konnte nicht hochgeladen werden.',invalidPhoto:'Nur Fotos bis 10 MB sind erlaubt.',remove:'Entfernen',noPhotos:'Noch keine Fotos.',photos:'Fotos',dimensionSource:'Maßquelle',sourceHelp:'Zeigt, woher die Modulmaße stammen.',measurementReference:'Aufmaß-Referenz',referencePlaceholder:'Zum Beispiel: Wand A / Nische 1',refWallA:'Wand A',refWallB:'Wand B',refWallC:'Wand C',refWallD:'Wand D',nextAction:'Nächster Schritt',nextMeasurements:'Schließen Sie das Aufmaß ab.',nextModules:'Fügen Sie das erste Möbelmodul hinzu.',nextMaterials:'Vervollständigen Sie Materialien und Beschläge.',nextPrice:'Speichern Sie Preis und Angebotsparameter.',nextProposal:'Erstellen und veröffentlichen Sie das Angebot.',ready:'Das Projekt ist bereit.',modulesIncomplete:'Module mit unvollständiger Kalkulation'};
const pl:Phase1Messages={...en,upload:'Dodaj zdjęcia',uploadHint:'JPG, PNG, WEBP, HEIC · do 10 MB na zdjęcie',uploading:'Przesyłanie…',uploadFailed:'Nie udało się przesłać zdjęcia.',invalidPhoto:'Obsługiwane są zdjęcia do 10 MB.',remove:'Usuń',noPhotos:'Brak zdjęć.',photos:'Zdjęcia',dimensionSource:'Źródło wymiarów',sourceHelp:'Pokazuje źródło wymiarów modułu.',measurementReference:'Powiązanie z pomiarem',referencePlaceholder:'Na przykład: Ściana A / wnęka 1',refWallA:'Ściana A',refWallB:'Ściana B',refWallC:'Ściana C',refWallD:'Ściana D',nextAction:'Następny krok',nextMeasurements:'Zakończ pomiary obiektu.',nextModules:'Dodaj pierwszy moduł meblowy.',nextMaterials:'Uzupełnij materiały i okucia.',nextPrice:'Zapisz cenę i parametry oferty.',nextProposal:'Utwórz i opublikuj ofertę.',ready:'Projekt jest gotowy.',modulesIncomplete:'Moduły z niepełną kalkulacją'};

const messages:Record<Locale,Phase1Messages>={ru,en,cs,de,pl};
export function getPhase1Messages(locale:Locale){return messages[locale]??en;}
