import { calculateQuoteCabinetPreview } from './cabinet-overrides';
import { costPreviewToJson, type ModuleKey, type PriceBookItem } from './engineering';

export type PlannerModule={id:string;kind:string;widthMm:number;libraryModuleCode?:string;libraryTemplateCode?:string;libraryVersion?:number};
export type PlannerContract={contract:string;version:string;handoffId?:string;source?:{projectId?:string};tenant?:{organizationId?:string;deploymentId?:string};project?:{id?:string;name?:string;payload?:Record<string,any>};commercial?:{currency?:string;clientVisibleTotalGross?:number;pricing?:Record<string,any>};lead?:{contact?:{name?:string;email?:string;phone?:string}};manufacturing?:{runs?:Record<string,PlannerModule[]>;materials?:Record<string,unknown>;appliances?:Record<string,unknown>};intake?:{stage?:string};sync?:{mode?:'CREATE'|'UPDATE';sourceHash?:string;previousHandoffId?:string|null;consumerRef?:string|null;syncCount?:number}};

function safeBps(value:unknown,fallback:number,max=9500){const n=Number(value);return Number.isFinite(n)?Math.max(0,Math.min(max,Math.round(n))):fallback;}
function moduleKey(kind:string):ModuleKey{if(kind==='drawer')return'b-drawer';if(kind==='oven')return'b-oven';if(kind==='dishwasher')return'dishwasher';if(kind==='wall')return'w-door';if(kind==='tall')return't-door';if(kind==='door'||kind==='sink'||kind==='hob')return'b-door';return'generic';}
function moduleName(kind:string,code?:string){const labels:Record<string,string>={door:'Нижний шкаф',drawer:'Нижний шкаф с ящиками',sink:'Тумба под мойку',hob:'Тумба под варочную',oven:'Тумба под духовку',dishwasher:'ПММ',wall:'Верхний шкаф',tall:'Пенал',corner_blind:'Угловой глухой',corner_l:'Угловой L'};return `${labels[kind]??'Модуль'}${code?` · ${code}`:''}`;}
function standardGeometry(kind:string){if(kind==='wall')return{heightMm:720,depthMm:350};if(kind==='tall')return{heightMm:2100,depthMm:560};return{heightMm:720,depthMm:560};}
function roomShape(layout:unknown){const v=String(layout??'').toLowerCase();if(v.includes('island'))return'island';if(v.startsWith('u'))return'u';if(v.startsWith('l'))return'l';if(v.includes('straight'))return'straight';return'other';}
function defaultShelfCount(key:ModuleKey){if(key==='b-door')return 1;if(key==='w-door'||key==='open')return 2;if(key==='t-door')return 4;if(key==='t-oven')return 2;if(key==='t-fridge')return 1;return 0;}

export function plannerProjectSettings(contract:PlannerContract,handoff:{id:string;deployment_id?:string|null}){return{source:'DREAM_PLANNER',sourceProjectId:contract.source?.projectId??contract.project?.id,plannerHandoffId:handoff.id,plannerDeploymentId:handoff.deployment_id,intakeStage:'ESTIMATE_REVIEW',workflow:{measurementsProvided:true,modulesProvided:true,visualizationProvided:true},plannerSync:{mode:contract.sync?.mode??'CREATE',sourceHash:contract.sync?.sourceHash??null,syncCount:Number(contract.sync?.syncCount??1),syncedAt:new Date().toISOString()},preliminaryPrice:{status:'PRELIMINARY',currency:contract.commercial?.currency??'EUR',gross:contract.commercial?.clientVisibleTotalGross??0,priceBookRevision:contract.commercial?.pricing?.priceBookRevision??null}};}

export function plannerMeasurementPayload(organizationId:string,projectId:string,contract:PlannerContract){const payload=contract.project?.payload??{};const roomFeatures=Array.isArray(payload.roomFeatures)?payload.roomFeatures:[];const featureText=(kind:string)=>roomFeatures.filter((x:any)=>String(x?.kind??'').toLowerCase().includes(kind)).map((x:any)=>`${x.wall??''} ${x.offsetMm??''} ${x.widthMm??''}x${x.heightMm??''}`.trim()).join('; ')||null;return{organization_id:organizationId,project_id:projectId,room_shape:roomShape(payload.layout),room_height_mm:Number(payload.roomHeightMm)||null,wall_a_mm:Number(payload.lengthMm)||null,wall_b_mm:Number(payload.returnLengthMm)||null,windows_text:featureText('window'),doors_text:featureText('door'),plumbing_text:featureText('plumb'),electrical_text:featureText('electric'),appliances_text:JSON.stringify(contract.manufacturing?.appliances??{}),floor_walls_text:JSON.stringify(contract.manufacturing?.materials??{}),notes:'Imported from Dream Planner. Commercial intake is complete; verify site dimensions before manufacturing release.',status:'complete'};}

export async function buildPlannerCabinetRows(admin:any,organizationId:string,projectId:string,revisionId:string,contract:PlannerContract){const runs=contract.manufacturing?.runs??{};const modules=Object.entries(runs).flatMap(([runId,list])=>(Array.isArray(list)?list:[]).map((module,index)=>({runId,index,module})));
 const codes=[...new Set(modules.map(x=>x.module.libraryModuleCode).filter(Boolean))] as string[];const libraryByCode=new Map<string,any>();
 if(codes.length){const {data:libRows,error}=await admin.from('library_modules').select('module_code,display_name,active_version_id').in('module_code',codes);if(error)throw error;const versionIds=(libRows??[]).map((x:any)=>x.active_version_id).filter(Boolean);const versionResult=versionIds.length?await admin.from('library_module_versions').select('id,version,width_mm,depth_mm,body_height_mm,leg_height_mm,library_status,release_status').in('id',versionIds):{data:[],error:null};if(versionResult.error)throw versionResult.error;const versionMap=new Map((versionResult.data??[]).map((v:any)=>[v.id,v]));for(const row of libRows??[])libraryByCode.set(row.module_code,{...row,version:versionMap.get(row.active_version_id)});}
 const [{data:org,error:orgError},{data:priceRows,error:priceError}]=await Promise.all([admin.from('organizations').select('settings').eq('id',organizationId).single(),admin.from('quote_price_book_items').select('id,category,name,unit,currency,purchase_price_minor,parameters_json').eq('organization_id',organizationId).eq('active',true)]);if(orgError||priceError)throw orgError||priceError;
 const currency=contract.commercial?.currency??'EUR';const priceBook=(priceRows??[]).filter((x:any)=>x.currency===currency) as PriceBookItem[];const quoteSettings=((org?.settings as any)?.quote??{}) as Record<string,any>;const ids=(quoteSettings.priceBookDefaults??{}) as Record<string,string>;const targetMarginBps=safeBps(quoteSettings.targetMarginBps,3500);const overheadBps=safeBps(quoteSettings.overheadBps,0);
 return modules.map(({runId,index,module},sortIndex)=>{const key=moduleKey(module.kind);const lib=module.libraryModuleCode?libraryByCode.get(module.libraryModuleCode):null;const v=lib?.version;const ready=Boolean(v&&v.library_status==='READY'&&Number(v.width_mm)>0&&Number(v.depth_mm)>0&&Number(v.body_height_mm)>0);const fallback=standardGeometry(module.kind);const heightMm=ready?Number(v.body_height_mm)+Number(v.leg_height_mm||0):fallback.heightMm;const depthMm=ready?Number(v.depth_mm):fallback.depthMm;const widthMm=ready?Number(v.width_mm):Number(module.widthMm)||600;const input={moduleKey:key,widthMm,heightMm,depthMm,thicknessMm:18,gapMm:2,drawers:key==='b-drawer'?3:0,doors:key==='t-door'?2:1,shelfCount:defaultShelfCount(key),stretcherDepthMm:100,shelfSetbackMm:20,applianceOpeningHeightMm:600,backMode:'groove' as const,backThicknessMm:4,backInsetMm:10,backGrooveDepthMm:8,frontEdgeIncluded:true,boardItemId:ids.boardItemId,frontItemId:ids.frontItemId,backItemId:ids.backItemId,edgeItemId:ids.edgeItemId,hingeItemId:ids.hingeItemId,drawerItemId:ids.drawerItemId,labourItemId:ids.labourItemId,labourHours:0};const preview=calculateQuoteCabinetPreview(input,priceBook,{targetMarginBps,overheadBps,taxBps:0});const cost=costPreviewToJson(preview) as Record<string,any>;if(!ready){cost.complete=false;cost.warnings=[...((cost.warnings as string[]|undefined)??[]),'Planner module has no READY library geometry; verify height/depth before final quote.'];}return{organization_id:organizationId,project_id:projectId,project_revision_id:revisionId,module_key:key,name:moduleName(module.kind,module.libraryModuleCode),sort_order:sortIndex*10,width_mm:widthMm,height_mm:heightMm,depth_mm:depthMm,quantity:1,dimension_source:'planner',measurement_reference:`Dream Planner ${runId} · ${module.id}`,construction_json:{...input,planner:{runId,index,sourceModuleId:module.id,libraryModuleCode:module.libraryModuleCode??null,libraryTemplateCode:module.libraryTemplateCode??null,libraryVersion:module.libraryVersion??null,geometryStatus:ready?'READY':'REVIEW'}},material_refs_json:{plannerMaterials:contract.manufacturing?.materials??{},boardItemId:ids.boardItemId??null,frontItemId:ids.frontItemId??null,backItemId:ids.backItemId??null,edgeItemId:ids.edgeItemId??null,labourItemId:ids.labourItemId??null},hardware_refs_json:{hingeItemId:ids.hingeItemId??null,drawerItemId:ids.drawerItemId??null},computed_parts_json:{usage:preview.usage,parts:preview.parts,hardware:preview.hardware.map(x=>({...x,costMinor:x.costMinor.toString()})),operations:preview.operations.map(x=>({...x,costMinor:x.costMinor.toString()})),notes:preview.notes},computed_cost_json:cost,engine_version:'mq-planner-import-0.2'};});
}
