import { QUOTE_MODULE_PRESETS, type QuoteModulePreset } from './module-presets';

export type SpecialHardwareRole = 'cargo' | 'lift' | 'corner' | 'rail' | 'sliding';
export type SpecialHardwarePreset = QuoteModulePreset & {
  specialHardwareRole: SpecialHardwareRole;
  specialHardwareQty: number;
};

const common={thicknessMm:18,gapMm:2,stretcherDepthMm:100,shelfSetbackMm:20,backThicknessMm:4,backInsetMm:10,backGrooveDepthMm:8,frontEdgeIncluded:true} as const;
const base={...common,family:'kitchen' as const,heightMm:720,depthMm:560} as const;
const wall={...common,family:'kitchen' as const,heightMm:720,depthMm:350,stretcherDepthMm:80,shelfSetbackMm:15} as const;
const wardrobe={...common,family:'wardrobe' as const,heightMm:2400,depthMm:600,shelfSetbackMm:20} as const;

function cargo(widthMm:number):SpecialHardwarePreset{return{...base,key:`cargo-${widthMm}`,group:'base-door',name:`Карго ${widthMm}`,description:`Нижний выдвижной модуль ${widthMm} мм под бутылочницу / cargo. Механизм считается отдельной специальной фурнитурой.`,moduleKey:'b-door',widthMm,drawers:0,doors:1,shelfCount:0,backMode:'groove',specialHardwareRole:'cargo',specialHardwareQty:1,translations:{en:{name:`Cargo pull-out ${widthMm}`,description:`Base pull-out ${widthMm} mm for a bottle/cargo mechanism. The mechanism is costed as special hardware.`},cs:{name:`Cargo výsuv ${widthMm}`,description:`Spodní výsuvný modul ${widthMm} mm pro cargo mechanismus. Mechanismus se počítá jako speciální kování.`},de:{name:`Cargo-Auszug ${widthMm}`,description:`Ausziehbarer Unterschrank ${widthMm} mm für Cargo-/Flaschenauszug. Der Beschlag wird separat kalkuliert.`},pl:{name:`Cargo ${widthMm}`,description:`Dolny wysuwany moduł ${widthMm} mm pod cargo. Mechanizm jest liczony jako specjalne okucie.`}}};}
function lift(widthMm:number,heightMm=720):SpecialHardwarePreset{return{...wall,key:`lift-wall-${widthMm}-${heightMm}`,group:'wall-door',name:`Верхний Lift-Up ${widthMm} × ${heightMm}`,description:`Навесной шкаф с подъёмным фасадом. Подъёмник типа Aventos считается отдельной специальной фурнитурой.`,moduleKey:'w-door',widthMm,heightMm,drawers:0,doors:1,shelfCount:heightMm>=720?2:1,backMode:'groove',specialHardwareRole:'lift',specialHardwareQty:1,translations:{en:{name:`Lift-up wall ${widthMm} × ${heightMm}`,description:'Wall cabinet with lift-up front. Aventos-type lift mechanism is costed as special hardware.'},cs:{name:`Horní Lift-Up ${widthMm} × ${heightMm}`,description:'Horní skříňka s výklopným čelem. Mechanismus typu Aventos se počítá jako speciální kování.'},de:{name:`Lift-Up Oberschrank ${widthMm} × ${heightMm}`,description:'Oberschrank mit Klappenfront. Aventos-artiger Klappenbeschlag wird separat kalkuliert.'},pl:{name:`Górna Lift-Up ${widthMm} × ${heightMm}`,description:'Szafka górna z frontem podnoszonym. Mechanizm typu Aventos jest liczony jako specjalne okucie.'}}};}
function cornerMechanism(key:string,name:string,widthMm:number,frontWidthMm:number):SpecialHardwarePreset{return{...base,key,group:'corner',name,description:`Угловой нижний модуль ${widthMm} мм со специальным механизмом. Механизм считается отдельной фурнитурой; точная присадка остаётся в Makster Pro.`,moduleKey:'b-door',widthMm,frontWidthMm,drawers:0,doors:1,shelfCount:1,backMode:'groove',specialHardwareRole:'corner',specialHardwareQty:1,translations:{en:{name,description:`${widthMm} mm base corner cabinet with a special corner mechanism. Hardware is costed separately; exact drilling stays in Makster Pro.`},cs:{name,description:`Rohová spodní skříň ${widthMm} mm se speciálním rohovým mechanismem. Kování se počítá samostatně.`},de:{name,description:`${widthMm}-mm-Eckunterschrank mit speziellem Eckmechanismus. Beschlag wird separat kalkuliert.`},pl:{name,description:`Dolny narożnik ${widthMm} mm ze specjalnym mechanizmem narożnym. Okucie jest liczone osobno.`}}};}
function wardrobeRail(key:string,name:string,widthMm:number,shelfCount:number,railQty:number,translations:NonNullable<QuoteModulePreset['translations']>):SpecialHardwarePreset{return{...wardrobe,key,group:'wardrobe-hinged',name,description:`Гардеробная секция ${widthMm} мм со штангой. Штанга и крепления считаются отдельной позицией фурнитуры.`,moduleKey:'t-door',widthMm,drawers:0,doors:widthMm>=900?2:1,shelfCount,backMode:'groove',specialHardwareRole:'rail',specialHardwareQty:railQty,translations};}
function wardrobeSliding(widthMm:number,doors:number):SpecialHardwarePreset{return{...wardrobe,key:`wardrobe-sliding-${widthMm}-${doors}`,group:'wardrobe-hinged',name:`Гардероб раздвижной ${widthMm} · ${doors} фасада`,description:`Шкаф ${widthMm} мм с раздвижными фасадами. Комплект направляющих и роликов считается отдельной специальной фурнитурой.`,moduleKey:'t-door',widthMm,drawers:0,doors,shelfCount:4,backMode:'groove',specialHardwareRole:'sliding',specialHardwareQty:1,translations:{en:{name:`Sliding wardrobe ${widthMm} · ${doors} fronts`,description:'Wardrobe with sliding fronts. Track and roller set is costed as special hardware.'},cs:{name:`Posuvná skříň ${widthMm} · ${doors} čela`,description:'Skříň s posuvnými čely. Sada kolejnic a pojezdů se počítá jako speciální kování.'},de:{name:`Schiebetürenschrank ${widthMm} · ${doors} Fronten`,description:'Schrank mit Schiebefronten. Schienen- und Rollensatz wird als Spezialbeschlag kalkuliert.'},pl:{name:`Szafa przesuwna ${widthMm} · ${doors} fronty`,description:'Szafa z frontami przesuwnymi. Zestaw prowadnic i rolek jest liczony jako okucie specjalne.'}}};}

export const SPECIAL_HARDWARE_PRESETS:SpecialHardwarePreset[]=[
  cargo(150),cargo(200),cargo(300),
  lift(600,360),lift(600,720),lift(800,720),lift(900,720),
  cornerMechanism('corner-lemans-900','LeMans 900',900,450),
  cornerMechanism('corner-lemans-1000','LeMans 1000',1000,500),
  cornerMechanism('corner-magic-900','Magic Corner 900',900,450),
  cornerMechanism('corner-magic-1000','Magic Corner 1000',1000,500),
  wardrobeRail('wardrobe-long-rail-600','Гардероб · длинная одежда + штанга 600',600,1,1,{en:{name:'Wardrobe long hanging + rail 600',description:'600 mm long-clothes section with top shelf and one wardrobe rail.'},cs:{name:'Šatna dlouhé oděvy + tyč 600',description:'Sekce 600 mm pro dlouhé oděvy s horní policí a jednou šatní tyčí.'},de:{name:'Garderobe lange Kleidung + Stange 600',description:'600-mm-Sektion für lange Kleidung mit oberem Boden und einer Kleiderstange.'},pl:{name:'Garderoba długie ubrania + drążek 600',description:'Sekcja 600 mm na długie ubrania z górną półką i jednym drążkiem.'}}),
  wardrobeRail('wardrobe-double-hang-600','Гардероб · двойная штанга 600',600,2,2,{en:{name:'Wardrobe double hanging 600',description:'600 mm short-clothes section with two wardrobe rails.'},cs:{name:'Šatna dvojitá tyč 600',description:'Sekce 600 mm pro krátké oděvy se dvěma šatními tyčemi.'},de:{name:'Garderobe Doppelstange 600',description:'600-mm-Sektion für kurze Kleidung mit zwei Kleiderstangen.'},pl:{name:'Garderoba podwójny drążek 600',description:'Sekcja 600 mm na krótkie ubrania z dwoma drążkami.'}}),
  wardrobeRail('wardrobe-double-hang-900','Гардероб · двойная штанга 900',900,2,2,{en:{name:'Wardrobe double hanging 900',description:'Wide 900 mm short-clothes section with two wardrobe rails.'},cs:{name:'Šatna dvojitá tyč 900',description:'Široká sekce 900 mm pro krátké oděvy se dvěma šatními tyčemi.'},de:{name:'Garderobe Doppelstange 900',description:'Breite 900-mm-Sektion für kurze Kleidung mit zwei Kleiderstangen.'},pl:{name:'Garderoba podwójny drążek 900',description:'Szeroka sekcja 900 mm na krótkie ubrania z dwoma drążkami.'}}),
  wardrobeRail('wardrobe-combo-900','Гардероб · полки + штанга 900',900,4,1,{en:{name:'Wardrobe shelves + rail 900',description:'900 mm combination section with shelves and one hanging rail.'},cs:{name:'Šatna police + tyč 900',description:'Kombinovaná sekce 900 mm s policemi a jednou šatní tyčí.'},de:{name:'Garderobe Böden + Stange 900',description:'900-mm-Kombinationssektion mit Böden und einer Kleiderstange.'},pl:{name:'Garderoba półki + drążek 900',description:'Sekcja kombinowana 900 mm z półkami i jednym drążkiem.'}}),
  wardrobeSliding(1200,2),wardrobeSliding(1600,2),wardrobeSliding(1800,3),
];

export const SCENARIO_COMPLETENESS_PRESETS:QuoteModulePreset[]=[
  {...wall,key:'hood-wall-600-720',group:'appliance',name:'Верхний шкаф вытяжки 600',description:'Навесной шкаф 600 мм под встроенную вытяжку, без внутренней полки и без задней стенки в зоне вентиляции.',moduleKey:'w-door',widthMm:600,heightMm:720,depthMm:350,drawers:0,doors:1,shelfCount:0,backMode:'none',translations:{en:{name:'Hood wall cabinet 600',description:'600 mm wall cabinet for a built-in hood, without internal shelf or back panel in the ventilation zone.'},cs:{name:'Horní skříň pro digestoř 600',description:'Horní skříňka 600 mm pro vestavnou digestoř bez vnitřní police a zadní stěny v zóně odtahu.'},de:{name:'Dunstabzug-Oberschrank 600',description:'600-mm-Oberschrank für Einbauhaube ohne Innenboden und Rückwand im Abluftbereich.'},pl:{name:'Szafka górna pod okap 600',description:'Szafka górna 600 mm pod okap do zabudowy, bez półki i pleców w strefie wentylacji.'}}},
  {...wall,key:'fridge-top-600-400',group:'appliance',name:'Шкаф над холодильником 600 × 400',description:'Глубокий верхний шкаф над холодильником, глубина 600 мм.',moduleKey:'w-door',widthMm:600,heightMm:400,depthMm:600,drawers:0,doors:1,shelfCount:0,backMode:'groove',translations:{en:{name:'Fridge top cabinet 600 × 400',description:'Deep wall cabinet above a fridge, 600 mm deep.'},cs:{name:'Skříň nad lednici 600 × 400',description:'Hluboká horní skříňka nad lednici, hloubka 600 mm.'},de:{name:'Schrank über Kühlschrank 600 × 400',description:'Tiefer Oberschrank über dem Kühlschrank, 600 mm tief.'},pl:{name:'Szafka nad lodówką 600 × 400',description:'Głęboka szafka górna nad lodówką, głębokość 600 mm.'}}},
  {...wall,key:'fridge-top-800-400',group:'appliance',name:'Шкаф над холодильником 800 × 400',description:'Глубокий верхний шкаф над холодильником, глубина 600 мм.',moduleKey:'w-door',widthMm:800,heightMm:400,depthMm:600,drawers:0,doors:2,shelfCount:0,backMode:'groove',translations:{en:{name:'Fridge top cabinet 800 × 400',description:'Deep wall cabinet above a fridge, 600 mm deep.'},cs:{name:'Skříň nad lednici 800 × 400',description:'Hluboká horní skříňka nad lednici, hloubka 600 mm.'},de:{name:'Schrank über Kühlschrank 800 × 400',description:'Tiefer Oberschrank über dem Kühlschrank, 600 mm tief.'},pl:{name:'Szafka nad lodówką 800 × 400',description:'Głęboka szafka górna nad lodówką, głębokość 600 mm.'}}},
  {...common,family:'bathroom',group:'bathroom-wall',key:'bathroom-tall-400-1800',name:'Ванная · высокий шкаф 400 × 1800',description:'Высокий шкаф ванной 400 мм, глубина 350 мм, четыре полки.',moduleKey:'t-door',widthMm:400,heightMm:1800,depthMm:350,drawers:0,doors:1,shelfCount:4,backMode:'groove',translations:{en:{name:'Bathroom tall 400 × 1800',description:'Tall 400 mm bathroom cabinet, 350 mm deep, with four shelves.'},cs:{name:'Koupelna vysoká 400 × 1800',description:'Vysoká koupelnová skříňka 400 mm, hloubka 350 mm, čtyři police.'},de:{name:'Bad-Hochschrank 400 × 1800',description:'Hoher Badschrank 400 mm, 350 mm tief, mit vier Böden.'},pl:{name:'Łazienka wysoka 400 × 1800',description:'Wysoka szafka łazienkowa 400 mm, głębokość 350 mm, cztery półki.'}}},
  {...common,family:'bathroom',group:'bathroom-vanity',key:'bathroom-vanity-1200-4d',name:'Тумба под раковину 1200 · 4 ящика',description:'Широкая подвесная тумба 1200 мм с четырьмя ящиками, без задней стенки для коммуникаций.',moduleKey:'b-drawer',widthMm:1200,heightMm:560,depthMm:480,drawers:4,doors:0,shelfCount:0,backMode:'none',translations:{en:{name:'Vanity 1200 · 4 drawers',description:'Wide 1200 mm wall-hung vanity with four drawers and open back for services.'},cs:{name:'Skříňka pod umyvadlo 1200 · 4 zásuvky',description:'Široká závěsná skříňka 1200 mm se čtyřmi zásuvkami a bez zad pro instalace.'},de:{name:'Waschtischunterschrank 1200 · 4 Schubladen',description:'Breiter hängender Waschtischunterschrank 1200 mm mit vier Schubladen und ohne Rückwand.'},pl:{name:'Szafka pod umywalkę 1200 · 4 szuflady',description:'Szeroka wisząca szafka 1200 mm z czterema szufladami i bez pleców.'}}},
];

for(const preset of [...SCENARIO_COMPLETENESS_PRESETS,...SPECIAL_HARDWARE_PRESETS]){
  if(!QUOTE_MODULE_PRESETS.some((item)=>item.key===preset.key))QUOTE_MODULE_PRESETS.push(preset);
}

export function specialHardwarePreset(key:string){return SPECIAL_HARDWARE_PRESETS.find((preset)=>preset.key===key)??null;}
export function isSpecialHardwarePreset(preset:QuoteModulePreset):preset is SpecialHardwarePreset{return 'specialHardwareRole' in preset && 'specialHardwareQty' in preset;}
