import http from "node:http";
import {spawn} from "node:child_process";
import {mkdtemp,writeFile,readdir,readFile,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
const port=Number(process.env.PORT||3000),runtimeSecret=process.env.VYTA_RUNTIME_SHARED_SECRET||"";
const adapters={stt:{kind:"provider_adapter",preferred:"vyta_self_hosted",fallback:"external",status:"chunk_benchmark_ready",protocol:"openai_compatible_http",endpoint_env:"VYTA_STT_BASE_URL",model_env:"VYTA_STT_MODEL"},tts:{kind:"provider_adapter",preferred:"vyta_self_hosted",fallback:"external"},reasoning:{kind:"provider_adapter",preferred:"vyta_self_hosted",fallback:"external"}};
const json=(res,s,b)=>{res.writeHead(s,{"content-type":"application/json"});res.end(JSON.stringify(b));};
const authorized=req=>runtimeSecret&&req.headers["x-vyta-runtime-secret"]===runtimeSecret;
const route=(capability,complexity,externalAllowed=true)=>{if(["stt","tts","action"].includes(capability)&&complexity<=1)return{tier:"vyta_small",provider:"vyta",reason:"low_complexity"};if(complexity<=2)return{tier:"vyta_small",provider:"vyta",reason:"default_self_host"};if(complexity<=4)return{tier:"vyta_large",provider:"vyta",reason:"complex_self_host"};if(externalAllowed)return{tier:"external_frontier",provider:"external",reason:"frontier_required"};return{tier:"vyta_large",provider:"vyta",reason:"external_disabled"};};
async function sttMultipart(bytes,name,model,type="audio/mpeg"){const base=(process.env.VYTA_STT_BASE_URL||"").replace(/\/$/,"");if(!base)throw new Error("stt_backend_not_configured");const fd=new FormData();fd.append("file",new Blob([bytes],{type}),name);fd.append("model",model);const u=await fetch(base+"/v1/audio/transcriptions",{method:"POST",body:fd,signal:AbortSignal.timeout(120000)});const t=await u.text();if(!u.ok)throw new Error("stt_"+u.status+":"+t.slice(0,200));try{return JSON.parse(t)}catch{return{text:t}}}
async function transcribeBytes(res,bytes,contentType,started){try{const base=(process.env.VYTA_STT_BASE_URL||"").replace(/\/$/,"");if(!base)return json(res,503,{error:"stt_backend_not_configured"});const u=await fetch(base+"/v1/audio/transcriptions",{method:"POST",headers:{"content-type":contentType},body:bytes,signal:AbortSignal.timeout(120000)});const body=await u.text();res.writeHead(u.status,{"content-type":u.headers.get("content-type")||"application/json","x-vyta-stt-latency-ms":String(Date.now()-started),"x-vyta-stt-provider":"self_hosted"});res.end(body)}catch(e){json(res,502,{error:"stt_backend_unavailable",detail:e.name,latency_ms:Date.now()-started})}}
const allowedSource=source=>{try{const h=new URL(source).hostname.toLowerCase(),a=["dnznrvs05pmza.cloudfront.net","runwayml.com","www.runwayml.com"];return /^https:\/\//i.test(source)&&a.some(x=>h===x||h.endsWith("."+x))}catch{return false}};
async function fetchAudio(source){if(!allowedSource(source))throw new Error("invalid_audio_url");const a=await fetch(source,{signal:AbortSignal.timeout(30000),redirect:"follow"});if(!a.ok)throw new Error("audio_fetch_"+a.status);const b=Buffer.from(await a.arrayBuffer());if(b.length>25*1024*1024)throw new Error("audio_too_large");return b}
async function chunkAudio(bytes,seconds){const dir=await mkdtemp(join(tmpdir(),"vyta-stt-")),input=join(dir,"input.mp3"),pattern=join(dir,"chunk-%03d.wav");await writeFile(input,bytes);await new Promise((ok,bad)=>{const p=spawn("ffmpeg",["-hide_banner","-loglevel","error","-i",input,"-f","segment","-segment_time",String(seconds),"-ar","16000","-ac","1","-c:a","pcm_s16le",pattern]);let err="";p.stderr.on("data",d=>err+=d);p.on("error",bad);p.on("close",c=>c===0?ok():bad(new Error("ffmpeg_"+c+":"+err.slice(-300))))});const files=(await readdir(dir)).filter(x=>x.startsWith("chunk-")).sort();return{dir,files:await Promise.all(files.map(async name=>({name,bytes:await readFile(join(dir,name))})))}} 
http.createServer((req,res)=>{
 if(req.method==="GET"&&req.url==="/health")return json(res,200,{ok:true,service:"vyta-runtime",version:"0.1.2"});
 if(req.method==="GET"&&req.url==="/")return json(res,200,{service:"VYTA Runtime",version:"0.1.2",policy:"self-host-first"});
 if(req.method==="GET"&&req.url==="/v1/adapters")return json(res,200,{runtime:"VYTA Runtime 0.1.2",execute:false,adapters});
 if(req.method==="GET"&&req.url==="/v1/stt/status")return json(res,200,{adapter:"stt",mode:"chunk_benchmark",configured:Boolean(process.env.VYTA_STT_BASE_URL),model:process.env.VYTA_STT_MODEL||null,execute:true});
 if(req.method==="POST"&&req.url==="/v1/stt/transcribe"){if(!runtimeSecret)return json(res,503,{error:"runtime_secret_not_configured"});if(!authorized(req))return json(res,401,{error:"unauthorized"});const started=Date.now(),chunks=[];req.on("data",x=>chunks.push(x));req.on("end",()=>transcribeBytes(res,Buffer.concat(chunks),req.headers["content-type"]||"application/octet-stream",started));return}
 if(req.method==="POST"&&(req.url==="/v1/stt/benchmark"||req.url==="/v1/stt/benchmark-chunked")){if(!runtimeSecret)return json(res,503,{error:"runtime_secret_not_configured"});if(!authorized(req))return json(res,401,{error:"unauthorized"});let raw="";req.on("data",x=>raw+=x);req.on("end",async()=>{const started=Date.now();let dir;try{const b=JSON.parse(raw||"{}"),source=String(b.audio_url||""),model=String(b.model||process.env.VYTA_STT_MODEL||"Systran/faster-distil-whisper-small.en"),audio=await fetchAudio(source);if(req.url==="/v1/stt/benchmark"){const out=await sttMultipart(audio,String(b.filename||"benchmark.mp3"),model);return json(res,200,{...out,latency_ms:Date.now()-started})}const seconds=Math.max(5,Math.min(20,Number(b.chunk_seconds||12))),c=await chunkAudio(audio,seconds);dir=c.dir;const parts=[];for(let i=0;i<c.files.length;i++){const s=Date.now(),out=await sttMultipart(c.files[i].bytes,c.files[i].name,model,"audio/wav");parts.push({index:i,text:String(out.text||"").trim(),latency_ms:Date.now()-s})}return json(res,200,{mode:"chunked",chunk_seconds:seconds,chunks:parts.length,text:parts.map(x=>x.text).filter(Boolean).join(" "),parts,latency_ms:Date.now()-started})}catch(e){return json(res,502,{error:"benchmark_failed",detail:e.message,latency_ms:Date.now()-started})}finally{if(dir)await rm(dir,{recursive:true,force:true}).catch(()=>{})}});return}
 if(req.method==="POST"&&req.url==="/v1/route"){if(!runtimeSecret)return json(res,503,{error:"runtime_secret_not_configured"});if(!authorized(req))return json(res,401,{error:"unauthorized"});let raw="";req.on("data",x=>raw+=x);req.on("end",()=>{try{const b=JSON.parse(raw||"{}"),a=["realtime","stt","tts","reasoning","action"];if(!a.includes(b.capability))return json(res,400,{error:"invalid_capability"});const complexity=Math.max(1,Math.min(5,Number(b.complexity??2)));return json(res,200,{runtime:"VYTA Runtime 0.1.2",execute:false,selected:route(b.capability,complexity,b.external_frontier_enabled!==false)})}catch{return json(res,400,{error:"invalid_json"})}});return}
 json(res,404,{error:"not_found"});
}).listen(port,"0.0.0.0",()=>console.log("VYTA Runtime listening",port));