import http from "node:http";
import crypto from "node:crypto";
import {spawn} from "node:child_process";
import {mkdtemp,writeFile,readdir,readFile,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import WebSocket,{WebSocketServer} from "ws";
const port=Number(process.env.PORT||3000),runtimeSecret=process.env.VYTA_RUNTIME_SHARED_SECRET||"";
const sessions=new Map();
const streamSessions=new Map();
const conversationStates=new Map();
const TURN_STATES=new Set(["LISTEN","HOLD","COMMIT","BACKCHANNEL","POSSIBLE_INTERRUPT","CONFIRMED_INTERRUPT","BACKGROUND"]);
function createConversationState(id=crypto.randomUUID()){const now=Date.now(),x={id,state:"LISTEN",turn:0,created_at:now,updated_at:now,last_text:"",history:[]};conversationStates.set(id,x);return x}
function setTurnState(c,next,reason=""){if(!TURN_STATES.has(next))throw new Error("invalid_turn_state");const prev=c.state;c.state=next;c.updated_at=Date.now();c.history.push({ts:c.updated_at,from:prev,to:next,reason});if(c.history.length>50)c.history.shift();return c}

// Build trigger: stream self-test syntax hotfix
const STREAM_SILENCE_DB=Number(process.env.VYTA_STREAM_SILENCE_DB||-38),STREAM_END_MS=Number(process.env.VYTA_STREAM_END_MS||550),STREAM_MIN_SPEECH_MS=Number(process.env.VYTA_STREAM_MIN_SPEECH_MS||180);
const warmState={ready:false,warming:false,last_error:null,warmed_at:null,latency_ms:null};
async function warmStt(){if(warmState.ready||warmState.warming)return;warmState.warming=true;const started=Date.now();try{const base=(process.env.VYTA_STT_BASE_URL||"").replace(/\/$/,"");if(!base)throw new Error("stt_backend_not_configured");const wav=Buffer.alloc(16044);wav.write("RIFF",0);wav.writeUInt32LE(16036,4);wav.write("WAVEfmt ",8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write("data",36);wav.writeUInt32LE(16000,40);await sttMultipart(wav,"warmup.wav",process.env.VYTA_STT_MODEL||"Systran/faster-distil-whisper-small.en","audio/wav");warmState.ready=true;warmState.warmed_at=Date.now();warmState.latency_ms=Date.now()-started;warmState.last_error=null;console.log("VYTA_STT_WARM_READY",JSON.stringify({latency_ms:warmState.latency_ms,warmed_at:warmState.warmed_at}))}catch(e){warmState.ready=false;warmState.last_error=e.message;console.error("VYTA_STT_WARM_FAILED",e.message)}finally{warmState.warming=false}}
const SESSION_TTL_MS=15*60*1000;
const cleanupSessions=()=>{const now=Date.now();for(const [id,s] of sessions)if(now-s.updated_at>SESSION_TTL_MS)sessions.delete(id)};setInterval(cleanupSessions,60000).unref();
const adapters={stt:{kind:"provider_adapter",preferred:"vyta_self_hosted",fallback:"external",status:"warm_session_ready",protocol:"openai_compatible_http",endpoint_env:"VYTA_STT_BASE_URL",model_env:"VYTA_STT_MODEL"},tts:{kind:"provider_adapter",preferred:"vyta_self_hosted",fallback:"external"},reasoning:{kind:"provider_adapter",preferred:"vyta_self_hosted",fallback:"external"}};
const json=(res,s,b)=>{res.writeHead(s,{"content-type":"application/json"});res.end(JSON.stringify(b));};
const authorized=req=>runtimeSecret&&req.headers["x-vyta-runtime-secret"]===runtimeSecret;
const route=(capability,complexity,externalAllowed=true)=>{if(["stt","tts","action"].includes(capability)&&complexity<=1)return{tier:"vyta_small",provider:"vyta",reason:"low_complexity"};if(complexity<=2)return{tier:"vyta_small",provider:"vyta",reason:"default_self_host"};if(complexity<=4)return{tier:"vyta_large",provider:"vyta",reason:"complex_self_host"};if(externalAllowed)return{tier:"external_frontier",provider:"external",reason:"frontier_required"};return{tier:"vyta_large",provider:"vyta",reason:"external_disabled"};};
async function sttMultipart(bytes,name,model,type="audio/mpeg"){const base=(process.env.VYTA_STT_BASE_URL||"").replace(/\/$/,"");if(!base)throw new Error("stt_backend_not_configured");const fd=new FormData();fd.append("file",new Blob([bytes],{type}),name);fd.append("model",model);const u=await fetch(base+"/v1/audio/transcriptions",{method:"POST",body:fd,signal:AbortSignal.timeout(120000)});const t=await u.text();if(!u.ok)throw new Error("stt_"+u.status+":"+t.slice(0,200));try{return JSON.parse(t)}catch{return{text:t}}}
async function transcribeBytes(res,bytes,contentType,started){try{const base=(process.env.VYTA_STT_BASE_URL||"").replace(/\/$/,"");if(!base)return json(res,503,{error:"stt_backend_not_configured"});const u=await fetch(base+"/v1/audio/transcriptions",{method:"POST",headers:{"content-type":contentType},body:bytes,signal:AbortSignal.timeout(120000)});const body=await u.text();res.writeHead(u.status,{"content-type":u.headers.get("content-type")||"application/json","x-vyta-stt-latency-ms":String(Date.now()-started),"x-vyta-stt-provider":"self_hosted"});res.end(body)}catch(e){json(res,502,{error:"stt_backend_unavailable",detail:e.name,latency_ms:Date.now()-started})}}
const allowedSource=source=>{try{const h=new URL(source).hostname.toLowerCase(),a=["dnznrvs05pmza.cloudfront.net","runwayml.com","www.runwayml.com"];return /^https:\/\//i.test(source)&&a.some(x=>h===x||h.endsWith("."+x))}catch{return false}};
async function fetchAudio(source){if(!allowedSource(source))throw new Error("invalid_audio_url");const a=await fetch(source,{signal:AbortSignal.timeout(30000),redirect:"follow"});if(!a.ok)throw new Error("audio_fetch_"+a.status);const b=Buffer.from(await a.arrayBuffer());if(b.length>25*1024*1024)throw new Error("audio_too_large");return b}
async function vadAudio(bytes,{silenceDb=-38,minSilence=0.55,maxSegment=12}={}){const dir=await mkdtemp(join(tmpdir(),"vyta-vad-")),input=join(dir,"input.mp3"),wav=join(dir,"speech.wav");await writeFile(input,bytes);await new Promise((ok,bad)=>{const p=spawn("ffmpeg",["-hide_banner","-loglevel","error","-i",input,"-ar","16000","-ac","1","-c:a","pcm_s16le",wav]);let err="";p.stderr.on("data",d=>err+=d);p.on("error",bad);p.on("close",x=>x===0?ok():bad(new Error("ffmpeg_decode_"+x+":"+err.slice(-300))))});const args=["-hide_banner","-i",wav,"-af",`silencedetect=noise=${silenceDb}dB:d=${minSilence}`,"-f","null","-"],events=[];await new Promise((ok,bad)=>{const p=spawn("ffmpeg",args);let err="";p.stderr.on("data",d=>err+=d);p.on("error",bad);p.on("close",x=>{if(x!==0)return bad(new Error("ffmpeg_vad_"+x));for(const line of err.split("\n")){let m=line.match(/silence_start: ([0-9.]+)/);if(m)events.push({type:"start",t:Number(m[1])});m=line.match(/silence_end: ([0-9.]+)/);if(m)events.push({type:"end",t:Number(m[1])})}ok()})});const probe=await new Promise((ok,bad)=>{let out="";const p=spawn("ffprobe",["-v","error","-show_entries","format=duration","-of","default=nw=1:nk=1",wav]);p.stdout.on("data",d=>out+=d);p.on("error",bad);p.on("close",x=>x===0?ok(Number(out.trim())):bad(new Error("ffprobe_"+x))) });const silences=[];let ss=null;for(const e of events){if(e.type==="start")ss=e.t;else if(e.type==="end"){silences.push([ss??0,e.t]);ss=null}}if(ss!==null)silences.push([ss,probe]);const speech=[];let cur=0;for(const [a,b] of silences){if(a>cur+0.15)speech.push([cur,a]);cur=Math.max(cur,b)}if(probe>cur+0.15)speech.push([cur,probe]);const merged=[];for(const [a,b] of speech){let s=a;while(b-s>maxSegment){merged.push([s,s+maxSegment]);s+=maxSegment}if(b-s>0.2)merged.push([s,b])}const files=[];for(let i=0;i<merged.length;i++){const [a,b]=merged[i],name=`vad-${String(i).padStart(3,"0")}.wav`,path=join(dir,name);await new Promise((ok,bad)=>{const p=spawn("ffmpeg",["-hide_banner","-loglevel","error","-ss",String(a),"-to",String(b),"-i",wav,"-c","copy",path]);p.on("error",bad);p.on("close",x=>x===0?ok():bad(new Error("ffmpeg_cut_"+x))) });files.push({name,bytes:await readFile(path),start_ms:Math.round(a*1000),end_ms:Math.round(b*1000)})}return{dir,files,duration_ms:Math.round(probe*1000),silence_db:silenceDb,min_silence_ms:Math.round(minSilence*1000)}}
async function chunkAudio(bytes,seconds){const dir=await mkdtemp(join(tmpdir(),"vyta-stt-")),input=join(dir,"input.mp3"),pattern=join(dir,"chunk-%03d.wav");await writeFile(input,bytes);await new Promise((ok,bad)=>{const p=spawn("ffmpeg",["-hide_banner","-loglevel","error","-i",input,"-f","segment","-segment_time",String(seconds),"-ar","16000","-ac","1","-c:a","pcm_s16le",pattern]);let err="";p.stderr.on("data",d=>err+=d);p.on("error",bad);p.on("close",c=>c===0?ok():bad(new Error("ffmpeg_"+c+":"+err.slice(-300))))});const files=(await readdir(dir)).filter(x=>x.startsWith("chunk-")).sort();return{dir,files:await Promise.all(files.map(async name=>({name,bytes:await readFile(join(dir,name))})))}} 
function createStreamSession(){const id=crypto.randomUUID(),now=Date.now(),s={id,created_at:now,updated_at:now,seq:0,bytes:0,state:"listening",events:[],speech:false,speech_bytes:[],speech_ms:0,silence_ms:0,stt_busy:false,pending:Promise.resolve(),pending_count:0};streamSessions.set(id,s);return s}
function pcmLevelDb(b){if(!b?.length)return -100;let sum=0,n=0;for(let i=0;i+1<b.length;i+=2){const x=b.readInt16LE(i)/32768;sum+=x*x;n++}return n?20*Math.log10(Math.sqrt(sum/n)+1e-9):-100}
function pcmWav(pcm){const h=Buffer.alloc(44);h.write("RIFF",0);h.writeUInt32LE(36+pcm.length,4);h.write("WAVEfmt ",8);h.writeUInt32LE(16,16);h.writeUInt16LE(1,20);h.writeUInt16LE(1,22);h.writeUInt32LE(16000,24);h.writeUInt32LE(32000,28);h.writeUInt16LE(2,32);h.writeUInt16LE(16,34);h.write("data",36);h.writeUInt32LE(pcm.length,40);return Buffer.concat([h,pcm])}
function finalizeStreamSpeech(s){if(!s.speech_bytes.length)return s.pending;const pcm=Buffer.concat(s.speech_bytes),duration_ms=Math.round(pcm.length/32);s.speech_bytes=[];s.speech_ms=0;s.silence_ms=0;s.speech=false;pushStreamEvent(s,"speech.end",{duration_ms});if(duration_ms<STREAM_MIN_SPEECH_MS)return s.pending;s.pending_count++;s.pending=s.pending.then(async()=>{s.stt_busy=true;try{const started=Date.now(),out=await sttMultipart(pcmWav(pcm),"stream.wav",process.env.VYTA_STT_MODEL||"Systran/faster-distil-whisper-small.en","audio/wav");pushStreamEvent(s,"speech.final",{text:String(out.text||"").trim(),duration_ms,latency_ms:Date.now()-started})}catch(e){pushStreamEvent(s,"speech.error",{error:e.message,duration_ms})}finally{s.pending_count--;s.stt_busy=s.pending_count>0}});return s.pending}
function pushStreamEvent(s,type,data={}){const e={seq:++s.seq,type,ts:Date.now(),...data};s.events.push(e);if(s.events.length>100)s.events.shift();s.updated_at=Date.now();if(s.ws?.readyState===1)s.ws.send(JSON.stringify(e));return e}
function ingestPcmChunk(s,b){s.bytes+=b.length;const db=pcmLevelDb(b),ms=Math.round(b.length/32);if(db>=STREAM_SILENCE_DB){if(!s.speech){s.speech=true;pushStreamEvent(s,"speech.start",{level_db:Number(db.toFixed(1))})}s.speech_bytes.push(b);s.speech_ms+=ms;s.silence_ms=0;if(s.speech_ms>=12000)finalizeStreamSpeech(s)}else if(s.speech){s.speech_bytes.push(b);s.silence_ms+=ms;if(s.silence_ms>=STREAM_END_MS)finalizeStreamSpeech(s)}return db}
const server=http.createServer(async(req,res)=>{
 if(req.method==="POST"&&req.url==="/v1/realtime/stream"){if(!runtimeSecret)return json(res,503,{error:"runtime_secret_not_configured"});if(!authorized(req))return json(res,401,{error:"unauthorized"});const s=createStreamSession();pushStreamEvent(s,"session.created",{transport:"http_chunk_stream",sample_rate_hz:16000,channels:1,format:"pcm_s16le"});return json(res,201,{session_id:s.id,transport:"http_chunk_stream",next:"POST /v1/realtime/stream/:id/audio"})}
 {const m=req.url?.match(/^\/v1\/realtime\/stream\/([^/]+)\/audio$/);if(req.method==="POST"&&m){if(!authorized(req))return json(res,401,{error:"unauthorized"});const s=streamSessions.get(m[1]);if(!s)return json(res,404,{error:"stream_session_not_found"});const chunks=[];req.on("data",x=>chunks.push(x));req.on("end",()=>{const b=Buffer.concat(chunks);s.bytes+=b.length;const db=pcmLevelDb(b),ms=Math.round(b.length/32);pushStreamEvent(s,"audio.chunk",{bytes:b.length,total_bytes:s.bytes,level_db:Number(db.toFixed(1))});if(db>=STREAM_SILENCE_DB){if(!s.speech){s.speech=true;pushStreamEvent(s,"speech.start",{level_db:Number(db.toFixed(1))})}s.speech_bytes.push(b);s.speech_ms+=ms;s.silence_ms=0}else if(s.speech){s.speech_bytes.push(b);s.silence_ms+=ms;if(s.silence_ms>=STREAM_END_MS)finalizeStreamSpeech(s)}return json(res,202,{session_id:s.id,accepted_bytes:b.length,total_bytes:s.bytes,seq:s.seq,speech:s.speech,level_db:Number(db.toFixed(1))})});return}}
 {const m=req.url?.match(/^\/v1\/realtime\/stream\/([^/]+)\/events$/);if(req.method==="GET"&&m){if(!authorized(req))return json(res,401,{error:"unauthorized"});const s=streamSessions.get(m[1]);if(!s)return json(res,404,{error:"stream_session_not_found"});return json(res,200,{session_id:s.id,state:s.state,events:s.events})}}
 {const m=req.url?.match(/^\/v1\/realtime\/stream\/([^/]+)$/);if(req.method==="DELETE"&&m){if(!authorized(req))return json(res,401,{error:"unauthorized"});const s=streamSessions.get(m[1]);if(!s)return json(res,404,{error:"stream_session_not_found"});pushStreamEvent(s,"session.closed",{total_bytes:s.bytes});streamSessions.delete(s.id);return json(res,200,{session_id:s.id,closed:true,total_bytes:s.bytes})}}
 if(req.method==="GET"&&req.url==="/health")return json(res,200,{ok:true,service:"vyta-runtime",version:"0.3.0"});
 if(req.method==="GET"&&req.url==="/")return json(res,200,{service:"VYTA Runtime",version:"0.3.0",policy:"self-host-first"});
 if(req.method==="GET"&&req.url==="/v1/adapters")return json(res,200,{runtime:"VYTA Runtime 0.3.0",execute:false,adapters});
 if(req.method==="GET"&&req.url==="/v1/stt/status")return json(res,200,{adapter:"stt",mode:"stream_session",configured:Boolean(process.env.VYTA_STT_BASE_URL),model:process.env.VYTA_STT_MODEL||null,execute:true,warm:warmState});
 if(req.method==="POST"&&req.url==="/v1/stt/warm"){if(!authorized(req))return json(res,401,{error:"unauthorized"});warmStt().then(()=>json(res,warmState.ready?200:503,{warm:warmState})).catch(()=>json(res,503,{warm:warmState}));return}
 if(req.method==="POST"&&req.url==="/v1/stt/transcribe"){if(!runtimeSecret)return json(res,503,{error:"runtime_secret_not_configured"});if(!authorized(req))return json(res,401,{error:"unauthorized"});const started=Date.now(),chunks=[];req.on("data",x=>chunks.push(x));req.on("end",()=>transcribeBytes(res,Buffer.concat(chunks),req.headers["content-type"]||"application/octet-stream",started));return}
 if(req.method==="POST"&&(req.url==="/v1/stt/benchmark"||req.url==="/v1/stt/benchmark-chunked")){if(!runtimeSecret)return json(res,503,{error:"runtime_secret_not_configured"});if(!authorized(req))return json(res,401,{error:"unauthorized"});let raw="";req.on("data",x=>raw+=x);req.on("end",async()=>{const started=Date.now();let dir;try{const b=JSON.parse(raw||"{}"),source=String(b.audio_url||""),model=String(b.model||process.env.VYTA_STT_MODEL||"Systran/faster-distil-whisper-small.en"),audio=await fetchAudio(source);if(req.url==="/v1/stt/benchmark"){const out=await sttMultipart(audio,String(b.filename||"benchmark.mp3"),model);return json(res,200,{...out,latency_ms:Date.now()-started})}const seconds=Math.max(5,Math.min(20,Number(b.chunk_seconds||12))),c=await chunkAudio(audio,seconds);dir=c.dir;const parts=[];for(let i=0;i<c.files.length;i++){const s=Date.now(),out=await sttMultipart(c.files[i].bytes,c.files[i].name,model,"audio/wav");parts.push({index:i,text:String(out.text||"").trim(),latency_ms:Date.now()-s})}return json(res,200,{mode:"chunked",chunk_seconds:seconds,chunks:parts.length,text:parts.map(x=>x.text).filter(Boolean).join(" "),parts,latency_ms:Date.now()-started})}catch(e){return json(res,502,{error:"benchmark_failed",detail:e.message,latency_ms:Date.now()-started})}finally{if(dir)await rm(dir,{recursive:true,force:true}).catch(()=>{})}});return}
 if(req.method==="POST"&&req.url==="/v1/stt/benchmark-vad"){if(!runtimeSecret)return json(res,503,{error:"runtime_secret_not_configured"});if(!authorized(req))return json(res,401,{error:"unauthorized"});let raw="";req.on("data",x=>raw+=x);req.on("end",async()=>{const started=Date.now();let dir;try{const b=JSON.parse(raw||"{}"),audio=await fetchAudio(String(b.audio_url||"")),model=String(b.model||process.env.VYTA_STT_MODEL||"Systran/faster-distil-whisper-small.en"),v=await vadAudio(audio,{silenceDb:Number(b.silence_db??-38),minSilence:Number(b.min_silence_seconds??0.55),maxSegment:Number(b.max_segment_seconds??12)});dir=v.dir;const parts=[];for(let i=0;i<v.files.length;i++){const f=v.files[i],s=Date.now(),out=await sttMultipart(f.bytes,f.name,model,"audio/wav");parts.push({index:i,start_ms:f.start_ms,end_ms:f.end_ms,text:String(out.text||"").trim(),latency_ms:Date.now()-s})}return json(res,200,{mode:"vad",segments:parts.length,duration_ms:v.duration_ms,silence_db:v.silence_db,min_silence_ms:v.min_silence_ms,text:parts.map(x=>x.text).filter(Boolean).join(" "),parts,latency_ms:Date.now()-started})}catch(e){return json(res,502,{error:"vad_benchmark_failed",detail:e.message,latency_ms:Date.now()-started})}finally{if(dir)await rm(dir,{recursive:true,force:true}).catch(()=>{})}});return}
 if(req.method==="POST"&&req.url==="/v1/realtime/session"){if(!runtimeSecret)return json(res,503,{error:"runtime_secret_not_configured"});if(!authorized(req))return json(res,401,{error:"unauthorized"});let raw="";req.on("data",x=>raw+=x);req.on("end",async()=>{try{if(!warmState.ready){await warmStt();if(!warmState.ready)return json(res,503,{error:"stt_not_ready",warm:warmState})}const b=JSON.parse(raw||"{}"),id=crypto.randomUUID(),now=Date.now();sessions.set(id,{id,created_at:now,updated_at:now,turn:0,language:String(b.language||"auto"),model:String(b.model||process.env.VYTA_STT_MODEL||"Systran/faster-distil-whisper-small.en")});json(res,201,{session_id:id,mode:"realtime_http",vad:{silence_db:-38,min_silence_ms:550,max_segment_ms:12000},warm:warmState.ready,warm_latency_ms:warmState.latency_ms})}catch{return json(res,400,{error:"invalid_json"})}});return}
 if(req.method==="POST"&&/^\/v1\/realtime\/session\/[^/]+\/audio$/.test(req.url)){if(!runtimeSecret)return json(res,503,{error:"runtime_secret_not_configured"});if(!authorized(req))return json(res,401,{error:"unauthorized"});const id=req.url.split("/")[4],s=sessions.get(id);if(!s)return json(res,404,{error:"session_not_found"});const started=Date.now(),chunks=[];req.on("data",x=>chunks.push(x));req.on("end",async()=>{let dir;try{const bytes=Buffer.concat(chunks);if(!bytes.length)return json(res,400,{error:"empty_audio"});if(bytes.length>8*1024*1024)return json(res,413,{error:"audio_too_large"});const v=await vadAudio(bytes,{silenceDb:-38,minSilence:0.55,maxSegment:12});dir=v.dir;const parts=[];for(const f of v.files){const t=Date.now(),out=await sttMultipart(f.bytes,f.name,s.model,"audio/wav");parts.push({start_ms:f.start_ms,end_ms:f.end_ms,text:String(out.text||"").trim(),latency_ms:Date.now()-t})}s.turn++;s.updated_at=Date.now();return json(res,200,{session_id:id,turn:s.turn,event:"speech.final",text:parts.map(x=>x.text).filter(Boolean).join(" "),segments:parts,latency_ms:Date.now()-started})}catch(e){return json(res,502,{error:"realtime_stt_failed",detail:e.message,latency_ms:Date.now()-started})}finally{if(dir)await rm(dir,{recursive:true,force:true}).catch(()=>{})}});return}
 if(req.method==="DELETE"&&/^\/v1\/realtime\/session\/[^/]+$/.test(req.url)){if(!authorized(req))return json(res,401,{error:"unauthorized"});const id=req.url.split("/")[4],found=sessions.delete(id);return json(res,found?200:404,{session_id:id,closed:found})}
 if(req.method==="POST"&&req.url==="/v1/route"){if(!runtimeSecret)return json(res,503,{error:"runtime_secret_not_configured"});if(!authorized(req))return json(res,401,{error:"unauthorized"});let raw="";req.on("data",x=>raw+=x);req.on("end",()=>{try{const b=JSON.parse(raw||"{}"),a=["realtime","stt","tts","reasoning","action"];if(!a.includes(b.capability))return json(res,400,{error:"invalid_capability"});const complexity=Math.max(1,Math.min(5,Number(b.complexity??2)));return json(res,200,{runtime:"VYTA Runtime 0.1.4",execute:false,selected:route(b.capability,complexity,b.external_frontier_enabled!==false)})}catch{return json(res,400,{error:"invalid_json"})}});return}
 json(res,404,{error:"not_found"});
});
const wss=new WebSocketServer({noServer:true,maxPayload:256*1024});
server.on("upgrade",(req,socket,head)=>{if(req.url!=="/v1/realtime/ws"||!runtimeSecret||req.headers["x-vyta-runtime-secret"]!==runtimeSecret){socket.write("HTTP/1.1 401 Unauthorized\r\nConnection: close\r\n\r\n");return socket.destroy()}wss.handleUpgrade(req,socket,head,ws=>wss.emit("connection",ws,req))});
wss.on("connection",(ws,req)=>{const s=createStreamSession();const u=new URL(req.url,"http://runtime.local");const requestedConversationId=u.searchParams.get("conversation_id");let conversation=requestedConversationId?conversationStates.get(requestedConversationId):null;const resumed=!!conversation;if(!conversation)conversation=createConversationState(requestedConversationId||undefined);s.conversation_id=conversation.id;s.ws=ws;pushStreamEvent(s,"session.created",{transport:"websocket",conversation_id:conversation.id,conversation_resumed:resumed,turn:conversation.turn,turn_state:conversation.state,sample_rate_hz:16000,channels:1,format:"pcm_s16le"});ws.on("message",async(data,isBinary)=>{if(isBinary){const b=Buffer.from(data);if(!b.length)return;const db=ingestPcmChunk(s,b);if(s.bytes%(3200*10)<b.length)ws.send(JSON.stringify({type:"audio.ack",total_bytes:s.bytes,level_db:Number(db.toFixed(1))}))}else{try{const m=JSON.parse(String(data));if(m.type==="audio.commit"){setTurnState(conversation,"COMMIT","audio.commit");pushStreamEvent(s,"turn.state",{conversation_id:conversation.id,state:conversation.state});await finalizeStreamSpeech(s);conversation.turn++;setTurnState(conversation,"LISTEN","commit.complete");pushStreamEvent(s,"audio.committed",{conversation_id:conversation.id,turn:conversation.turn,turn_state:conversation.state})}else if(m.type==="session.close")ws.close(1000,"client_close");else if(m.type==="ping")ws.send(JSON.stringify({type:"pong",ts:Date.now()}));else ws.send(JSON.stringify({type:"error",error:"unsupported_message"}))}catch{ws.send(JSON.stringify({type:"error",error:"invalid_json"}))}}});ws.on("close",()=>{if(s.speech_bytes.length)finalizeStreamSpeech(s);s.ws=null;streamSessions.delete(s.id)});ws.on("error",()=>{s.ws=null})});
server.listen(port,"0.0.0.0",()=>console.log("VYTA Runtime listening",port));
async function runRealtimeSelfTest(){const source=process.env.VYTA_STT_BENCHMARK_AUDIO_URL;if(!source)return console.log("VYTA_REALTIME_SELFTEST_SKIP no_audio_url");try{if(!warmState.ready)await warmStt();if(!warmState.ready)throw new Error("stt_not_ready:"+warmState.last_error);const audio=await fetchAudio(source),id=crypto.randomUUID(),now=Date.now();sessions.set(id,{id,created_at:now,updated_at:now,turn:0,language:"auto",model:process.env.VYTA_STT_MODEL||"Systran/faster-distil-whisper-small.en"});for(let turn=1;turn<=2;turn++){const started=Date.now(),v=await vadAudio(audio);let dir=v.dir;const parts=[];try{for(let i=0;i<v.files.length;i++){const s=Date.now(),out=await sttMultipart(v.files[i].bytes,v.files[i].name,sessions.get(id).model,"audio/wav");parts.push({index:i,text:String(out.text||"").trim(),latency_ms:Date.now()-s})}const session=sessions.get(id);session.turn++;session.updated_at=Date.now();console.log("VYTA_REALTIME_SELFTEST_TURN",JSON.stringify({session_id:id,turn:session.turn,segments:parts.length,text:parts.map(x=>x.text).filter(Boolean).join(" "),parts,latency_ms:Date.now()-started}))}finally{if(dir)await rm(dir,{recursive:true,force:true}).catch(()=>{})}}sessions.delete(id);console.log("VYTA_REALTIME_SELFTEST_DONE",id)}catch(e){console.error("VYTA_REALTIME_SELFTEST_FAILED",e.message)}}
setTimeout(()=>warmStt(),500).unref();
if(process.env.VYTA_RUNTIME_SELFTEST==="1")setTimeout(()=>runRealtimeSelfTest(),5000).unref();
async function runStreamSelfTest(){const source=process.env.VYTA_STT_BENCHMARK_AUDIO_URL;if(!source)return console.log("VYTA_STREAM_SELFTEST_SKIP no_audio_url");try{if(!warmState.ready)await warmStt();const raw=await fetchAudio(source),dir=await mkdtemp(join(tmpdir(),"vyta-stream-"));try{const src=join(dir,"input"),pcmPath=join(dir,"audio.pcm");await writeFile(src,raw);await new Promise((ok,bad)=>{const p=spawn("ffmpeg",["-hide_banner","-loglevel","error","-y","-i",src,"-ac","1","-ar","16000","-f","s16le",pcmPath]);let err="";p.stderr.on("data",d=>err+=d);p.on("error",bad);p.on("close",x=>x===0?ok():bad(new Error("ffmpeg_stream_"+x+":"+err.slice(-300))))});const pcm=await readFile(pcmPath),s=createStreamSession(),chunkBytes=3200;for(let o=0;o<pcm.length;o+=chunkBytes){const b=pcm.subarray(o,Math.min(o+chunkBytes,pcm.length)),db=pcmLevelDb(b),ms=Math.round(b.length/32);s.bytes+=b.length;if(db>=STREAM_SILENCE_DB){if(!s.speech){s.speech=true;pushStreamEvent(s,"speech.start",{level_db:Number(db.toFixed(1))})}s.speech_bytes.push(b);s.speech_ms+=ms;s.silence_ms=0}else if(s.speech){s.speech_bytes.push(b);s.silence_ms+=ms;if(s.silence_ms>=STREAM_END_MS)await finalizeStreamSpeech(s)}}if(s.speech_bytes.length)await finalizeStreamSpeech(s);console.log("VYTA_STREAM_SELFTEST",JSON.stringify({session_id:s.id,bytes:s.bytes,events:s.events.filter(e=>e.type!=="audio.chunk")}));streamSessions.delete(s.id)}finally{await rm(dir,{recursive:true,force:true}).catch(()=>{})}}catch(e){console.error("VYTA_STREAM_SELFTEST_FAILED",e.message)}}
if(process.env.VYTA_STREAM_SELFTEST==="1")setTimeout(()=>runStreamSelfTest(),5000).unref();

async function runWsSelfTest(){const source=process.env.VYTA_STT_BENCHMARK_AUDIO_URL;if(!source)return console.log("VYTA_WS_SELFTEST_SKIP no_audio_url");try{if(!warmState.ready)await warmStt();const raw=await fetchAudio(source),dir=await mkdtemp(join(tmpdir(),"vyta-ws-"));try{const src=join(dir,"input"),pcmPath=join(dir,"audio.pcm");await writeFile(src,raw);await new Promise((ok,bad)=>{const p=spawn("ffmpeg",["-hide_banner","-loglevel","error","-y","-i",src,"-ac","1","-ar","16000","-f","s16le",pcmPath]);p.on("error",bad);p.on("close",x=>x===0?ok():bad(new Error("ffmpeg_ws_"+x)))});const pcm=await readFile(pcmPath),events=[];console.log("VYTA_WS_SELFTEST_START",JSON.stringify({bytes:pcm.length}));await new Promise((resolve,reject)=>{const ws=new WebSocket("ws://127.0.0.1:"+port+"/v1/realtime/ws",{headers:{"x-vyta-runtime-secret":runtimeSecret}});const timer=setTimeout(()=>{ws.terminate();reject(new Error("ws_selftest_timeout"))},120000);ws.on("open",async()=>{console.log("VYTA_WS_SELFTEST_OPEN");ws.send(JSON.stringify({type:"ping"}));for(let o=0;o<pcm.length;o+=3200){ws.send(pcm.subarray(o,Math.min(o+3200,pcm.length)),{binary:true});await new Promise(r=>setTimeout(r,100))}ws.send(JSON.stringify({type:"audio.commit"}))});ws.on("message",d=>{try{const e=JSON.parse(String(d));if(e.type!=="audio.ack"){events.push(e);if(e.type==="pong"||e.type==="speech.start"||e.type==="speech.end"||e.type==="speech.final")console.log("VYTA_WS_EVENT",JSON.stringify(e));}if(e.type==="speech.final"&&String(e.text||"").toLowerCase().includes("answer is alive")){clearTimeout(timer);ws.close(1000,"selftest_done")}}catch{}});ws.on("close",()=>{clearTimeout(timer);resolve()});ws.on("error",e=>{clearTimeout(timer);reject(e)})});console.log("VYTA_WS_SELFTEST",JSON.stringify({bytes:pcm.length,events}))}finally{await rm(dir,{recursive:true,force:true}).catch(()=>{})}}catch(e){console.error("VYTA_WS_SELFTEST_FAILED",e.message)}}
if(process.env.VYTA_WS_SELFTEST==="1")setTimeout(()=>runWsSelfTest(),5000).unref();
